### PR TITLE
fix: mark enum variants as deprecated when their parent enum is deprecated

### LINKED ISSUE #22090: Completion: variant of a deprecated enum isn't shown as deprecated
**rust-analyzer version**: 0.3.2862-standalone

**rustc version**: rustc 1.94.1 (e408947bf 2026-03-25)

**editor or extension**: VSCode, extension version 0.3.2862

**relevant settings**: none

**repository link (if public, optional)**: none

**code snippet to reproduce**:
```rust
#[deprecated]
enum Foo {
    Bar,
}

fn main() {
    let b = Foo::$0 // `Bar` is suggested, but isn't stricken out
}

```

### PR DESCRIPTION
**Pull request by Brumbelow**
Closes rust-lang/rust-analyzer#22090.

- Completion items for variants of a `#[deprecated]` enum were not rendered as deprecated because `RenderContext::is_deprecated` only consulted the def's own attributes. PR rust-lang/rust-analyzer#22083 handled the trait→assoc-item propagation at the render layer. 

- This extends the same pattern to enum→variant via a small `is_variant_deprecated` helper, wired into both the path-completion and literal-completion render paths. Closes rust-lang/rust-analyzer#22090.

### CODE REVIEW

File: crates/ide-completion/src/tests/expression.rs [hunk 1]
```diff
@@ -3161,6 +3161,41 @@ fn foo() {
...
+        expect![[r#"
+            ev Bar Bar DEPRECATED
+        "#]],
+    );
+}
+
+#[test]
+fn deprecated_variant_of_undeprecated_enum_still_deprecated() {
+    // regression guard for rust-lang/rust-analyzer#22090 — the existing
+    // per-variant `#[deprecated]` behavior must keep working.
```
Comment (A4-Tacks) [inline crates/ide-completion/src/tests/expression.rs]: I think these comments are a bit redundant

**Review by A4-Tacks — APPROVED** [review]
Some nits


*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22116/f381976fa67d9b87ca6c2ae35f8277b13013abf8..616f182f01576fa0831a6078e16b897bf3e127a0)*

File: crates/ide-completion/src/tests/expression.rs (hunk 1 above)
Comment (A4-Tacks) [reply crates/ide-completion/src/tests/expression.rs]: Another test comment is also

Comment (Brumbelow) [reply crates/ide-completion/src/tests/expression.rs]: @A4-Tacks Fixed both and repushed

**Review by A4-Tacks — APPROVED** [review]

**Comment by ChayimFriedman2** [comment]
Please note that we require disclosure for AI usage.

**Comment by Brumbelow** [comment]
> Please note that we require disclosure for AI usage.

Thanks! I read CONTRIBUTING.md before opening my PR

@ChayimFriedman2 I should note the odd named commit is due to me not properly setting up my new environment initially. Sorry for any confusion!

Hope to contribute more in the future
