### PR TITLE
fix cargo check diagnostics are mapped incorrectly with non-BMP codepoints

### LINKED ISSUE #11945: `cargo check` diagnostics are mapped incorrectly with non-BMP codepoints
```rust
fn main() {
//        11111111122222
//2345678901234567802456
    let x: u32 = "𐐀𐐀𐐀𐐀";
}
```
For the file above RA sends the following diagnostics (not in json, but hopefully still readable):
```
[server-notification] Sat Apr  9 10:39:06 2022:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
	  (:uri "file:///home/nemethf/src/eglot/rust-2/main.rs" :diagnostics
		[(:range
		  (:start
		   (:line 3 :character 17)
		   :end
		   (:line 3 :character 23))
		  :severity 1 :code "E0308" :codeDescription
		  (:href "https://doc.rust-lang.org/error-index.html#E0308")
		  :source "rustc" :message "mismatched types\nexpected `u32`, found `&str`" :relatedInformation
		  [(:location
		    (:uri "file:///home/nemethf/src/eglot/rust-2/main.rs" :range
			  (:start
			   (:line 3 :character 11)
			   :end
			   (:line 3 :character 14)))
		    :message "expected due to this")])
...
```
The problem is character 23 does not exists.  The fancy letters take up two code units. 

Thanks!

cc @tsdh 

**rust-analyzer version**: rust-analyzer 9093941ed 2022-04-09 dev

**rustc version**:  rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: --

### PR DESCRIPTION
**Pull request by harpsword**
fix #11945

### CODE REVIEW

File: crates/rust-analyzer/src/diagnostics/to_proto.rs [hunk 1]
```diff
@@ -61,21 +61,39 @@ fn location(
...
+        for char in line.text.chars() {
+            char_offset += 1;
+            if char_offset > column_offset {
+                break;
+            }
+            if char.len_utf16() > 1 {
+                true_column_offset += char.len_utf16() - 1;
+            }
+        }
+    }
```
Comment (bjorn3) [inline crates/rust-analyzer/src/diagnostics/to_proto.rs:90]: The utf-8 to utf-16 conversion logic must only apply when `config.offset_encoding()` returns utf-16 and not when it returns utf-8.

File: crates/rust-analyzer/src/diagnostics/to_proto.rs [hunk 2]
```diff
@@ -61,21 +61,39 @@ fn location(
...
+fn position(
+    span: &DiagnosticSpan,
+    line_offset: usize,
+    column_offset: usize,
+) -> lsp_types::Position {
+    let line_index = line_offset - span.line_start;
+    let mut true_column_offset = column_offset;
+    if let Some(line) = span.text.get(line_index) {
+        let mut char_offset = 0;
+        for char in line.text.chars() {
```
Comment (bjorn3) [inline crates/rust-analyzer/src/diagnostics/to_proto.rs:81]: Character by character is slow for large inputs. Is it possible to get a fast path for ascii text?

**Comment by bjorn3** [comment]
Could you change the PR title to be more descriptive? I didn't know this was about utf-8 vs utf-16 issues in lsp until I read the diff.

File: crates/rust-analyzer/src/diagnostics/to_proto.rs (hunk 2 above)
Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:81]: i made a simple benchmark, for all ascii text, this will save 60% 

```
if let Some(line) = span.text.get(line_index) {
  if text.chars().count() == text.len() {
          // all utf-8 
          return position{}
      }
 .....
}

```

File: crates/rust-analyzer/src/diagnostics/to_proto.rs (hunk 1 above)
Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:101]: fixed

File: crates/rust-analyzer/src/diagnostics/to_proto.rs [hunk 3]
```diff
@@ -61,21 +61,51 @@ fn location(
...
+            };
+        }
+        let mut char_offset = 0;
+        for char in line.text.chars() {
+            char_offset += 1;
+            if char_offset > column_offset {
+                break;
+            }
+            let offset_shift = match config.offset_encoding {
+                OffsetEncoding::Utf8 => char.len_utf8() - 1,
```
Comment (bjorn3) [inline crates/rust-analyzer/src/diagnostics/to_proto.rs:96]: I think we can skip the entire mapping logic in case of utf-8.

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:96]: sorry, i don't understand how to skip the entire mapping logic in case of utf-8. 
But we can put `match` before `for` to get the func pointer, therefore `match` will run only once.

Comment (bjorn3) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs]: The old implementation of this function works fine for utf-8, right?

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs]: yes

Comment (bjorn3) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs]: I mean something like

```rust
fn position(
    config: &DiagnosticsMapConfig,
    span: &DiagnosticSpan,
    line_offset: usize,
    column_offset: usize,
) -> lsp_types::Position {
    if config.offset_encoding == OffsetEncoding::Utf8 {
        return lsp_types::Position::new(
            (span.line_start as u32).saturating_sub(1),
            (span.column_start as u32).saturating_sub(1),
        );
    }

    // ...
}
```

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs]: source code may contain three bytes or four bytes utf-8 character, for this situation, we cannot use span.column_start.

Comment (bjorn3) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs]: Why not? `column_start` would use the byte offset in case of `OffsetEncoding::Utf8`, right? This is exactly what rustc returns in it's json diagnostics.

File: crates/rust-analyzer/src/diagnostics/to_proto.rs [hunk 4]
```diff
@@ -61,21 +61,51 @@ fn location(
...
+    config: &DiagnosticsMapConfig,
+    span: &DiagnosticSpan,
+    line_offset: usize,
+    column_offset: usize,
+) -> lsp_types::Position {
+    let line_index = line_offset - span.line_start;
+
+    let mut true_column_offset = column_offset;
+    if let Some(line) = span.text.get(line_index) {
+        if line.text.chars().count() == line.text.len() {
```
Comment (lnicola) [inline crates/rust-analyzer/src/diagnostics/to_proto.rs:82]: It's not public, but we have a `utf16_lines` map which we could use for a fast(er) path.

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:82]: in order to use LineIndex::utf16_lines, we need to build `LineIndex` by snap.file_line_index(file_id). So we need to get file_id first, can you get file_id by file_path ?

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:82]: in `DiagnosticSpan` we only have character offset, we still need to iterate `DiagnosticSpan.text` to get corresponding BytePos of `DiagnosticSpan.column_start` and `DiagnosticSpan.column_end`.

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:82]: i found it( byte_start , byte_end).

Comment (lnicola) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:82]: > we need to build LineIndex by snap.file_line_index(file_id)

That's actually going to be cached.

I don't remember the code very well, but passing in a `LineIndex` might be fine. That should also work inside the tests.

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:105]: I add a new parameter `GlobalStateSnapshot` to `fn position` to build line_index. when encouner error in calling `from_proto::file_id` or `snap.file_line_index`, I will use original solution to get `lsp_types::range`. 

for test, i build a default `GlobalStateSnapshot` to use old test, but in this situation, the computation of `lsp_types::range` will use original solution instead of `to_proto::range(line_index, text_range)`. 

I cannot find any example of initing `GlobalState` in test, do you have any idea to init `GlobalState` in test to test `fn location` with new `to_proto::range(line_index, text_range)`?

Comment (matklad) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs:105]: I like chars().cont() solution more, because it guarantees consistent data -- we are using the text of the file according to rustc's POV. And we shouldn't worry about O(N)/O(1) here I think -- we transfered O(N) text of the span over the wire anyway.

**Review by matklad — APPROVED** [review]
LGTM!

**Comment by harpsword** [comment]
could you help me to merge it ? @lnicola  thanks

**Comment by matklad** [comment]
Sorry, forgot

@bors delegate=harpsword
