### PR TITLE
Fix allow extracting function from single brace of block expression

### LINKED ISSUE #14514: Extract function assist allows extracting single brace of block expression
```rs
fn f() {}
```
selecting either `{` or `}` shows the extract function assist which should not happen.

Relevant code is here https://github.com/rust-lang/rust-analyzer/blob/3dd17bcfc3d0e4d4e0c711828887d6f31602e415/crates/ide-assists/src/handlers/extract_function.rs

### PR DESCRIPTION
**Pull request by AmrDeveloper**
Fix allow extracting function when selecting either `{` or `}`

Fix #14514

### CODE REVIEW

**Comment by HKalbasi** [comment]
I think the fix should be more general. For example it should also not be applicable in `fn foo() { $0foo() }$0`.

File: crates/ide-assists/src/handlers/extract_function.rs [hunk 1]
```diff
@@ -70,6 +70,11 @@ pub(crate) fn extract_function(acc: &mut Assists, ctx: &AssistContext<'_>) -> Op
     }
 
     let node = ctx.covering_element();
+    if node.kind() == SyntaxKind::L_CURLY || node.kind() == SyntaxKind::R_CURLY {
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/extract_function.rs:73]: While we are at this, let's expand this to all kinds of braces (for brevity we can also use the `T!` macro, so `T!['{']`, `T!['(']`, ... which expand to the appropriate `SyntaxKind`)

**Comment by Veykril** [comment]
> I think the fix should be more general. For example it should also not be applicable in `fn foo() { $0foo() }$0`.

Ideally we'd reject that, but at least this kind of extraction doesn't break the syntax tree currently, so it's fine for this to be out of scope of this PR. (There are a lot more cases we should reject actually, I believe we can even extract plain operators right now which is non-sensical)

File: crates/ide-assists/src/handlers/extract_function.rs (hunk 1 above)
Comment (AmrDeveloper) [reply crates/ide-assists/src/handlers/extract_function.rs]: Done i expanded it to support (, [, {

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
