### PR TITLE
fix: Fix a case where completion was unable to expand a macro

### LINKED ISSUE #18719: Poor completion in `tracing` crate macros
**rust-analyzer version**: 0.3.2220-standalone

**rustc version**: any recent

**editor or extension**: VSCode, but shouldn't matter

**relevant settings**: none

**repository link (if public, optional)**: https://github.com/tokio-rs/tracing

**code snippet to reproduce**: 
```rust
let variable = "test";
tracing::info!(var<|>);
tracing::info!(name = var<|>);
```

Requesting completions in the two places in the snippet above comes up empty, but this is a valid place to put the `variable` local, which tracing will then emit as an event.

```rust
let variable = "test";
tracing::info!("{}", va<|>);
```

In this snippet, the `info!` macro is used just like `log::info!` can be, except with the `log` crate, rust-analyzer *does* manage to provide proper completions.

A fix for these would be great, since `tracing` is heavily favored over `log` in large parts of the ecosystem (eg. the whole async ecosystem, and bevy uses it too).

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Which caused the macros of the popular `tracing` crate to not offer completions.

The reason is rather complicated: it boils down to macro ignoring their input and completion always choosing the first expansion.

What started as a fairly simple feature request turned out to be a nightmary-ish group of changes on top of something that resembles a pile of hacks more than anything else (completions in IDEs). It turns out, well, this is not so simple. But at least it is fixed now, and tracing finally offers delicious completions!

https://github.com/user-attachments/assets/1338f1cd-c106-4c39-be9a-ab61d303e3cf

Fixes #18719.

### CODE REVIEW

File: crates/ide-completion/src/context/analysis.rs [hunk 1]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+        speculative_file,
+        original_offset: offset,
+        speculative_offset: offset,
+        fake_ident_token,
+        derive_ctx: None,
+    });
 
     // add the relative offset back, so that left_biased finds the proper token
-    let offset = expansion.offset + relative_offset;
+    let offset = expansion.original_offset + relative_offset;
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:80]:
```suggestion
    let original_offset = expansion.original_offset + relative_offset;
```
might as well

File: crates/ide-completion/src/context/analysis.rs [hunk 2]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+///         helper!($v);
+///         $v
+///     };
+/// }
+///
+/// my_macro!(complete_me_here)
+/// ```
+/// If we would expand the first thing we encounter only (which in fact this method used to do), we would
+/// be unable to complete here, because we would be walking directly into the void. So we instead try
+/// *every* possible path.
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:108]: Wouldn't it suffice to try paths until we find one where we don't end up in a token tree (where we would lose all semantic info)?

I guess ultimately we would want to pick the one that makes the most sense (as per the ranking, like is done for semantic highlighting and other IDE stuff).

File: crates/ide-completion/src/context/analysis.rs [hunk 3]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+        speculative_file.clone(),
+        offset,
+        fake_ident_token.clone(),
+        relative_offset,
+    )
+    .unwrap_or(ExpansionResult {
+        original_file,
+        speculative_file,
+        original_offset: offset,
+        speculative_offset: offset,
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:74]:
```suggestion
        speculative_offset: fake_ident_token.text_range().start(),
```

File: crates/ide-completion/src/context/analysis.rs [hunk 4]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+            .is_some_and(|original_token| !sema.might_be_inside_macro_call(&original_token))
+    {
+        return Some(ExpansionResult {
+            original_file,
+            speculative_file,
+            original_offset,
+            speculative_offset: fake_ident_token.text_range().start(),
+            fake_ident_token,
+            derive_ctx: None,
+        });
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:140]:
```suggestion
        return None;
```

File: crates/ide-completion/src/context/analysis.rs [hunk 5]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+            ) => {
+                let mut accumulated_offset_from_fake_tokens = 0;
+                let actual_range = actual_expansion.text_range().end();
+                let result = fake_mapped_tokens
+                    .into_iter()
+                    .filter_map(|(fake_mapped_token, rank)| {
+                        let accumulated_offset = accumulated_offset_from_fake_tokens;
+                        if fake_mapped_token.text().contains(COMPLETION_MARKER) {
+                            accumulated_offset_from_fake_tokens += COMPLETION_MARKER.len();
+                        }
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:181]: This makes me wonder, shouldn't we just straight up filter out mappings that map the span to a token that has differing text than our marker? It feels unintentional for macro authors for that to having an effect on completions imo.

File: crates/ide-completion/src/context/analysis.rs [hunk 6]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+                    )?;
+                    Some((result, rank))
+                })
+                .min_by_key(|(_, rank)| *rank)
+                .map(|(result, _)| result);
         }
-
-        // none of our states have changed so stop the loop
-        break 'expansion;
+        // at least on expansion failed, we won't have anything to expand from this point
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:384]:
```suggestion
        // at least one expansion failed, we won't have anything to expand from this point
```

File: crates/ide-completion/src/context/analysis.rs [hunk 7]
```diff
@@ -54,226 +59,334 @@ pub(super) fn expand_and_analyze(
...
+            &actual_macro_call,
+            &speculative_args,
+            fake_ident_token.clone(),
+        ),
+    ) {
+        // successful expansions
+        (Some(actual_expansion), Some((fake_expansion, fake_mapped_tokens))) => {
+            let mut accumulated_offset_from_fake_tokens = 0;
+            let actual_range = actual_expansion.text_range().end();
+            return fake_mapped_tokens
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:356]: can drop the return here and move the final `None` into the other arm
```suggestion
            fake_mapped_tokens
```

**Review by Veykril — COMMENTED** [review]
I sure can't wait for salsa 3 and its promised database forking so that we can get rid of the speculative stuff

File: crates/ide-completion/src/context/analysis.rs (hunk 2 above)
Comment (ChayimFriedman2) [reply crates/ide-completion/src/context/analysis.rs:108]: Yes, the problem is ranking.

It is possible to optimize this a bit if we give up the *best of all* ranking and chose *the best in the first non-macro expansion*. This will still require looping over the tokens to calculate the offset. Can do that if requested, didn't do that because it seems it won't cause problems to just expand everything.

Comment (Veykril) [reply crates/ide-completion/src/context/analysis.rs:108]: Ye I don't think perf will matter here much, if there is a highly recursive macro somewhere completions will become sluggish either way. So considering all seems the way to go (especially as at some point we'd do https://github.com/rust-lang/rust-analyzer/issues/11058 which requires that as well anyways)

File: crates/parser/src/grammar/items.rs [hunk 8]
```diff
@@ -72,8 +72,19 @@ pub(super) fn item_or_macro(p: &mut Parser<'_>, stop_on_r_curly: bool, is_in_ext
...
+        paths::use_path(p);
+        // Do not create a MACRO_CALL node here if this isn't a macro call, this causes problems with completion.
+
+        // test_err path_item_without_excl
+        // foo
+        if p.at(T![!]) {
+            macro_call(p, m);
+            return;
+        } else {
+            m.complete(p, ITEM_RECOVERY);
```
[the remark this answers is not in the document]
Comment (ChayimFriedman2) [reply crates/parser/src/grammar/items.rs:84]: I tried `Error` and it didn't work previously, but it was probably because of some other problem, because it works now. I'll change to it.

File: crates/ide-completion/src/context/analysis.rs (hunk 4 above)
Comment (ChayimFriedman2) [reply crates/ide-completion/src/context/analysis.rs:140]: We can't, this is the recursion base case.

File: crates/ide-completion/src/context/analysis.rs (hunk 5 above)
Comment (ChayimFriedman2) [reply crates/ide-completion/src/context/analysis.rs:182]: Do you want me to do that?

Comment (Veykril) [reply crates/ide-completion/src/context/analysis.rs:182]: I'd say yes

Comment (ChayimFriedman2) [reply crates/ide-completion/src/context/analysis.rs:182]: Done.

**Comment by Veykril** [comment]
> Does salsa 3 already have db forking or it's only planned?

I think some very rudimentary forking is implemented, but the stuff that we need specifically (the fork having copy on write semantics aka speculative execution) is still missing

**Comment by ChayimFriedman2** [comment]
Needed to rebase and bless - @Veykril can you re-approve? Thanks.

**Review by Veykril — APPROVED** [review]
