### PR TITLE
fix: Make edition per-token, not per-file

### LINKED ISSUE #18857: Using await inside a macro defined by an edition 2015 crate fails with E0559
When using an expression that includes `.await` as the first argument to [`assert_matches::assert_matches`](https://docs.rs/assert_matches/latest/assert_matches/macro.assert_matches.html) from an edition 2021 crate, rust-analyzer reports an error

```
no field `r#await` on type `impl Future<Output = ...>`
```

which is wrong because the expression with the `.await` has a span from the actual file it's written in, and thus can use `.await`. (things are just fine outside of RA)

**rust-analyzer version**: 0.4.2248-standalone
**rustc version**: 1.86.0-nightly (3f43b1a63 2025-01-03)
**editor or extension**: VSCode, extension v0.4.2248

I can provide a proper reproducer if it turns out my basic instructions above don't work all the time (didn't minimize yet but this seems like a pretty clear bug).

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
More correctly, *also* per-token. Because as it turns out, while the top-level edition affects parsing (I think), the per-token edition affects escaping of identifiers/keywords.

Fixes #18857.

CC @davidbarsky, I know the `SyntaxContextId` stuff is problematic for new Salsa and I don't know enough your solution, can you take a look this isn't problematic?

### CODE REVIEW

File: crates/hir-def/src/macro_expansion_tests/mbe.rs [hunk 1]
```diff
@@ -35,9 +35,9 @@ macro_rules! f {
     };
 }
 
-struct#0:1@58..64#1# MyTraitMap2#0:2@31..42#0# {#0:1@72..73#1#
-    map#0:1@86..89#1#:#0:1@89..90#1# #0:1@89..90#1#::#0:1@91..93#1#std#0:1@93..96#1#::#0:1@96..98#1#collections#0:1@98..109#1#::#0:1@109..111#1#HashSet#0:1@111..118#1#<#0:1@118..119#1#(#0:1@119..120#1#)#0:1@120..121#1#>#0:1@121..122#1#,#0:1@122..123#1#
-}#0:1@132..133#1#
+struct#0:1@58..64#4# MyTraitMap2#0:2@31..42#2# {#0:1@72..73#4#
```
Comment (ChayimFriedman2) [inline crates/hir-def/src/macro_expansion_tests/mbe.rs:38]: We really ought to do something about these tests, in new Salsa they change every time someone create a new interned type and that is awful.

**Comment by Veykril** [comment]
> More correctly, also per-token. Because as it turns out, while the top-level edition affects parsing (I think), the per-token edition affects escaping of identifiers/keywords.

Yep, edition is part of hygiene (which is a per token, or well, per span thing)

File: crates/edition/src/lib.rs [hunk 2]
```diff
@@ -2,6 +2,7 @@
 // This should live in a separate crate because we use it in both actual code and codegen.
 use std::fmt;
 
+// The syntax context stuff needs the discriminants to start from 0 and be consecutive.
```
Comment (Veykril) [inline crates/edition/src/lib.rs:5]: Might be better to set the first variant `= 0` then with the comment on that?

File: crates/hir-def/src/macro_expansion_tests/mbe.rs (hunk 1 above)
Comment (Veykril) [reply crates/hir-def/src/macro_expansion_tests/mbe.rs:38]: Yes, we talked about that on zulip iirc, for new salsa a bunch of tests need to change the rendering of what they expect. For this kind of stuff we likely need to have the test allocate a map and assign stable IDs that way

File: crates/hir-expand/src/builtin/derive_macro.rs [hunk 3]
```diff
@@ -58,8 +58,8 @@ impl BuiltinDeriveExpander {
         tt: &tt::TopSubtree,
         span: Span,
     ) -> ExpandResult<tt::TopSubtree> {
-        let span = span_with_def_site_ctxt(db, span, id);
-        self.expander()(span, tt)
+        let span = span_with_def_site_ctxt(db, span, id, Edition::CURRENT);
```
Comment (Veykril) [inline crates/hir-expand/src/builtin/derive_macro.rs:61]: Now I wonder, what is the edition rustc sets for these? Presumably its the edition of the standard library?

File: crates/syntax-bridge/src/lib.rs [hunk 4]
```diff
@@ -141,15 +141,17 @@ where
...
 where
-    SpanData<Ctx>: Copy + fmt::Debug,
-    Ctx: PartialEq,
+    Ctx: Copy + fmt::Debug + PartialEq + PartialEq + Eq + Hash,
 {
     let buffer = tt.view().strip_invisible();
-    let parser_input = to_parser_input(edition, buffer);
-    let parser_output = entry_point.parse(&parser_input, edition);
+    let parser_input = to_parser_input(buffer, span_to_edition);
+    // FIXME: Does it really matter what edition we parse with if we escape all identifiers correctly?
```
Comment (Veykril) [inline crates/syntax-bridge/src/lib.rs:152]: Yes it does, lexing and parsing is both independently edition dependent.

File: crates/span/src/hygiene.rs [hunk 5]
```diff
@@ -59,11 +91,23 @@ impl fmt::Display for SyntaxContextId {
...
+            self
+        }
+    }
+
     /// The root context, which is the parent of all other contexts. All [`FileId`]s have this context.
-    pub const ROOT: Self = SyntaxContextId(unsafe { InternId::new_unchecked(0) });
+    pub const fn root(edition: Edition) -> Self {
+        SyntaxContextId(unsafe { InternId::new_unchecked(edition as u32) })
+    }
+    // pub const ROOT: Self = ;
```
Comment (Veykril) [inline crates/span/src/hygiene.rs:107]:
```suggestion
```

File: crates/hir-expand/src/name.rs [hunk 6]
```diff
@@ -85,6 +85,11 @@ impl Name {
         Self::new_text(text)
     }
 
+    pub fn new_root(text: &str) -> Name {
+        // The edition doesn't matter for hygiene.
```
Comment (Veykril) [inline crates/hir-expand/src/name.rs:89]: It technically does matter for our displaying of names (it should affect the r# escaping), but I don't think that is too important here for now, given our Names are not properly using hygiene right now

File: crates/hir-expand/src/db.rs [hunk 7]
```diff
@@ -699,9 +700,9 @@ fn expand_proc_macro(
             loc.krate,
             &macro_arg,
             attr_arg,
-            span_with_def_site_ctxt(db, span, id),
-            span_with_call_site_ctxt(db, span, id),
-            span_with_mixed_site_ctxt(db, span, id),
+            span_with_def_site_ctxt(db, span, id, loc.def.edition),
+            span_with_call_site_ctxt(db, span, id, loc.def.edition),
+            span_with_mixed_site_ctxt(db, span, id, loc.def.edition),
```
Comment (Veykril) [inline crates/hir-expand/src/db.rs:705]: I am not entirely sure this right, need to double check with rustc here

File: crates/mbe/src/lib.rs [hunk 8]
```diff
@@ -369,7 +369,8 @@ pub fn expect_fragment<'t>(
 ) -> ExpandResult<tt::TokenTreesView<'t, Span>> {
     use ::parser;
     let buffer = tt_iter.remaining();
-    let parser_input = to_parser_input(edition, buffer);
+    // FIXME: Pass the correct edition per token. Due to the split between mbe and hir-expand it's complicated.
+    let parser_input = to_parser_input(buffer, &mut |_ctx| edition);
```
Comment (Veykril) [inline crates/mbe/src/lib.rs:373]: Why is that? syntax context lookup isn't defined on the `ExpandDatabase` is it?

File: crates/span/src/hygiene.rs [hunk 9]
```diff
@@ -26,12 +26,44 @@ use crate::InternId;
...
+        Some(self.cmp(other))
+    }
+}
+
+impl PartialEq for SyntaxContextId {
+    #[inline]
+    fn eq(&self, other: &Self) -> bool {
+        self.remove_root_edition().0 == other.remove_root_edition().0
+    }
+}
```
Comment (Veykril) [inline crates/span/src/hygiene.rs:65]: Doesn't this break interning for salsa? The editions we intern are load bearing, we should do these changes in `Name`'s implementations instead

File: crates/span/src/hygiene.rs [hunk 10]
```diff
@@ -59,11 +91,23 @@ impl fmt::Display for SyntaxContextId {
...
     /// The root context, which is the parent of all other contexts. All [`FileId`]s have this context.
-    pub const ROOT: Self = SyntaxContextId(unsafe { InternId::new_unchecked(0) });
+    pub const fn root(edition: Edition) -> Self {
+        SyntaxContextId(unsafe { InternId::new_unchecked(edition as u32) })
+    }
+    // pub const ROOT: Self = ;
 
     pub fn is_root(self) -> bool {
-        self == Self::ROOT
+        self.into_u32() <= Edition::LATEST as u32
```
Comment (Veykril) [inline crates/span/src/hygiene.rs:110]: So in new salsa we still do kind of the same thing see https://github.com/rust-lang/rust-analyzer/commit/f0ab7420a2071b8eb2da223df920ae89590ef81a

But instead of using `0` we now use the max ID - 1 (which is the actual maximum), now that we have multiple roots we would need to change the check to ignore the page bits but otherwise this change should not be a problem for the salsa upgrade

**Comment by Veykril** [comment]
Neat, I knew we were missing this when I was implementing the hygiene setup but expected this to be a lot more annoying to get to work. Glad to have been proven wrong.

File: crates/hir-expand/src/db.rs (hunk 7 above)
Comment (Veykril) [reply crates/hir-expand/src/db.rs:705]: Hmm, so rustc only has the concept of the "local crate" here, that is the crate that is being analyzed right now (we can't model it like that). In my eyes, that would imply we ought to fill the call site edition here instead?

File: crates/hir-expand/src/name.rs (hunk 6 above)
Comment (ChayimFriedman2) [reply crates/hir-expand/src/name.rs:89]: Displaying of names does not depend on the edition they were written with but on the edition were they are shown, and it's already handled.

File: crates/span/src/hygiene.rs (hunk 9 above)
Comment (ChayimFriedman2) [reply crates/span/src/hygiene.rs:65]: Ah I haven't thought about that, this doesn't seem to break salsa but maybe it does, anyway ignoring them on `Name` was something I thought about as an alternative.

File: crates/mbe/src/lib.rs (hunk 8 above)
Comment (ChayimFriedman2) [reply crates/mbe/src/lib.rs:373]: It is.

File: crates/hir-expand/src/name.rs (hunk 6 above)
Comment (Veykril) [reply crates/hir-expand/src/name.rs:93]: Right

File: crates/mbe/src/lib.rs (hunk 8 above)
Comment (Veykril) [reply crates/mbe/src/lib.rs:373]: Ah drats, forgot we define the id in span, but not the content (we probably need to do use some extra trait setup to fix that post salsa swap to do dependency injection)
