### PR TITLE
fix: Extend `type_variable_table` when modifying index is larger than the table size

### LINKED ISSUE #18109: thread 'Worker' panicked at crates/hir-ty/src/infer/unify.rs:276:33:
I was editing my code and suddenly started getting the following crash every time I tried to hover over something. I don't know exactly what triggered :S

```text
hread 'Worker' panicked at crates/hir-ty/src/infer/unify.rs:276:33:
index out of bounds: the len is 67 but the index is 67
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce_inner
   4: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce
   5: hir_ty::infer::coerce::<impl hir_ty::infer::InferenceContext>::coerce
   6: hir_ty::infer::coerce::CoerceMany::coerce
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  14: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  15: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  16: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  17: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  18: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  19: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  20: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  21: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
  22: hir_ty::infer::infer_query
  23: salsa::Cycle::catch
  24: salsa::derived::slot::Slot<Q>::execute
  25: salsa::derived::slot::Slot<Q>::read
  26: <DB as hir_ty::db::HirDatabase>::infer::__shim
  27: <DB as hir_ty::db::HirDatabase>::infer
  28: hir::semantics::SemanticsImpl::analyze_impl
  29: hir::semantics::SemanticsImpl::resolve_bind_pat_to_const
  30: ide_db::defs::NameClass::classify
  31: ide_db::defs::IdentClass::classify_node
  32: ide::hover::hover_offset
  33: salsa::Cancelled::catch
  34: rust_analyzer::handlers::request::handle_hover
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:34:04 PM] Request textDocument/hover failed.
  Message: request handler panicked: index out of bounds: the len is 67 but the index is 67
  Code: -32603 
```

**rust-analyzer version**: rust-analyzer version: 0.4.2108-standalone [/home/nlehmann/.vscode/extensions/rust-lang.rust-analyzer-0.4.2108-linux-x64/server/rust-analyzer]

**rustc version**: rustc 1.82.0-nightly (636d7ff91 2024-08-19)

**editor or extension**: VSCode

**repository link (if public, optional)**: https://github.com/flux-rs/flux/tree/snapshot-for-ra

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #18109

Whenever we create an inference variable in r-a, we extend `type_variable_table` to matching size here;

https://github.com/rust-lang/rust-analyzer/blob/f4aca78c92e03354327c8f6c7fefaef9f45ab166/crates/hir-ty/src/infer/unify.rs#L378-L381 

But sometimes, an inference variable is [created from chalk](https://github.com/rust-lang/chalk/blob/ab710e0c9b455403b138ef72a2fb90967a58eff3/chalk-solve/src/infer/unify.rs#L743) and passed to r-a as a type of an expression or a pattern.
If r-a set diverging flag to this before the table is extended to a sufficient size, it panics here;

https://github.com/rust-lang/rust-analyzer/blob/f4aca78c92e03354327c8f6c7fefaef9f45ab166/crates/hir-ty/src/infer/unify.rs#L275-L277

I think that extending table when setting diverging flag is reasonable becase we are already doing such extending to a size that covers the inference vars created from chalk and this change only covers the order-dependent random cases that this might fail

### CODE REVIEW

File: crates/hir-ty/src/infer/unify.rs [hunk 1]
```diff
@@ -266,14 +266,16 @@ impl<'a> InferenceTable<'a> {
             }
             let v = InferenceVar::from(i as u32);
             let root = self.var_unification_table.inference_var_root(v);
-            if let Some(data) = self.type_variable_table.get_mut(root.index() as usize) {
-                *data |= TypeVariableFlags::DIVERGING;
-            }
+            self.modify_type_variable_flag(root, |f| {
+                *f |= TypeVariableFlags::DIVERGING;
+            });
```
Comment (ShoyuVanilla) [inline crates/hir-ty/src/infer/unify.rs:271]: I think that doing this is also reasonable for the same reason

**Review by Veykril — APPROVED** [review]
