### PR TITLE
pass struct fields to chalk

### LINKED ISSUE #19003: Code passes initial check, but fails on closure-dyn type check after any operation
**rust-analyzer version**: both stable and pre-release *(0.3.2273-standalone (248bd511ae 2025-01-18) and 0.4.2276-standalone (0b68402d78 2025-01-21))*

**rustc version**: rustc 1.84.0 (9fc6b4312 2025-01-07)

**editor or extension**: VSCode

**relevant settings**: rustc_wrapper = sccache

**repository link (if public, optional)**: None

**code snippet to reproduce**: 
```rust
use std::sync::{Arc, Mutex};
fn need(x: Arc<Mutex<dyn FnMut(i32) -> i32>>) {
    todo!()
}
fn main() {
    let callback = |x| x;
    let mut callback = need(Arc::new(Mutex::new(callback)));
}
```

reproduce: 
1. copy this snippet to a new cargo project
2. Run `cargo check` or `cargo clippy` — the code passes.
3. Restart the RA LSP — the code passes the initial check.
4. Make a minor change (e.g., add a space somewhere in the code) to trigger a recheck in RA. RA now reports an error: `expected Arc<Mutex<dyn FnMut(i32) -> i32>, Global>, found Arc<Mutex<{closure#1}>, Global> rust-analyzer ([E0308](https://doc.rust-lang.org/stable/error_codes/E0308.html))`

### PR DESCRIPTION
**Pull request by Austaras**
Closes #19003

### CODE REVIEW

File: crates/hir-ty/src/chalk_db.rs [hunk 1]
```diff
@@ -768,8 +768,7 @@ pub(crate) fn adt_datum_query(
         phantom_data,
     };
 
-    // this slows down rust-analyzer by quite a bit unfortunately, so enabling this is currently not worth it
```
Comment (Austaras) [inline crates/hir-ty/src/chalk_db.rs:771]: I don't really know how much it would be slower -- if significantly slower, it's possible to find another way to work around this.

File: crates/hir-ty/src/tests/coercion.rs [hunk 2]
```diff
@@ -536,17 +536,15 @@ fn test() {
...
         r#"
 //- minicore: coerce_unsized
-struct Foo<T> { t: T };
-struct Bar<T>(Foo<T>);
+struct Foo<T: ?Sized> { t: T };
+struct Bar<T: ?Sized>(Foo<T>);
 
 fn test() {
     let _: &Foo<[usize]> = &Foo { t: [1, 2, 3] };
-                         //^^^^^^^^^^^^^^^^^^^^^ expected &'? Foo<[usize]>, got &'? Foo<[i32; 3]>
```
Comment (Austaras) [inline crates/hir-ty/src/tests/coercion.rs:547]: This test case is effectively the same with the added one, just different kind of coerce unsized

File: crates/hir-ty/src/chalk_db.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/hir-ty/src/chalk_db.rs:771]: You can benchmark using `rust-analyzer analysis-stats .` on the rust-analyzer repository.

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: master(35181e167e)
```
Database loaded:     40.68s, 58mb (metadata 37.21s, 1949kb; build 2.78s, -725kb)
  item trees: 1336
Item Tree Collection: 429.36ms, 28mb
  crates: 62, mods: 1166, decls: 33774, bodies: 30989, adts: 2355, consts: 1866
Item Collection:     4.63s, 423mb
Body lowering:       2.56s, 286mb
  exprs: 925899, ??ty: 60 (0%), ?ty: 125 (0%), !ty: 1
  pats: 196345, ??ty: 9 (0%), ?ty: 4 (0%), !ty: 0
Inference:           34.59s, 689mb
MIR lowering:        6.00s, 393mb
Mir failed bodies: 44 (0%)
Data layouts:        49.45ms, 7mb
Failed data layouts: 1 (0%)
Const evaluation:    34.16ms, 5mb
Failed const evals: 5 (0%)
Total:               48.28s, 1833mb
```
current(dcf9ca77df)
```
Database loaded:     3.09s, 60mb (metadata 316.07ms, 1949kb; build 2.41s, -813kb)
  item trees: 1336
Item Tree Collection: 429.91ms, 29mb
  crates: 62, mods: 1166, decls: 33775, bodies: 30990, adts: 2355, consts: 1866
Item Collection:     4.69s, 421mb
Body lowering:       2.60s, 286mb
  exprs: 925899, ??ty: 60 (0%), ?ty: 125 (0%), !ty: 1
  pats: 196343, ??ty: 9 (0%), ?ty: 4 (0%), !ty: 0
Inference:           45.29s, 701mb
MIR lowering:        7.01s, 392mb
Mir failed bodies: 44 (0%)
Data layouts:        49.25ms, 8mb
Failed data layouts: 1 (0%)
Const evaluation:    34.64ms, 5mb
Failed const evals: 5 (0%)
Total:               60.11s, 1845mb
```

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: current(dcf9ca77df)
```
Database loaded:     787.41ms, 60mb (metadata 311.40ms, 1949kb; build 101.45ms, -815kb)
  item trees: 1336
Item Tree Collection: 431.62ms, 30mb
  crates: 62, mods: 1166, decls: 33775, bodies: 30990, adts: 2355, consts: 1866
Item Collection:     4.58s, 421mb
Body lowering:       2.51s, 286mb
  exprs: 925897, ??ty: 60 (0%), ?ty: 125 (0%), !ty: 1
  pats: 196342, ??ty: 9 (0%), ?ty: 4 (0%), !ty: 0
Inference:           44.30s, 696mb
MIR lowering:        7.05s, 392mb
Mir failed bodies: 44 (0%)
Data layouts:        49.62ms, 8mb
Failed data layouts: 1 (0%)
Const evaluation:    34.29ms, 5mb
Failed const evals: 5 (0%)
Total:               58.96s, 1840mb
```

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: I don't know if it's acceptable or not.

Comment (ChayimFriedman2) [reply crates/hir-ty/src/chalk_db.rs:771]: That's... not good. 12s difference is quite a lot. I'm not sure it's worth it. Do you know what Chalk uses the fields for?

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: For impl auto trait, chalk need to know fields of structs. This could be worked around by impl auto trait ourself

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: The linked issue arises because `Mutex<T>` should have `impl<T: Unsize<U>, U> Unsize<U> for Mutex<T>` but not in r-a.

Comment (ChayimFriedman2) [reply crates/hir-ty/src/chalk_db.rs:771]: But `Unsize` isn't an auto trait?

Or is Chalk also using the type of the last field for unsizing coercions?

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: > But `Unsize` isn't an auto trait?

It is, see [doc](https://doc.rust-lang.org/std/marker/trait.Unsize.html)

> Or is Chalk also using the type of the last field for unsizing coercions?

This is also true, as stated in the third point of aforementioned doc

Comment (ChayimFriedman2) [reply crates/hir-ty/src/chalk_db.rs:771]: Ah, I thought you meant auto traits in the conventional sense, aka `auto trait`, like `Send` and `Sync`. `Unsize` is not an auto trait in that sense, although it is, as you said, implemented automatically by the compiler.

Comment (ChayimFriedman2) [reply crates/hir-ty/src/chalk_db.rs:771]: Anyway: if you want to play with Chalk and find ways to minimize the losses, good luck. If not, I'll leave it to @Veykril whether to accept this PR.

Comment (Veykril) [reply crates/hir-ty/src/chalk_db.rs:771]: Would it suffice to just supply the tail field then?

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: I tried but they made almost no difference performance wise, like 1 or 2 seconds fewer.

Comment (Veykril) [reply crates/hir-ty/src/chalk_db.rs:771]: Hmm, I imagine the actual slowdown comes from the `field_types` query (which we otherwise only ever call when a field access happens).

I'd rather wait on the new trait solver then as that perf regression is quite severe

Comment (flodiebold) [reply crates/hir-ty/src/chalk_db.rs:771]: IMO we should revisit this with the new solver, but there's not much point in spending time on teaching to find a solution with Chalk.

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:771]: new commit(a48cb25b1c)
```
Database loaded:     3.13s, 60mb (metadata 314.47ms, 1949kb; build 2.44s, -815kb)
  item trees: 1336
Item Tree Collection: 431.26ms, 28mb
  crates: 62, mods: 1166, decls: 33775, bodies: 30990, adts: 2355, consts: 1866
Item Collection:     4.59s, 422mb
Body lowering:       2.51s, 286mb
  exprs: 925899, ??ty: 653 (0%), ?ty: 933 (0%), !ty: 60
  pats: 196340, ??ty: 133 (0%), ?ty: 217 (0%), !ty: 0
Inference:           36.35s, 690mb
MIR lowering:        6.10s, 383mb
Mir failed bodies: 229 (0%)
Data layouts:        50.56ms, 6mb
Failed data layouts: 1 (0%)
Const evaluation:    34.33ms, 4005kb
Failed const evals: 5 (0%)
Total:               50.07s, 1822mb
```
guess we good now

File: crates/hir-ty/src/chalk_db.rs [hunk 3]
```diff
@@ -768,23 +768,21 @@ pub(crate) fn adt_datum_query(
...
-            let field_types = db.field_types(id);
-            variant_data
-                .fields()
-                .iter()
-                .map(|(idx, _)| field_types[idx].clone().substitute(Interner, &bound_vars_subst))
-                .filter(|it| !it.contains_unknown())
-                .collect()
+            // HACK: provide full struct type info slows down rust-analyzer by quite a bit unfortunately,
+            // so we trick chalk into thinking that our struct impl Unsize
+            if let Some(ty) = bound_vars_subst.at(Interner, 0).ty(Interner) {
```
Comment (Veykril) [inline crates/hir-ty/src/chalk_db.rs:778]: What is the first bound var in this context? (has been a while since I touched this here)

Comment (Austaras) [reply crates/hir-ty/src/chalk_db.rs:778]: Basically this is make chalk believe every struct with generic type is `struct Foo<T>(T)`

Comment (Veykril) [reply crates/hir-ty/src/chalk_db.rs:778]: I wonder if this could cause other issues, also wouldn't this only work out where the first supplied parameter type is actually unsizable?

**Comment by Veykril** [comment]
Alright lets give this a test run then, if it doesn't break anything we can keep this as a best effort tradeoff until we switch to the new solver

**Comment by Veykril** [comment]
This is causing major regressions as I expected so we gotta roll this back https://rust-analyzer.github.io/metrics/?start=2025-02-16&end=
