### PR TITLE
fix: show diagnostic for } token followed by else in let else statement

### LINKED ISSUE #14221: Show diagnostic for `}` token followed by `else` in let else statement
`}` braces before `else` in `let ... else` statements are not permitted, we should show an error here.
```rs
let Some(node) = match expr_or_pat {
    hir_def::expr::ExprOrPatId::ExprId(expr) => expr_node(&body_source_map, expr, &db),
    hir_def::expr::ExprOrPatId::PatId(pat) => pat_node(&body_source_map, pat, &db),
} else { continue; };
```

### PR DESCRIPTION
**Pull request by XFFXFF**
fix #14221 

My thinking is to check if the `expr` after `=` is block like when parse `let ... lese` , and if so, emit error.

### CODE REVIEW

File: crates/parser/src/grammar/expressions.rs [hunk 1]
```diff
@@ -16,9 +16,9 @@ pub(super) enum Semicolon {
 
 const EXPR_FIRST: TokenSet = LHS_FIRST;
 
-pub(super) fn expr(p: &mut Parser<'_>) -> bool {
+pub(super) fn expr(p: &mut Parser<'_>) -> Option<CompletedMarker> {
     let r = Restrictions { forbid_structs: false, prefer_stmt: false };
-    expr_bp(p, None, r, 1).is_some()
+    expr_bp(p, None, r, 1).map(|(m, _)| m)
```
Comment (XFFXFF) [inline crates/parser/src/grammar/expressions.rs:21]: I found that the `BlockLike` returned by `expr_bp` is only useful if `prefer_stmt` is `true`, otherwise it is always `NotBlock`, so I don't make this function reutrn `BlockLike`

File: crates/parser/src/grammar/expressions.rs [hunk 2]
```diff
@@ -120,16 +120,32 @@ pub(super) fn stmt(p: &mut Parser<'_>, semicolon: Semicolon) {
...
+        let mut is_block_like_expr_after_eq = false;
         if p.eat(T![=]) {
             // test let_stmt_init
             // fn f() { let x = 92; }
-            expressions::expr(p);
+            let expr = expressions::expr(p);
+
+            if let Some(expr) = expr {
+                is_block_like_expr_after_eq = match expr.kind() {
+                    IF_EXPR | WHILE_EXPR | FOR_EXPR | LOOP_EXPR | MATCH_EXPR | BLOCK_EXPR => true,
```
Comment (Veykril) [inline crates/parser/src/grammar/expressions.rs:132]: Can we extract this match into an assocaited function on `BlockLike` since this is duplicated now and runs risk of going out of sync from the other place

Comment (XFFXFF) [reply crates/parser/src/grammar/expressions.rs:132]: Yes

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
