### PR TITLE
fix: Make `rust-analyzer.files.excludeDirs` work, actually

### LINKED ISSUE #14734: rust-analyzer.files.excludeDirs is (still) not working
`rust-analyzer.files.excludeDirs` does not appear to be working. Issue #7755 discussed this awhile ago and was closed, but the feature is still not working for me. I am using rust-analyzer 0.4.1501-standalone with rustc 1.68.2 in VSCode.

It could be that I misunderstand how to specify directories. My project layout is
```
.
├── src
        ├── module0
```
and my rust analyzer setting is
```
{
  "rust-analyzer.files.excludeDirs: ["src/module0"]
}
```
I tried also setting `files.watcherExclude`, as suggested in the documentation, but no luck.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
I have no idea what the original writer of the code thought (CC @matklad, I don't expect you to remember but it was you), but the logic just seems backwards. We should not exclude a file/directory if it is equal to an include! This also meant that we had to add a `root == path` check so this stuff will actually work, which in turn meant excludes (of root files) no longer worked...

Also rename if to `rust-analyzer.files.exclude`, because it can exclude files as well.

Fixes #14734.

### CODE REVIEW

**Comment by matklad** [comment]
The original logic still looks correct to me!

It handles nested entries. If root B is nested under A, and C is excluded, then, while scanning A:

* you should ignore C as it is explicitly excluded
* But you _also_ should ignore B, as you get to scanning the contents of B separately

That is, there’s an outer loop over A and B anyway. Without this exclusion, B will be scanned twice

**Comment by ChayimFriedman2** [comment]
Okay, so the logic needs to be:
```rust
dirs.exclude.iter().all(|it| it != path) && (root == path || dirs.include.iter().all(|it| it != path))
```

**Comment by matklad** [comment]
To make sure I understand correctly, what happens here is that the same path ends up in exclude (explicitly configured by the user) and also in the include (I am guessing through auto-discovery mechanism)?

🤔 

Should be perhaps push the if up here? In VFS, we can assert that neither path is simultaneously in the inclusion and exclusion list. 

In the project-discovery code, we can explicitly exclude the excluded directories. 

---

Unrelated, but, due to a bug in GitHub, it is best not to include @-mentions in the commit messages. GitHub incorrectly sends a email-notification every time such a commit is pushed, including rebases and forks.

Pings in PR descriptions are totally fine and encouraged!

**Comment by ChayimFriedman2** [comment]
> To make sure I understand correctly, what happens here is that the same path ends up in exclude (explicitly configured by the user) and also in the include (I am guessing through auto-discovery mechanism)?

Yes, exactly.

> Should be perhaps push the if up here? In VFS, we can assert that neither path is simultaneously in the inclusion and exclusion list.

I don't think, I think it's fine as it's now.

> Unrelated, but, due to a bug in GitHub, it is best not to include @-mentions in the commit messages. GitHub incorrectly sends a email-notification every time such a commit is pushed, including rebases and forks.

Didn't know, sorry! I edited the commit message.

File: crates/rust-analyzer/src/handlers/notification.rs [hunk 1]
```diff
@@ -127,7 +136,7 @@ pub(crate) fn handle_did_close_text_document(
             tracing::error!("orphan DidCloseTextDocument: {}", path);
         }
 
-        if let Some(file_id) = state.vfs.read().0.file_id(&path) {
+        if let Some((file_id, vfs::FileExcluded::No)) = state.vfs.read().0.file_id(&path) {
```
Comment (Veykril) [inline crates/rust-analyzer/src/handlers/notification.rs:139]: I think we want to do this irrespective of exclusion (in the rare case that someone adds an exclusion for a file that has diagnostics, assuming that even works)

**Review by Veykril — APPROVED** [review]
Unfortunate that we have to encode this specially in the VFS (and then effectively handle in every request handler), but it does make sense as to why (and I can't think of a different way to do this either)

File: crates/rust-analyzer/src/handlers/notification.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/rust-analyzer/src/handlers/notification.rs:139]: Exclusions require reload (at least that's what the VSCode client tells me), but sure, why not.

Comment (Veykril) [reply crates/rust-analyzer/src/handlers/notification.rs]: Figured as much, though it doesn't hurt to do this either way

**Comment by futile** [comment]
Ping, kind of waiting for this (I think it'll solve my "Roots scanned" issue), and wanted to ask when it can/will be merged? thanks! :)

**Comment by Veykril** [comment]
Forgot about this, should be good to merge :)

**Comment by futile** [comment]
Awesome, thank you! 🚀
