### PR TITLE
Fix some mir related bugs

### LINKED ISSUE #14701: Break-outside-of-loop false positives in try block
Looks like #14503. has been happening since then and i was waiting for the fix to be published, but it looks like rust-analyzer was released with the fix and my issue persists.

in this function, which notably has a try-block, containing a closure that returns a Result, and within the closure uses the `?` syntax:

```rust
fn _do_thing() {
    let r: anyhow::Result<()> = try {
        let v = vec![1, 2, 3];
        v.iter().map(|i| {
            let result = Some("hi").ok_or(anyhow::anyhow!("bad"));
            result?; // this line has error
            anyhow::Ok(i)
        }).collect::<anyhow::Result<Vec<_>>>()?;
    };
    r.unwrap();
}
```

We get a "break outside of loop" error, which is interesting because the code contains no break statements.

Screen Shot 2023-05-01 at 11 27 22 AM

Note in contrast to #14503, there is nothing async here -- instead we have a try block enabled by `#![feature(try_blocks)]`

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
happens in pre-release and release which are both `rust-analyzer version: 0.3.1498-standalone (3a27518fe 2023-04-30)`

**rustc version**: (eg. output of `rustc -V`)
`rustc 1.69.0-nightly (31f858d9a 2023-02-28)`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

### LINKED ISSUE #14704: Float constant evaluation showing incorrect values
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

* 0.3.1426-standalone (2023-03-06)
* 0.3.1498-standalone (2023-05-01)
* Several releases between those, when I did basic bisecting

**rustc version**: (eg. output of `rustc -V`)

* rustc 1.69.0 (84c898d65 2023-04-16)
* Also rustc 1.69.0-nightly (ef934d9b6 2023-02-08)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

* None

---

I normally use the rustup rust-analyzer, but I was excited to see const evaluation support in newer versions and wanted to try it out.  I did `cargo init --lib` for a blank project and added the following consts:
```rust
const ANGLE_01: f64 = 180.0;
const ANGLE_02: f64 = 180.0 - 2.0;
```

The rust-analyzer info for the plain constant ANGLE_01 is correct:

```
const ANGLE_01: f64 = 180.0
```

The (MIR?) const evaluation is incorrect for ANGLE_02, which should just be 178.0:
```
const ANGLE_02: f64 = 1.0012832363282406e-306
```

If I change it to an f32, it's similarly wrong:
```
const ANGLE_02: f32 = 5.2897246e-37
```

I'd expect these to show 178.0, or close enough for a float.  Am I misunderstanding the purpose of the const evaluation support, or am I doing something dumb?

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #14701 
fix #14704

### CODE REVIEW

File: crates/hir-ty/src/mir/eval.rs [hunk 1]
```diff
@@ -797,70 +797,122 @@ impl Evaluator<'_> {
...
+                                        BinOp::Div => l / r,
+                                        _ => unreachable!(),
+                                    };
+                                    Owned(r.to_le_bytes().into())
+                                }
+                                x => not_supported!(
+                                    "invalid binop {x:?} on floating point operators"
+                                ),
+                            }
+                        },
```
Comment (lnicola) [inline crates/hir-ty/src/mir/eval.rs:857]:
```suggestion
                        }
```

**Review by Veykril — APPROVED** [review]

File: crates/hir-ty/src/mir/eval.rs [hunk 2]
```diff
@@ -797,70 +797,122 @@ impl Evaluator<'_> {
...
+                                if k != 0 && (k != 255 || !is_signed) {
+                                    return Err(MirEvalError::Panic(format!("Overflow in {op:?}")));
+                                }
+                            }
+                            Owned(r[0..lc.len()].into())
+                        }
+                        BinOp::Shl | BinOp::Shr => {
+                            let shift_amount = if r128 < 0 {
+                                return Err(MirEvalError::Panic(format!("Overflow in {op:?}")));
+                            } else if r128 > 128 {
```
Comment (lnicola) [inline crates/hir-ty/src/mir/eval.rs:902]: Should this be `r128 >= 128`? Cf. `1 >> 32`.
