### PR TITLE
fix: f32 and f64 representation during lowering

### LINKED ISSUE #12380: Hover on floating consts shows zero if their value is positive
**rust-analyzer version**: rust-analyzer version: 81805d4cf 2022-05-24 nightly

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

If I have consts like those:

```rust
const INT_POS: i32 = 10;
const INT_NEG: i32 = -10;
const F32_POS: f32 = 10.0;
const F32_NEG: f32 = -10.0;
const F64_POS: f64 = 10.0;
const F64_NEG: f64 = -10.0;
```

Then hovering on `INT_POS`, `INT_NEG`, `F32_NEG` and `F64_NEG` shows their values as expected. E.g.:

image

However, hovering `F32_POS` and `F64_POS`, for some reason, shows zeros:

image

### PR DESCRIPTION
**Pull request by feniljain**
should fix #12380

### CODE REVIEW

File: crates/syntax/src/ast/token_ext.rs [hunk 1]
```diff
@@ -319,6 +319,32 @@ impl ast::IntNumber {
...
+    pub fn float_value(&self) -> Option<FloatTypeWrapper> {
+        let (_, text, _) = self.split_into_parts();
+        let float_value = text.parse::<f64>().ok()?;
+        Some(FloatTypeWrapper::new(float_value))
+    }
+}
+
+#[derive(Default, Debug, Clone, Eq, PartialEq)]
+pub struct FloatTypeWrapper {
+    //We convert float values into bits and that's how we don't need to deal with f32 and f64.
```
Comment (lnicola) [inline crates/syntax/src/ast/token_ext.rs:332]: Nit: missing space after `//` and I'd probably go for a tuple struct (`struct FloatEq(u64);`), but it doesn't matter too much.

Comment (feniljain) [reply crates/syntax/src/ast/token_ext.rs]: Hey, sorry for bringing it up here, tho I am not able to reach Jake ( @~jhgg ) for further review on this PR:
https://github.com/rust-lang/rust-analyzer/pull/12347

I try to press the re-request review button, but it doesn't do anything :(

Can you have a look at that PR too?

File: crates/syntax/src/ast/token_ext.rs [hunk 2]
```diff
@@ -319,6 +319,30 @@ impl ast::IntNumber {
...
+impl FloatTypeWrapper {
+    fn new(value: f64) -> Self {
+        Self(value.to_bits())
+    }
+}
+
+impl std::fmt::Display for FloatTypeWrapper {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        write!(f, "{}", f64::from_bits(self.0))
+    }
```
Comment (Veykril) [inline crates/syntax/src/ast/token_ext.rs:345]: This shouldn't go into `syntax`, let's put this where it is used by hir-def

File: crates/syntax/src/ast/token_ext.rs [hunk 3]
```diff
@@ -331,6 +355,11 @@ impl ast::FloatNumber {
         }
         Some(&text[suffix_start..])
     }
+
+    pub fn value(&self) -> Option<FloatTypeWrapper> {
+        let float_value = self.text().parse::<f64>().ok()?;
+        Some(FloatTypeWrapper::new(float_value))
+    }
```
Comment (Veykril) [inline crates/syntax/src/ast/token_ext.rs:362]: Similarly this should just return the f64

File: crates/syntax/src/ast/token_ext.rs [hunk 4]
```diff
@@ -331,6 +355,11 @@ impl ast::FloatNumber {
         }
         Some(&text[suffix_start..])
     }
+
+    pub fn value(&self) -> Option<FloatTypeWrapper> {
+        let float_value = self.text().parse::<f64>().ok()?;
```
Comment (Veykril) [inline crates/syntax/src/ast/token_ext.rs:360]: This will fail when we have things like `1.0f32`, we should probably have a `split_into_parts` akin to ast::IntNumber (minus the prefix part).

File: crates/syntax/src/ast/token_ext.rs (hunk 2 above)
Comment (feniljain) [reply crates/syntax/src/ast/token_ext.rs]: Shifted it to same file where `Literal::Float` is defined

File: crates/syntax/src/ast/token_ext.rs (hunk 3 above)
Comment (feniljain) [reply crates/syntax/src/ast/token_ext.rs]: Made changes for the same

File: crates/syntax/src/ast/token_ext.rs (hunk 4 above)
Comment (feniljain) [reply crates/syntax/src/ast/token_ext.rs]: Yeah, that's right, implemented the same too!

File: crates/ide/src/hover/tests.rs [hunk 5]
```diff
@@ -3595,6 +3595,72 @@ const FOO$0: u8 = b'\x61';
...
+    // show float literal
+    check(
+        r#"
+    /// This is a doc
+    const FOO$0: f64 = 1.0234;
+    "#,
+        expect![[r#"
+            *FOO*
+
+            ```rust
```
Comment (HKalbasi) [inline crates/ide/src/hover/tests.rs:3610]: It might be good to move these tests to `hir_ty::consteval::tests`

Comment (feniljain) [reply crates/ide/src/hover/tests.rs:3610]: So just have one float literal test here and move other cases to consteval?

Comment (HKalbasi) [reply crates/ide/src/hover/tests.rs:3610]: > So just have one float literal test here and move other cases to consteval?

Yes, that sounds good to me.

> Actually should they go in consteval this was a general problem regarding handling of floats

I think it only affects `consteval`, and current tests just test this, but if there are other problems fixed/affected by this, then adding test for those in addition to `consteval` tests is good.

**Comment by feniljain** [comment]
So, while re-reviewing the PR and understanding more from the review of @HKalbasi , I realized this does not fix `consteval` for floats compeltely, it does fix the base case of a simple float value directly assigned. Exactly what current tests show.

But for cases like `const FOO: f64 = 2.0 + 3.0`, this won't work because that part is errored out currently, you can see that here:

https://github.com/rust-lang/rust-analyzer/blob/732eb9a16799ea04331d99d4f9040d58e70edda7/crates/hir-ty/src/consteval.rs#L222-L226

Though it does fix exactly what the title mentions, so to close the issue #12380 completely I would have to add support for float in `consteval.rs` too. Now that seems to be some work, testing support for it has to be added, then there would be some significant changes in `consteval.rs`.

I was wondering should I do it in the same PR or separate one?

cc: @lnicola @Veykril @HKalbasi

**Comment by HKalbasi** [comment]
I think it is fine to not support float operations for now, since hover on `const FOO: f64 = 2.0 + 3.0` will show `Foo = 2.0 + 3.0` which is not invalid.

**Comment by feniljain** [comment]
> I think it is fine to not support float operations for now, since hover on const FOO: f64 = 2.0 + 3.0 will show Foo = 2.0 + 3.0 which is not invalid.

Then ig it makes sense to leave the current tests where they are :)

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by lnicola** [comment]
image
