### PR TITLE
fix: Use `ProofTreeVisitor` for unsized coercion

### LINKED ISSUE #21885: False positive compile error from lack of trait object coercion
With https://github.com/hickory-dns/hickory-dns/commit/a1f77f52409a5225120988e2d3518be446328f6c, I'm seeing false positive errors at

https://github.com/hickory-dns/hickory-dns/blob/main/crates/resolver/src/name_server_pool.rs#L1279

and

https://github.com/hickory-dns/hickory-dns/blob/main/crates/resolver/src/name_server_pool.rs#L1291

Image

Running `cargo check --all-features --all-targets` in `crates/resolver` does not reproduce these issues.

**rust-analyzer version**: rust-analyzer version: 0.3.2836-standalone (b42b63f390 2026-03-22) [/Users/djc/.vscode/extensions/rust-lang.rust-analyzer-0.3.2836-darwin-arm64/server/rust-analyzer]

**rustc version**: rustc 1.94.0 (4a4ef493e 2026-03-02)

**editor or extension**: 0.3.2836

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Ported rustc codes from https://github.com/rust-lang/rust/blob/22cc6747b18b3a6738e98b06676fd91f1756b33a/compiler/rustc_hir_typeck/src/coercion.rs#L657-L669

Fixes https://github.com/rust-lang/rust-analyzer/issues/21885

### CODE REVIEW

File: crates/hir-ty/src/tests/coercion.rs
Comment (ShoyuVanilla) [inline crates/hir-ty/src/tests/coercion.rs:615]: rustc succeeds the unsized coercion here, but emits fulfillment error on `impl Foo + ?Sized` is not being `Sized` 🤔 

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22096/2541da9d41db9ee96274d6f4958115ed4ca3c4c2..527788b98704273f77f8af873ef4b91304745ecd)*

File: crates/hir-ty/src/next_solver/inspect.rs [hunk 1]
```diff
@@ -473,6 +474,10 @@ pub(crate) trait ProofTreeVisitor<'db> {
     }
 
     fn visit_goal(&mut self, goal: &InspectGoal<'_, 'db>) -> Self::Result;
+
+    fn on_recursion_limit(&mut self) -> Self::Result {
```
Comment (ShoyuVanilla) [inline crates/hir-ty/src/next_solver/inspect.rs:478]: This is needed as like in https://github.com/rust-lang/rust/pull/152444

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22096/2541da9d41db9ee96274d6f4958115ed4ca3c4c2..527788b98704273f77f8af873ef4b91304745ecd)*

File: crates/hir-ty/src/tests/coercion.rs
Comment (ChayimFriedman2) [reply crates/hir-ty/src/tests/coercion.rs:615]: And we fail the coercion?

File: crates/hir-ty/src/tests/regression.rs [hunk 2]
```diff
@@ -2859,7 +2859,7 @@ fn foo<T: B>(v: T::T) {}
 }
 
 #[test]
-fn regression_() {
+fn regression_22007() {
```
Comment (ChayimFriedman2) [inline crates/hir-ty/src/tests/regression.rs:2862]: That's probably my fault 😳

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22096/2541da9d41db9ee96274d6f4958115ed4ca3c4c2..527788b98704273f77f8af873ef4b91304745ecd)*

**Review by ChayimFriedman2 — APPROVED** [review]

File: crates/hir-ty/src/tests/coercion.rs
Comment (ShoyuVanilla) [reply crates/hir-ty/src/tests/coercion.rs:615]: Currently we do, but not anymore with this PR

Comment (ShoyuVanilla) [reply crates/hir-ty/src/tests/coercion.rs:615]: I'm not sure which way would be better; keeping this with an ignored attribute or just removing this

Comment (ChayimFriedman2) [reply crates/hir-ty/src/tests/coercion.rs:615]: Following rustc is (almost) always better :)
