### PR TITLE
fix methods in pub trait generated by macro cannot be completed

### LINKED ISSUE #12483: A method inside a trait, when generated by a macro and implemented in another module, won't show in autocomplete list
**rust-analyzer version**: ad6810e90 2022-06-06 stable

**rustc version**: 1.61.0 (fe5b13d68 2022-05-18)

**relevant settings**: VSCode 1.67.2, Windows 10 x64

Mininum reproducible example:

```rust
mod other_mod {
    macro_rules! make_method {
        ($name:ident) => {
            fn $name(&self) {}
        };
    }

    pub trait MyTrait {
        make_method! { by_macro }
        fn not_by_macro(&self) {}
    }

    pub struct Foo {}

    impl MyTrait for Foo {}
}

fn main() {
    use other_mod::{Foo, MyTrait};
    let f = Foo {};
    f.by_macro(); // <-- this method won't show in autocomplete
    f.not_by_macro();
}
```

A screenshot. The `by_macro()` method is not shown:

macro_show

But if you remove the `other_mod` module, the method is actually shown in the autocomplete list:

method-shows

Note: I remember maybe 2 or 3 months ago when rust-analyzer showed everything perfectly fine, so I believe some change was made in this period that broke this functionality.

### PR DESCRIPTION
**Pull request by xuhongxu96**
Fix #12483

Check if the container is trait and inherit the visibility to associate items during collection.

### CODE REVIEW

File: crates/hir-def/src/item_tree.rs [hunk 1]
```diff
@@ -115,20 +115,36 @@ impl ItemTree {
...
             match syntax {
                 ast::SourceFile(file) => {
+                    let ctx = lower::Ctx::new(db, file_id);
                     top_attrs = Some(RawAttrs::new(db, &file, ctx.hygiene()));
                     ctx.lower_module_items(&file)
                 },
                 ast::MacroItems(items) => {
+                    // If a fn-like macro is defined in a trait, it should have the inherited visibility
+                    let trait_node = {
+                        if let Some((_, original_node)) = file_id.original_call_node(db.upcast()) {
```
Comment (Veykril) [inline crates/hir-def/src/item_tree.rs:129]: This doesn't quite work with nested macro invocations, we should use `file_id.call_node` here and take the parent before searching(since the call node could be an attributed item), and then probably loop up `ast::MacroItems` until we find an item(that is not a macro-call) and check whether that is a trait or not.

File: crates/hir-def/src/item_tree.rs [hunk 2]
```diff
@@ -115,20 +115,36 @@ impl ItemTree {
...
+                            original_node.ancestors().filter_map(|node| syntax::ast::Trait::cast(node)).next()
```
Comment (Veykril) [inline crates/hir-def/src/item_tree.rs:130]: Using ancestors as below won't properly work, as we could missclassify if we are a local item in an associated item of a trait. That is

```rs
macro_rules! call {
    () => {fn func() {}};
}
trait T {
    fn func() {
        call!()
    }
}

File: crates/hir-def/src/item_tree.rs (hunk 1 above)
Comment (flodiebold) [reply crates/hir-def/src/item_tree.rs:129]: maybe we should handle the inherited visibility during collection instead?

Comment (Veykril) [reply crates/hir-def/src/item_tree.rs:129]: It might make more sense to in collection? I am not sure how we treat visibility in these parts of the code base

Comment (xuhongxu96) [reply crates/hir-def/src/item_tree.rs:129]: Handling it in collection is intuitive. But how could we pass the inherited visibility to the `MacroFile` so that we can use it when lowering the `MacroFile`?

Comment (Veykril) [reply crates/hir-def/src/item_tree.rs:129]: Okay so the relevant code you should need to touch for this is here https://github.com/rust-lang/rust-analyzer/blob/master/crates/hir-def/src/data.rs#L460-L531

When collecting for a trait we just have to re-use the traits visibility there instead then. How to handle macros should be apparent from there as well I believe since that code also has to handle macros and attribute already.

Comment (xuhongxu96) [reply crates/hir-def/src/item_tree.rs:130]: Thanks for the tips! Actually, I've noticed that the trait visibility is available there. I'm just wondering how to make it available when lowering the `MacroFile` for the item tree.

I was thinking to add a field `inherited_visibility: RawVisibility` to the `MacroFile`, however, `RawVisibility` is not accessible from the hir-expand crate.

I also tried to add `inherited_visibility: RawVisibilityId` as a query parameter to the `file_item_tree_query` function. But I didn't figure out where to intern the `RawVisbility`. Any suggestions?

Comment (flodiebold) [reply crates/hir-def/src/item_tree.rs:130]: The idea would be that the `ItemTree` reflects what's literally written in the code, and the inherited visibility only comes into play at the collection stage, where we know that we're collecting trait methods.

Comment (xuhongxu96) [reply crates/hir-def/src/item_tree.rs:130]: Thanks for the info! This is my 1st time to contribute to this project. I'd like to learn and try if you don't mind :) I will switch this PR to draft now.

File: crates/hir-def/src/lib.rs [hunk 3]
```diff
@@ -156,19 +156,24 @@ impl<N: ItemTreeNode> Hash for ItemLoc<N> {
...
+        Self { raw_visibility_id: visibility_id, tree_id }
     }
 }
 
-impl<N: ItemTreeNode> Copy for AssocItemLoc<N> {}
+#[derive(Debug, Clone, Copy)]
+pub struct AssocItemLoc<N: ItemTreeNode> {
+    pub container: ItemContainerId,
+    pub id: ItemTreeId<N>,
+    pub inherited_visibility: Option<InheritedVisibilityLoc>,
```
Comment (flodiebold) [inline crates/hir-def/src/lib.rs:175]: sorry, but this is not the right approch. The `Loc` just contain the necessary data to identify the item in question; the visibility should not be a part of them. I should have looked into this a bit more before making vague comments, because as you found out the collector can't really change the visibility :sweat_smile: 

I think the right place to handle this is in the `fn_data_query`, `const_data_query` and `type_alias_data_query`, which currently take the visibility from the item tree and return it:
https://github.com/rust-lang/rust-analyzer/blob/65874dfff205335840cc9265ba06d74f234b719d/crates/hir-def/src/data.rs#L96
It should be possible to simply check whether the container is a trait and inherit the visibility if necessary there.

Comment (xuhongxu96) [reply crates/hir-def/src/lib.rs]: Oh yes. I just made it complex. Good to learn the design by making mistakes :)

File: crates/ide-completion/src/tests/special.rs [hunk 4]
```diff
@@ -636,3 +644,121 @@ fn bar() -> Bar {
             "#]],
     )
 }
+
+#[test]
+fn completes_fn_in_pub_trait_generated_by_macro() {
+    let mut config = TEST_CONFIG.clone();
+    config.enable_private_editable = false;
```
Comment (xuhongxu96) [inline crates/ide-completion/src/tests/special.rs:651]: Shall we make it `false` by default in tests?
I've tried locally and there will be failures in only 1 test case `test_visibility_filtering`. Maybe we can enable private editable for this test case?

```rust
        check(
            r#"
//- /lib.rs crate:lib new_source_root:local
pub mod m {
    pub struct A {
        private_field: u32,
        pub pub_field: u32,
        pub(crate) crate_field: u32,
        pub(super) super_field: u32,
    }
}
//- /main.rs crate:main deps:lib new_source_root:local
fn foo(a: lib::m::A) { a.$0 }
"#,
            expect![[r#"
                fd crate_field   u32
                fd private_field u32
                fd pub_field     u32
                fd super_field   u32
            "#]],
        );
```

Comment (Veykril) [reply crates/ide-completion/src/tests/special.rs:651]: No, I think our default test config should probably be as close to the default config we give users as possible.

Testing this feature specifically seems fine to me here, though making the changed config struct a new local const item here might be nice (or adding a `check_with_private_editable` function), either works.

**Review by Veykril — APPROVED** [review]
Looks good to me, this simplifies things a fair bit which is very nice!
Thanks!

**Comment by Veykril** [comment]
right,
@bors delegate+

File: crates/ide-completion/src/tests/special.rs (hunk 4 above)
Comment (xuhongxu96) [reply crates/ide-completion/src/tests/special.rs:651]: Hi @Veykril , what do you think about this question :)

Comment (xuhongxu96) [reply crates/ide-completion/src/tests/special.rs:651]: I think the default config we give to users is `enable_private_editable == false`?

Comment (xuhongxu96) [reply crates/ide-completion/src/tests/special.rs:651]: Related change: https://github.com/rust-lang/rust-analyzer/commit/2a7793d912bafef2d97c0e899262b94efe977543

Comment (xuhongxu96) [reply crates/ide-completion/src/tests/special.rs:651]: Sure, will do it tomorrow before merging this pr.
(Sorry for the delayed reply...Seems the GitHub pr is not realtime)

Comment (Veykril) [reply crates/ide-completion/src/tests/special.rs:651]: No problem :)

Comment (xuhongxu96) [reply crates/ide-completion/src/tests/special.rs]: Hi @Veykril, I've made the change. I'd like you to review it again in case I made something wrong :) 
Thanks!

**Comment by Veykril** [comment]
Thanks!
@bors r+
