### PR TITLE
fix: Don't add braces to 'if' completion in match guard position

### LINKED ISSUE #12823: `if` completion snippet inserts braces in guards
Accepting the `if` completion snippet in the following snippet will add a braced block
```rs
match () {
    () $0
}
```
becomes
```rs
match () {
    () if {
        $0
    }
}
```
We shouldn't emit the braces here

### PR DESCRIPTION
**Pull request by DorianListens**
fixes #12823

Is this what you were thinking of here, @Veykril ? I haven't done any work on completions before, so I could definitely be misunderstanding the issue.

### CODE REVIEW

**Comment by Veykril** [comment]
This doesn't quite work, this should only trigger inbetween the pattern and `=>` token of a match arm, the way its written right now makes this also apply to the expression of the match arm.

File: crates/ide-completion/src/completions/keyword.rs [hunk 1]
```diff
@@ -163,4 +163,75 @@ fn main() {
...
+    }
+}
+",
+            r"
+fn main() {
+    match () {
+        () => if $1 {
+    $0
+}
+    }
```
Comment (DorianListens) [inline crates/ide-completion/src/completions/keyword.rs:205]: The indentation here looks wrong, but this test passes.
When I use the assist for this example, the indentation appears correct in vscode. Any idea what's up here?

File: crates/ide-completion/src/context/analysis.rs [hunk 2]
```diff
@@ -763,6 +763,13 @@ impl<'a> CompletionContext<'a> {
                 .map_or(false, |it| it.semicolon_token().is_none());
             let impl_ = fetch_immediate_impl(sema, original_file, expr.syntax());
 
+            let in_match_guard = it.parent().and_then(ast::MatchArm::cast).is_some()
+                && it
+                    .siblings_with_tokens(Direction::Prev)
+                    .filter(|it| it.kind() == T![=>])
+                    .next()
+                    .is_none();
+
```
Comment (Veykril) [inline crates/ide-completion/src/context/analysis.rs:772]: This works, but feels a bit wrong to me. Instead of discarding the cast result we can use it to query the `=>` token via `.fat_arrow_token()` and then look at the text ranges instead. That feels more correct to me as we don't "arbitrarily" sift through the tokens ourselves.

<details>
  <summary>Something like the following (spoilered in case you wanna tackle what I mean yourself instead)</summary>
```rs
match it.parent().and_tehn(ast::MatchArm::cast) {
  Some(arm) => arm.fat_arrow_token().map_or(true, |it| name_ref.text_range().start() < it.text_range().start())
  None = false,
}
```
  
</details>

File: crates/ide-completion/src/completions/keyword.rs (hunk 1 above)
Comment (Veykril) [reply crates/ide-completion/src/completions/keyword.rs:205]: Might be VSCode fixing things up, don't pay formatting any mind in assists and completions. We can't do much about that until we ship our own builtin formatter

File: crates/ide-completion/src/context/analysis.rs (hunk 2 above)
Comment (DorianListens) [reply crates/ide-completion/src/context/analysis.rs]: Okay, that makes sense. I'm definitely still developing my sense of what "feels right", thanks for the suggestions!

Comment (Veykril) [reply crates/ide-completion/src/context/analysis.rs]: It takes time to get to know the APIs in r-a and what is the right tool for the right job that's for sure :)
