### PR TITLE
fix: Fix IDE resolution of `use` inside a body

### LINKED ISSUE #18286: `use` imports of modules defined in bodies (e.g. in functions) are assigned unresolved symbols semantic token types
**rust-analyzer version**: `rust-analyzer version: 0.3.2137-standalone`
**rustc version**: `rustc 1.81.0 (eeb90cda1 2024-09-04)`
**editor or extension**:  VSCode v0.3.2137

Example:

What's perplexing is that the `use` statement does work though, the imported symbol is resolved when referenced in the same scope.

**code snippet to reproduce**: 
```rust
fn main() {
    mod nice_module {
        pub(super) struct NiceStruct;
    }

    use nice_module::NiceStruct;

    let _ = NiceStruct;
}
```

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
We stopped the expression search too early because `use` is an item.

I thought it'll be complicated, but it turned out to be easy.

Fixes #18286.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

File: crates/hir/src/source_analyzer.rs [hunk 1]
```diff
@@ -1252,7 +1252,11 @@ fn scope_for(
     node: InFile<&SyntaxNode>,
 ) -> Option<ScopeId> {
     node.ancestors_with_macros(db.upcast())
-        .take_while(|it| !ast::Item::can_cast(it.kind()) || ast::MacroCall::can_cast(it.kind()))
+        .take_while(|it| {
+            !ast::Item::can_cast(it.kind())
+                || ast::MacroCall::can_cast(it.kind())
+                || ast::Use::can_cast(it.kind())
```
Comment (Veykril) [inline crates/hir/src/source_analyzer.rs:1258]: Then we probably also want to add `ExternCrate` to this? (I think that's all items that cannot have scopes)
