### PR TITLE
fix: calculate correct postion for Dos line ending in mapping rustc range to ls…

### LINKED ISSUE #12293: Wrong error and warning underline positions on Windows
**rust-analyzer version**: ce9b174f8 2022-05-17 nightly

**rustc version**: 1.60.0 (7737e0b5c 2022-04-04)

I got wrong warning and error underline positions with CRLF line ending source files on Windows:

image

If I change file line ending to LF, then the underlines are shown at their correct positions:

image

### PR DESCRIPTION
**Pull request by harpsword**
fix #12293

### CODE REVIEW

File: crates/rust-analyzer/src/diagnostics/to_proto.rs [hunk 1]
```diff
@@ -87,8 +87,18 @@ fn range(
 ) -> Result<lsp_types::Range> {
     let file_id = from_proto::file_id(snap, &uri)?;
     let line_index = snap.file_line_index(file_id)?;
-    let range =
-        to_proto::range(&line_index, TextRange::new(span.byte_start.into(), span.byte_end.into()));
+    let (start, end) = match line_index.endings {
+        line_index::LineEndings::Unix => (span.byte_start, span.byte_end),
+        line_index::LineEndings::Dos => {
+            let start_crlf_count = (span.line_start as u32).saturating_sub(1);
+            let end_crlf_count = (span.line_end as u32).saturating_sub(1);
```
Comment (jonas-schievink) [inline crates/rust-analyzer/src/diagnostics/to_proto.rs:94]: I think this logic is only correct if *every* line uses CRLF, but they might be mixed too

Comment (harpsword) [reply crates/rust-analyzer/src/diagnostics/to_proto.rs]: i cannot find a good way to get the number of CRLF. maybe we can use the default solution which donot need to calculate the number of CRLF but need more calculation.
