### PR TITLE
fix: escape receiver texts in completion

### LINKED ISSUE #11897: Using postfix snippets on expressions containing `'\\'` results in it getting unescaped
**rust-analyzer version**: 2022-03-28

**rustc version**: rustc 1.61.0-nightly (c5cf08d37 2022-03-30)

Example:
```rs
fn main() {
  let x = '\\'.ok|
}
```
(where `|` is the cursor)
Accepting the suggestion will result in this code:
```rs
fn main() {
  let x = Ok('\')|
}
```
which is invalid syntax.

It also seems that this happens with strings. Other escapes are intact, it's only `\\` that gets mangled.

Also of note is that the escape may be nested in some deeper expression. For instance:
```rs
match x {
  true => '\\',
  false => 'a',
}.ok|
```

### PR DESCRIPTION
**Pull request by lowr**
This PR fixes #11897 by escaping '\\' and '$' in the text of the receiver position expression. See [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) for the specification of the snippet syntax (especially [this section](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#grammar) discusses escaping).

Although not all occurrences of '\\' and '$' have to be replaced, I chose to replace all as that's simpler and easier to understand. There *are* more clever ways to implement it, but I thought they were premature optimization for the time being (maybe I should put FIXME notes?).

### CODE REVIEW

File: crates/ide-completion/src/completions/postfix.rs [hunk 1]
```diff
@@ -516,6 +526,44 @@ fn main() { 42.$0 }
...
+            r#"
+//- minicore: try
+fn main() { '\\'.$0 }
+"#,
+            r#"
+use core::ops::ControlFlow;
+
+fn main() { ControlFlow::Break('\\\\') }
+"#,
+        );
```
Comment (Veykril) [inline crates/ide-completion/src/completions/postfix.rs:544]: These outputs don't seem right to me, we effectively changed the string after the completion, simple escaping doesn't seem to work here. I'm not sure how we can solve this here though.

Comment (lowr) [reply crates/ide-completion/src/completions/postfix.rs:544]: Hmm, not sure if I'm following. I'm only escaping the text in the receiver position expression, which the user himself wrote and is expected to be rendered verbatim. Could I have an example where this doesn't work?

Comment (lowr) [reply crates/ide-completion/src/completions/postfix.rs:544]: Ah I think I got what you're saying. Yes, I'm turning `'\\'` into `'\\\\'` and sending it to the lsp client, which *then* unescapes every occurrence of `\\` to `\`. If we send `'\\'` without the escaping, the lsp client would interpret it as `'\'`, and that's what the original issue is about.

I understand the test fixture is confusing. Is there anything I can do to mitigate that?

**Comment by Veykril** [comment]
Thanks!
@bors delegate+

File: crates/ide-completion/src/completions/postfix.rs (hunk 1 above)
Comment (Veykril) [reply crates/ide-completion/src/completions/postfix.rs:544]: It might be good to add that to the code comment though for clarity.

File: crates/ide-completion/src/completions/postfix.rs [hunk 2]
```diff
@@ -193,13 +193,21 @@ pub(crate) fn complete_postfix(
...
-    }
+    };
+
+    // The receiver texts should be interpreted as-is, as they are expected to be
+    // normal Rust expressions. We escape '\' and '$' so they don't get treated as
+    // snippet-specific constructs.
+    //
+    // Note that we don't need to escape the other characters that can be escaped,
+    // because they wouldn't be treated as snippet-specific constructs without '$'.
+    text.replace('\\', "\\\\").replace('$', "\\$")
```
[the remark this answers is not in the document]
Comment (lowr) [reply crates/ide-completion/src/completions/postfix.rs:210]: We only need to escape `}` inside the snippet-specific construct, i.e. `${}`, to disambiguate it from the ending token of the syntax. Now that we escape every occurrence of `$` with this patch, we wouldn't have `${}` in the first place so I believe there's no need (I've built r-a and tested the behavior, and it worked as expected at least in my local environment).

I think this was my reasoning when writing this patch, but let me know if I'm missing anything!
