### PR TITLE
Fix const generic panic in dyn trait

### LINKED ISSUE #12048: Request textDocument/documentHighlight failed.
This minimal example leads to a panic within rust-analyzer in VSCode (1.66.02). The issue might be related to https://github.com/rust-lang/rust-analyzer/issues/12004, but happens on stable rust and stable analyzer.

```rust
use std::sync::Arc;

trait Bar<const CHANNELS: u8> {
    fn baz(self: Arc<Self>) -> Arc<dyn Bar<CHANNELS>>;
}

struct Foo;

impl<const CHANNELS: u8> Bar<CHANNELS> for Foo {
    fn baz(self: Arc<Self>) -> Arc<dyn Bar<CHANNELS>> {
        unimplemented!()
    }
}
```

Leads to the Output:
```
Panic context:
> 
version: 65fbe0a8d 2022-04-18 stable
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/work/rust_analyzer_bug/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 13,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'mismatched kinds in substitution', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\chalk-ir-0.82.0\src\fold\subst.rs:109:22
stack backtrace:
   0: std::panicking::begin_panic
   1: <chalk_ir::fold::subst::Subst<I> as chalk_ir::fold::Folder<I>>::fold_free_var_const
   2: <chalk_ir::Const<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
   3: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
   4: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   5: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
   6: chalk_ir::fold::binder_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Binders<T>>::fold_with
   7: chalk_ir::fold::in_place::fallible_map_vec
   8: chalk_ir::Binders<T>::substitute
   9: chalk_solve::clauses::super_traits::push_trait_super_clauses
  10: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
  11: chalk_solve::clauses::dyn_ty::build_dyn_self_ty_clauses
  12: chalk_ir::fold::Folder::fold_inference_const
  13: chalk_recursive::solve::SolveIteration::solve_iteration
  14: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  15: chalk_recursive::fulfill::Fulfill<I,Solver>::push_goal
  16: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  17: chalk_ir::fold::Folder::fold_inference_const
  18: chalk_recursive::solve::SolveIteration::solve_iteration
  19: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  20: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  21: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  22: salsa::runtime::Runtime::execute_query_implementation
  23: salsa::derived::slot::Slot<Q,MP>::read
  24: salsa::derived::slot::Slot<Q,MP>::read
  25: salsa::QueryTable<Q>::get
  26: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  27: hir_ty::db::trait_solve_wait
  28: <DB as hir_ty::db::HirDatabase>::trait_solve
  29: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce_inner
  30: hir_ty::infer::coerce::<impl hir_ty::infer::unify::InferenceTable>::coerce
  31: hir_ty::infer::coerce::<impl hir_ty::infer::InferenceContext>::coerce
  32: core::ptr::drop_in_place<core::cell::RefCell<core::option::Option<hir_def::body::Expander>>>
  33: hir_ty::infer::infer_query
  34: salsa::runtime::Runtime::execute_query_implementation
  35: salsa::derived::slot::Slot<Q,MP>::read
  36: salsa::derived::slot::Slot<Q,MP>::read
  37: salsa::QueryTable<Q>::get
  38: <DB as hir_ty::db::HirDatabase>::infer_query
  39: hir_ty::db::infer_wait
  40: hir::DefWithBody::diagnostics
  41: hir::Module::diagnostics
  42: ide_diagnostics::diagnostics
  43: std::panicking::try
  44: rust_analyzer::handlers::handle_code_action
  45: std::panicking::try
  46: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**rust-analyzer version**: v0.2.1022 as well as v0.3.1017

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #12048

### CODE REVIEW

File: crates/hir_ty/src/lower.rs [hunk 1]
```diff
@@ -712,34 +720,37 @@ impl<'a> TyLoweringContext<'a> {
...
+                                self.type_param_mode,
+                                || self.generics(),
+                                self.in_binders,
+                            )
+                        },
+                    ) {
+                        had_explicit_args = true;
+                        substs.push(x);
+                    } else {
+                        never!();
```
Comment (flodiebold) [inline crates/hir_ty/src/lower.rs:752]: can you add a comment/error message here to explain why this should never happen?

**Review by flodiebold — APPROVED** [review]
bors d+
