### PR TITLE
feat: Implement TAIT and fix ATPIT a bit

### LINKED ISSUE #16296: Failure to Infer Complicated Types
**rust-analyzer version**: 0.4.1797-standalone (f595e60b6 2024-01-06)

`DATABASE_POOL` declaration:
```rs
pub type PostgresPool = Pool<PostgresConnectionManager<NoTls>>;
pub type DatabasePoolFuture = impl Future<Output = PostgresPool>;
pub static DATABASE_POOL: AsyncLazy<PostgresPool, DatabasePoolFuture> = AsyncLazy::new(async {
    let hartex_pgsql_url = env::var("HARTEX_NIGHTLY_PGSQL_URL").unwrap();

    let manager = PostgresConnectionManager::new_from_stringlike(hartex_pgsql_url, NoTls).unwrap();

    Pool::builder().build(manager).await.unwrap()
});
```

Rust Analyzer behaviour:
image

RustRover behaviour:
image

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Closes #16296 (Commented on the issue)

In #16852, I implemented ATPIT, but as I didn't discern ATPIT and other non-assoc TAIT, I guess that it has been working for some TAITs.

As the definining usage of TAIT requires it should be appear in the Def body's type(const blocks' type annotations or functions' signatures), this can be done in simlilar way with ATPIT

And this PR also corrects some defining-usage resolution for ATPIT

### CODE REVIEW

File: crates/hir-ty/src/lib.rs [hunk 1]
```diff
@@ -595,7 +595,7 @@ impl TypeFoldable<Interner> for CallableSig {
 #[derive(Copy, Clone, PartialEq, Eq, Debug, Hash)]
 pub enum ImplTraitId {
     ReturnTypeImplTrait(hir_def::FunctionId, ImplTraitIdx),
-    AssociatedTypeImplTrait(hir_def::TypeAliasId, ImplTraitIdx),
+    TypeAliasImplTrait(hir_def::TypeAliasId, ImplTraitIdx),
```
Comment (ShoyuVanilla) [inline crates/hir-ty/src/lib.rs:598]: Though previously named as `AssociatedTypeImplTrait`, actually it also contains TAITs 😅

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
