### PR TITLE
fix(ide-assists): unwrap block when it parent is let stmt

### LINKED ISSUE #13990: Unwrap block does not work correctly with `let` stmt parents
#13726 was supposed to make unwrap block assist work when the parent of the block is a `let` statement, but it actually only works with blocks with a single expression. Blocks with statement are transformed incorrectly:

Input:
```rust
let _ = { 1; 2 };
```
Output:
```rust
let _ = 1; 2;
```
Expected result:
```rust
1; 
let _ = 2;
```

**rust-analyzer version**: 0.0.0 (b3d7c78cd 2023-01-16)

<sub>as a side note, I've tried fixing it, but couldn't find a way of getting the text representation of all statements and all adjacent trivia, everything that has come to my mind is broken in one way or another.</sub>

### PR DESCRIPTION
**Pull request by bvanjoi**
fix #13990

### CODE REVIEW

File: crates/ide-assists/src/handlers/unwrap_block.rs [hunk 1]
```diff
@@ -734,13 +776,41 @@ fn main() {
...
+fn main() -> i32 {
+    1;
+    let mut a = 2;
+}
 "#,
         );
     }
 
     #[test]
+    // https://github.com/rust-lang/rust-analyzer/issues/13679
```
Comment (jonas-schievink) [inline crates/ide-assists/src/handlers/unwrap_block.rs:812]: Please keep these inside the function to match how we do it in the rest of the code base
