### PR TITLE
fix: Correct span info for mir::Operand

### LINKED ISSUE #19172: cannot move out of reference error has bad span
```rs

struct NotCopy;
struct S {
    field: NotCopy,
}

fn f(s: &S) -> S {
    S { field: s.field }
}

```
the diagnostic here highlights the entire struct constructor `S { field: s.field }` which makes it difficult to tell what the cause is in more complicated constructions.

### PR DESCRIPTION
**Pull request by alibektas**
Fixes #19172

### CODE REVIEW

**Comment by alibektas** [comment]
Right now the question is whether I should go the extra mile and make `Operand`s `span` file of type `MirSpan` and not `Option<MirSpan>` ?

File: crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs [hunk 1]
```diff
@@ -18,7 +18,22 @@ pub(crate) fn moved_out_of_ref(ctx: &DiagnosticsContext<'_>, d: &hir::MovedOutOf
 mod tests {
     use crate::tests::check_diagnostics;
 
-    // FIXME: spans are broken
+    #[test]
+    fn abc() {
```
Comment (ChayimFriedman2) [inline crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs:22]: That... doesn't seem like the most descriptive name.

**Review by ChayimFriedman2 — CHANGES_REQUESTED** [review]

**Comment by ChayimFriedman2** [comment]
I think it'd be better if we wouldn't make this optional when there is no reason.

File: crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs (hunk 1 above)
Comment (alibektas) [reply crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs:22]: sorry about that 😂

Comment (ChayimFriedman2) [reply crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs:22]: Don't worry, it happens to me too that I put a test before the changes and don't bother to make its name meaningful, I understand you can forget to do that after :)

**Comment by alibektas** [comment]
I have spent  some time trying to understand how to get `MirSpan`s from `Place`s so that I can make the field of `Operand`s be of type `MirSpan` and not `Option<MirSpan>`, but it requires bigger changes. I will try to resolve this in a future PR.

**Review by Veykril — APPROVED** [review]

**Comment by lnicola** [comment]
This (understandably) caused a 30 MB memory increase on `anaysis-stats self`.

**Comment by ChayimFriedman2** [comment]
> This (understandably) caused a 30 MB memory increase on `anaysis-stats self`.

Maybe we should just LRU mir queries?
