### PR TITLE
fix: Do not compute `prettify_macro_expansion()` unless the "Inline macro" assist has actually been invoked

### LINKED ISSUE #18879: rust-analzyer progressively gets slower when repeatedly navigating to (large) `include!`ed files in VSCode
**rust-analyzer version**: 0.3.2253-standalone (cd12ef8547 2025-01-07)

**rustc version**: 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: VSCode, extension verson 0.3.2253

**relevant settings**: Likely irrelevant, but `CARGO_HOME=D:\.cargo`

**repository link (if public, optional)**: https://github.com/PrototypeNM1/include_nav_degrade_performance

**code snippet to reproduce**: 
Repeatedly ctrl+click the include path and navigate back until performance degrades.

A parallel symptom is that the rust-analyzer process will exhaust a CPU core while hanging.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
And not just called to be listed.

This was a major performance hang when repeatedly switching back-and-forth between a large `include!`d file, aka. #18879 (but there are others). This does not fix this issue because, well, it was a major hurdle hiding everything else in the profiler, but now that it's fixed other things show up (and it's still slow).

To categorize the main reasons remained, as analyzed by my profiler:

We have a lot of diagnostics, influenced mainly by two salsa queries, `body_with_source_map()` and `borrowck()`. These two are lru'ed so they of course evict with such large files with lots of small bodies. If I didn't let the file to analyze well before starting my back-and-forth, we also have a lot of calls to `infer()`, half of them are blocking on the other. This is also expected since we cancel them when we switch out of the file, so they never complete and cached, only consume CPU.

There is an important observation here, though: diagnostics are called twice. Once for assists and the other for, well, diagnostics. Since some diagnostics are not fully cached in the db this may cause actual slowdown for real users. We probably want to fix this, perhaps by measure of caching the diagnostics of the last file.

There is also a fair share of semantic highlighting, which is also fair, given that a lot of its work doesn't (and couldn't) be cached in the db. Another large part is assist, that tend to execute a lot of code when listing them, for deciding whether they are available or not. Perhaps we could improve on this metric too.

Overall, I'm tending to close (oh no GitHub, don't close it!) #18879 as "won't fix" given this is a very atypical scenario. But perhaps there are still a few points we can improve in, guided by the information from this issue.

### CODE REVIEW

**Comment by Veykril** [comment]
> We probably want to fix this, perhaps by measure of caching the diagnostics of the last file.

👍 we should introduce a bit of caching for diagnostics *somewhere* at some point

>  Another large part is assist, that tend to execute a lot of code when listing them, for deciding whether they are available or not. Perhaps we could improve on this metric too.

Also 👍 a lot of assists do the same upfront work that could likely be shared in some capacity.

File: crates/ide-assists/src/handlers/inline_macro.rs [hunk 1]
```diff
@@ -40,19 +40,19 @@ pub(crate) fn inline_macro(acc: &mut Assists, ctx: &AssistContext<'_>) -> Option
     let macro_call = ctx.sema.to_def(&unexpanded)?;
     let expanded = ctx.sema.parse_or_expand(macro_call.as_file());
     let span_map = ctx.sema.db.expansion_span_map(macro_call.as_macro_file());
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/inline_macro.rs:42]: We can also pull these two in

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
> Overall, I'm tending to close (oh no GitHub, don't close it!) https://github.com/rust-lang/rust-analyzer/issues/18879 as "won't fix" given this is a very atypical scenario. But perhaps there are still a few points we can improve in, guided by the information from this issue.

Let's close that and open an issue with the points you raised here as a replacement (could also link back to that issue there)

**Comment by Veykril** [comment]
Merging this and kicking off another nightly as running into this is quite bad

**Comment by lnicola** [comment]
@Veykril I can push a commit to move down the other two calls.

**Comment by Veykril** [comment]
I'll include that in my next PR

**Comment by ChayimFriedman2** [comment]
New issues: #18997 and #18996.
