### PR TITLE
fix: Insert spaces when inlining a function defined in a macro.

### LINKED ISSUE #12860: Inlining function defined in macro produces incorrect results (concatenated tokens).
Rust-analyzer's "Inline \<function\>" code action fails[^a] when the function to be inlined is defined in a macro.

[^a]: It succeeds but does not produce correct code if any sequential tokens need to be separated by spaces.

```rs
macro_rules! define_function {
    () => {
        fn test_macro(x: bool) {
            if x { println!("x is true!"); }
        }
    };
}
define_function!();
fn test_free(x: bool) {
    if x { println!("x is true!"); }
}
fn main() {
    test_macro(true);
    test_free(true);
}
```

Result when selecting `test_macro(true)` and running the "Inline \`test_macro\`" action: (at least `if` and `x` should be separated)
```rs
// ...
fn main() {
    {
        let x = true; ifx{println!("x is true!");}};
    test_free(true);
}
```

Result when selecting `test_free(true)` and running the "Inline \`test_free\`" action: (to show that the issue only happens for functions defined in macros)
```rs
// ...
fn main() {
    test_macro(true);
    if true { println!("x is true!"); };
}
```

The problem also occurs in associated functions/methods. I originally ran into this error when trying to inline `usize::next_multiple_of`, which is defined in a macro.

---

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 0.4.1138-standalone (977e12a0b 2022-07-23)
("Pre-Release" version on VSCode)
(Also happens on normal version on VSCode, rust-analyzer version: 0.3.1131-standalone (897a7ec4b 2022-07-17))

**rustc version**: (eg. output of `rustc -V`)
rustc 1.62.1 (e092d0b6b 2022-07-16)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
None that I am aware are relevant.

### PR DESCRIPTION
**Pull request by zachs18**
(partially) fixes #12860.

This PR (only) addresses the whitespace issue when inlining functions defined in macros.

Additionally, the indentation/spacing is not ideal, but works, e.g.
```rs
macro_rules! define_function {
    () => { fn test_function_macro() {
        if let Some(3) = 3i32.checked_add(0) {
            println!("3 + 0 == 3");
        }
    } };
}
define_function!();
fn main() {
    test_function_macro();
}
// previously became
// ...
fn main() {
    ifletSome(3)=3i32.checked_add(0){println!("3 + 0 == 3");};
}
// now becomes
// ...
fn main() {
    if let Some(3) = 3i32.checked_add(0){
        println!("3 + 0 == 3");
        
      };
}
```

The `self` -> `this` problem[^this] is (probably?) a separate problem that I am also looking into.

[^this]: As mentioned in [my comment on the above issue](https://github.com/rust-lang/rust-analyzer/issues/12860#issuecomment-1193231766), inlining a method defined in a macro does not properly replace `self` with the new local `this`.

### CODE REVIEW

File: crates/ide-assists/src/handlers/inline_call.rs [hunk 1]
```diff
@@ -301,7 +301,18 @@ fn inline(
...
-    let body = fn_body.clone_for_update();
+    let body = if sema.hir_file_for(fn_body.syntax()).is_macro() {
+        cov_mark::hit!(inline_call_defined_in_macro);
+        if let Some(body) = ast::BlockExpr::cast(insert_ws_into(fn_body.syntax().clone())) {
+            body
+        } else {
+            // FIXME(zachs18): I believe this should be unreachable,
+            // since insert_ws_into shouldn't change the kind of the SyntaxNode.
+            fn_body.clone_for_update()
+        }
```
Comment (zachs18) [inline crates/ide-assists/src/handlers/inline_call.rs:312]:
```suggestion
        ast::BlockExpr::cast(insert_ws_into(fn_body.syntax().clone()))?
```

Is the `else` block truly unreachable? I.e. will `insert_ws_into` never change the `kind` of the `SyntaxNode`?

Comment (zachs18) [reply crates/ide-assists/src/handlers/inline_call.rs:312]: The suggestion is wrong, since `inline` returns an `ast::Expr`, not an `Option<ast::Expr>`, but my question still stands.

Comment (Veykril) [reply crates/ide-assists/src/handlers/inline_call.rs:312]: `insert_ws_into` should not change the syntax node kind yes, otherwise that is a bug. It's fine to have this unreachable fallback though, assuming there is a bug in `insert_ws_into` it'd be nice to not bring down assists with a panic

**Comment by Veykril** [comment]
Thanks! I think the FIXME comment can just go
@bors delegate+

**Comment by zachs18** [comment]
Okay, I removed the FIXME comment. Thanks!
@bors r+
