### PR TITLE
Order auto-imports by relevance

### LINKED ISSUE #10337: sort items in auto-import by relevance
image

This is sorted in exactly the wrong order :)

### PR DESCRIPTION
**Pull request by nolanderc**
Fixes #10337.

Basically we sort the imports according to how "far away" the imported item is from where we want to import it to. This change makes it so that imports from the current crate are sorted before any third-party crates. Additionally, we make an exception for builtin crates (`std`, `core`, etc.) so that they are sorted before any third-party crates.

There are probably other heuristics that should be added to improve the experience (such as preferring imports that are common elsewhere in the same crate, and ranking crates depending on the dependency graph). However, I think this is a first good step. 

PS. This is my first time contributing here, so please be gentle if I have missed something obvious :-)

### CODE REVIEW

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 1]
```diff
@@ -158,11 +165,142 @@ fn group_label(import_candidate: &ImportCandidate) -> GroupLabel {
...
+        if module.krate().is_builtin(db) {
+            // prefer items builtin to the language
+            score += 5;
+        }
+    }
+
+    match item_module.zip(current_node) {
+        // get the distance between the modules (prefer items that are more local)
+        Some((item_module, current_node)) => {
+            let current_module = ctx.sema.scope(&current_node).unwrap().module();
```
Comment (lnicola) [inline crates/ide-assists/src/handlers/auto_import.rs:195]: Drive-by nit: I don't know if `ctx.sema.scope(&current_node)` can be missing here, but we've had `unwrap`s fail before and here it seems possible to avoid it.

Comment (nolanderc) [reply crates/ide-assists/src/handlers/auto_import.rs:195]: Right, I was too focused to get things working I forgot to fix every unwrap.

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 2]
```diff
@@ -158,11 +165,144 @@ fn group_label(import_candidate: &ImportCandidate) -> GroupLabel {
...
+    };
+
+    if let Some(module) = item_module.as_ref() {
+        if module.krate().is_builtin(db) {
+            // prefer items builtin to the language
+            score += 5;
+        }
+    }
+
+    let current_scope = current_node.as_ref().and_then(|node| ctx.sema.scope(node));
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/auto_import.rs:192]: Calculating this should be done outside this function as it is not relient on the function input (and we do call this function for each item when sorting)

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 3]
```diff
@@ -158,11 +165,144 @@ fn group_label(import_candidate: &ImportCandidate) -> GroupLabel {
...
+
+    match item_module.zip(current_scope) {
+        // get the distance between the modules (prefer items that are more local)
+        Some((item_module, current_scope)) => {
+            let current_module = current_scope.module();
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/auto_import.rs:197]: This as well

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 4]
```diff
@@ -158,11 +165,144 @@ fn group_label(import_candidate: &ImportCandidate) -> GroupLabel {
...
+
+        // could not find relevant modules, so just use the length of the path as an estimate
+        None => return -(2 * import.import_path.len() as i32),
+    }
+
+    score
+}
+
+/// A heuristic that gives a higher score to modules that are more separated.
+fn module_distance_hueristic(current: &Module, item: &Module, db: &dyn HirDatabase) -> usize {
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/auto_import.rs:209]: Nit: We like to put the database and semantics arguments first

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 5]
```diff
@@ -158,11 +165,144 @@ fn group_label(import_candidate: &ImportCandidate) -> GroupLabel {
...
+    item_path.reverse();
+
+    let mut i = 0;
+    while i < current_path.len() && i < item_path.len() {
+        if current_path[i] == item_path[i] {
+            i += 1
+        } else {
+            break;
+        }
+    }
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/auto_import.rs:223]: This can be done with iterators, the following should be equivalent I believe
```rs
current_path.iter().zip(&item_path).position(|(a, b)| a != b).unwrap_or(0)
```

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 6]
```diff
@@ -158,11 +165,144 @@ fn group_label(import_candidate: &ImportCandidate) -> GroupLabel {
...
+    fn prefer_shorter_paths() {
+        let before = r"
+            //- /main.rs crate:main deps:foo,bar
+            HashMap$0::new();
+
+            //- /lib.rs crate:foo
+            pub mod collections { pub struct HashMap; }
+
+            //- /lib.rs crate:bar
+            pub mod collections { pub mod hash_map { pub struct HashMap; } }
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/auto_import.rs:276]: Nit (same for the other test):
```suggestion
        let before = r"
//- /main.rs crate:main deps:foo,bar
HashMap$0::new();

//- /lib.rs crate:foo
pub mod collections { pub struct HashMap; }

//- /lib.rs crate:bar
pub mod collections { pub mod hash_map { pub struct HashMap; } }
```

File: crates/ide-assists/src/handlers/auto_import.rs (hunk 5 above)
Comment (nolanderc) [reply crates/ide-assists/src/handlers/auto_import.rs]: Sure, but the `unwrap_or` should be the shortest of the two paths. I did this using `take_while` instead (8e5b318d99d3d215ab0ae84b1a80e8034975002d).

**Comment by nolanderc** [comment]
@Veykril I think 8e5b318d99d3d215ab0ae84b1a80e8034975002d should resolve all the issues you raised.

File: crates/ide-assists/src/handlers/auto_import.rs (hunk 5 above)
Comment (Veykril) [reply crates/ide-assists/src/handlers/auto_import.rs]: Oh ye good catch

**Comment by Veykril** [comment]
Thanks!
@bors r+
