### PR TITLE
fix: record completion filtering

### LINKED ISSUE #12975: Wrong record completion after match
```rust
enum Enum {
    Var { field: u8 }
}

fn f(e: &Enum) {
    match e$0
}
```

Requesting completions here returns a reasonable result, but then typing a space afterwards results in incorrect `&Enum::Var {...}` and `Enum::Var {...}` completions.

Weirdly, this does not happen when typing a space while no completions are displayed. You have to request them right after the `match` and *then* type space.

### PR DESCRIPTION
**Pull request by yue4u**
close #12975

### CODE REVIEW

File: crates/ide-completion/src/render/variant.rs [hunk 1]
```diff
@@ -94,3 +94,12 @@ pub(crate) fn format_literal_label(name: &str, kind: StructKind) -> SmolStr {
         StructKind::Unit => name.into(),
     }
 }
+
+/// Format a struct, etc. literal option for lookup used in completions filtering.
+pub(crate) fn format_literal_lookup(name: &str, kind: StructKind) -> SmolStr {
```
Comment (yue4u) [inline crates/ide-completion/src/render/variant.rs:99]: `()` and `{}` are still needed as current testing infra does not allow duplicated lookup. https://github.com/rust-lang/rust-analyzer/blob/ec3586eab943d7c6c83d211f629a691fc8c14603/crates/ide-completion/src/tests.rs#L186-L190

I guess IDEs will happily accept duplicated lookup? Anyway these extra parentheses and brackets also allow completing something like `E{` so I'd prefer to keep them here.

**Comment by jonas-schievink** [comment]
Thanks!

@bors r+
