### PR TITLE
fix: Fix a bug in span map merge, and add explanations of how span maps are stored

### LINKED ISSUE #18163: Can `$crate` come from `SyntaxContextId::ROOT`? Maybe yes
My #18131 introduced an `expect()` on the assumption that `$crate` cannot come from `SyntaxContextId::ROOT` (aka., it must come from macro expansion). This is because `$crate` will never parse as a single identifier, unless it comes from a macro.

I (obviously) thought this is correct, and I still believe this *should* be correct, but I'm pretty sure I saw VSCode reports an error from this panic when I Expanded Macro Recursively and my cursor was on `derive`. Except I cannot reproduce that now, in every way that I tried. Which is... weird, I guess? What does `$crate` has to do with `derive`?

So someone (maybe me) should investigate this. Or we can just wait and see if users come to complain that r-a panics for them (this won't be Broken Window at least, since this can only come in a response to a user action).

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Because it took me hours to figure out that contrary to common sense, the offset stored is the *end* of the node, and we search by the *start*. Which is why we need a convoluted `partition_point()` instead of a simple `binary_search()`. And this was not documented at all. Which made me make mistakes with my implementation of `SpanMap::merge()`.

The other bug fixed about span map merging is correctly keeping track of the current offset in presence of multiple sibling macro invocations. Unrelated, but because of the previous issue it took me hours to debug, so I figured out I'll put them together for posterity.

Fixes #18163.

### CODE REVIEW

File: crates/span/src/map.rs [hunk 1]
```diff
@@ -13,6 +13,7 @@ use crate::{
 /// Maps absolute text ranges for the corresponding file to the relevant span data.
 #[derive(Debug, PartialEq, Eq, Clone, Hash)]
 pub struct SpanMap<S> {
+    /// The offset stored here is the *end* of the node.
```
Comment (Veykril) [inline crates/span/src/map.rs:16]: I believe my thinking was that if using the start we'd need to separately store the end of the final node/length of the file while also always having a `0` at the start. So encoding the end is slightly more optimal. Either way this should've been documented, sorry.

**Comment by Veykril** [comment]
Thanks!
@bors r+
