### PR TITLE
Fix bug of "fill match arm" action in tokio::main macro

### LINKED ISSUE #18027: Code action "fill match arms" adds extra `}` inside `#[tokio::main]`
**rust-analyzer version**: 2024-09-02

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: Neovim + nvim-lspconfig. Here's my full (minimal) config:

<details>
<summary><b>Click to expand</b></summary>

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- install plugins
require('lazy').setup({
  "folke/tokyonight.nvim",
  {
    'neovim/nvim-lspconfig',
    dependencies = {
      { 'williamboman/mason.nvim', config = true },
      'williamboman/mason-lspconfig.nvim',
      'WhoIsSethDaniel/mason-tool-installer.nvim',
    },
    config = function()
      require('mason').setup()

      local servers = {}

      require('mason-tool-installer').setup {
        ensure_installed = { 'rust-analyzer' },
      }

      require('mason-lspconfig').setup {
        handlers = {
          function(server_name)
            local server = servers[server_name] or {}
            require('lspconfig')[server_name].setup(server)
          end,
        },
      }
    end,
  },
})
```

</details>

**relevant settings**: I need to have tokio installed for the bug to appear

**repository link (if public, optional)**: ?

**code snippet to reproduce**:

```rust
#[tokio::main]
fn main() {
    match true {}
}
```

After executing the code action "Fill match arms" on `match true`:

```rust
#[tokio::main]
async fn main() {
    match true {
    true => todo!(),
    false => todo!(),
}} // <-- notice the extra `}`
}
```

If I remove `#[tokio::main]` I no longer have this issue.

Here's my `Cargo.toml`:

```toml
[package]
name = "rust-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
```

### PR DESCRIPTION
**Pull request by 1hakusai1**
close #18027 

スクリーンショット 2024-12-30 20 07 37
スクリーンショット 2024-12-30 20 07 44

### CODE REVIEW

File: crates/ide-assists/src/handlers/add_missing_match_arms.rs [hunk 1]
```diff
@@ -261,7 +261,9 @@ pub(crate) fn add_missing_match_arms(acc: &mut Assists, ctx: &AssistContext<'_>)
             }
 
             if let Some(cap) = ctx.config.snippet_cap {
-                if let Some(it) = first_new_arm.and_then(|arm| arm.syntax().descendants().find_map(ast::WildcardPat::cast)) {
+                if let Some(it) = first_new_arm
+                    .and_then(|arm| arm.syntax().descendants().find_map(ast::WildcardPat::cast))
+                {
```
Comment (1hakusai1) [inline crates/ide-assists/src/handlers/add_missing_match_arms.rs:266]: This line was formatted automatically.

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks! It is a bit odd that we apparently hit the single token case there. Our upmapping probably needs some improvement there still (or we get confused by tokio's span re-usage)

**Comment by 1hakusai1** [comment]
Thanks!

> It is a bit odd that we apparently hit the single token case there.

Yes. `SemanticsImpl::original_range_opt` and `parse_macro_expansion` may not work in some cases. (However, I could not find where the problem was.)
