### PR TITLE
fix: Properly account for editions in names

### LINKED ISSUE #17774: `Name` escaping is not edition aware
https://users.rust-lang.org/t/vscode-rust-extension-summon-wrong-command-when-test-name-is-gen/115374/3

### LINKED ISSUE #17895: rust-analyzer completes `r#gen` even before edition 2024
In edition 2024, the `gen` keyword is reserved. So rust-analyzer completes `gen` as `r#gen`.

However, it does that even when the crate edition is less than 2024, which creates a weird symbol (`r#gen`) where it is not really needed. Since edition 2024 is still unstable, this means the common case becomes worse for the non-common (yet) case.

**rust-analyzer version**: 0.3.2070-standalone (0daeb5c0b 2024-08-10)

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: VSCode

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**code snippet to reproduce**: 
```rust
fn gen() {}

fn foo() {
    gen<|>
}
```
Trigger completion and choose `gen()`. It completes as `r#gen()`.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
This PR touches a lot of parts. But the main changes are changing `hir_expand::Name` to be raw edition-dependently and only when necessary (unrelated to how the user originally wrote the identifier), and changing `is_keyword()` and `is_raw_identifier()` to be edition-aware (this was done in #17896, but the FIXMEs were fixed here).

It is possible that I missed some cases, but most IDE parts should properly escape (or not escape) identifiers now.

The rules of thumb are:

 - If we show the identifier to the user, its rawness should be determined by the edition of the edited crate. This is nice for IDE features, but really important for changes we insert to the source code.
 - For tests, I chose `Edition::CURRENT` (so we only have to (maybe) update tests when an edition becomes stable, to avoid churn).
 - For debugging tools (helper methods and logs), I used `Edition::LATEST`.

Reviewing notes:

This is a really big PR but most of it is mechanical translation. I changed `Name` displayers to require an edition, and followed the compiler errors. Most methods just propagate the edition requirement. The interesting cases are mostly in `ide-assists`, as sometimes the correct crate to fetch the edition from requires awareness (there may be two). `ide-completions` and `ide-diagnostics` were solved pretty easily by introducing an edition field to their context. `ide` contains many features, for most of them it was propagated to the top level function and there the edition was fetched based on the file.

I also fixed all FIXMEs from #17896. Some required introducing an edition parameter (usually not for many methods after the changes to `Name`), some were changed to a new method `is_any_identifier()` because they really want any possible keyword.

Fixes #17895.
Fixes #17774.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
I didn't know we run Clippy!

File: crates/ide-completion/src/completions/flyimport.rs [hunk 1]
```diff
@@ -411,7 +411,7 @@ fn compute_fuzzy_completion_order_key(
     cov_mark::hit!(certain_fuzzy_order_test);
     let import_name = match proposed_mod_path.segments().last() {
         // FIXME: nasty alloc, this is a hot path!
-        Some(name) => name.display_no_db().to_smolstr().to_ascii_lowercase(),
+        Some(name) => name.unescaped().display_no_db().to_smolstr().to_ascii_uppercase(),
```
Comment (Veykril) [inline crates/ide-completion/src/completions/flyimport.rs:414]: why the casing change?

File: crates/ide-completion/src/tests/flyimport.rs [hunk 2]
```diff
@@ -227,9 +227,9 @@ fn main() {
 }
 "#,
         expect![[r#"
-            st ThirdStruct (use dep::some_module::ThirdStruct) ThirdStruct
             st AfterThirdStruct (use dep::some_module::AfterThirdStruct) AfterThirdStruct
             st ThiiiiiirdStruct (use dep::some_module::ThiiiiiirdStruct) ThiiiiiirdStruct
+            st ThirdStruct (use dep::some_module::ThirdStruct) ThirdStruct
```
Comment (Veykril) [inline crates/ide-completion/src/tests/flyimport.rs:232]: I imagine this is due to the casing change mentioned before

File: crates/ide/src/inlay_hints/param_name.rs [hunk 3]
```diff
@@ -121,7 +130,9 @@ fn should_hide_param_name_hint(
     }
 
     let fn_name = match callable.kind() {
-        hir::CallableKind::Function(it) => Some(it.name(sema.db).display_no_db().to_smolstr()),
+        hir::CallableKind::Function(it) => {
+            Some(it.name(sema.db).display_no_db(edition).to_smolstr())
+        }
```
Comment (Veykril) [inline crates/ide/src/inlay_hints/param_name.rs:135]: I think here we want to always consider the non-r#-prefixed name?

File: crates/ide/src/rename.rs [hunk 4]
```diff
@@ -1433,7 +1422,7 @@ pub fn baz() {}
                         ),
                         [
                             Indel {
-                                insert: "r#fn",
+                                insert: "fn",
```
Comment (Veykril) [inline crates/ide/src/rename.rs:1425]: This is wrong no?

File: crates/syntax-bridge/src/lib.rs [hunk 5]
```diff
@@ -301,14 +301,12 @@ where
...
                     }
                     let leaf: tt::Leaf<_> = match kind {
-                        T![true] | T![false] => make_ident!(),
-                        IDENT => {
+                        k if k.is_any_identifier() => {
                             let text = token.to_text(conv);
                             tt::Ident::new(&text, conv.span_for(abs_range)).into()
                         }
                         UNDERSCORE => make_ident!(),
                         // FIXME: Edition
```
Comment (Veykril) [inline crates/syntax-bridge/src/lib.rs:309]: stale comment

File: crates/ide-completion/src/completions/flyimport.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/ide-completion/src/completions/flyimport.rs:414]: Oops I tried to avoid the allocationn (and failed), must've screwed that.

File: crates/hir-def/src/import_map.rs [hunk 6]
```diff
@@ -461,7 +470,7 @@ fn search_maps(
                     query.search_mode.check(
                         &query.query,
                         query.case_sensitive,
-                        &info.name.display(db.upcast()).to_smolstr(),
+                        &info.name.display(db.upcast(), edition).to_smolstr(),
```
[the remark this answers is not in the document]
Comment (ChayimFriedman2) [reply crates/hir-def/src/import_map.rs:473]: Right, it should use unescaped identifier.

The original code also has this bug which is why my PR has it.

BTW, I fixed such bugs in bunch of other places.

File: crates/hir-expand/src/name.rs [hunk 7]
```diff
@@ -54,17 +55,29 @@ impl PartialEq<Name> for Symbol {
...
+    fn eq(&self, other: &str) -> bool {
+        self.as_str() == other.trim_start_matches("r#")
+    }
+}
+
+impl PartialEq<Name> for str {
+    fn eq(&self, other: &Name) -> bool {
+        other == self
+    }
+}
```
[the remark this answers is not in the document]
Comment (ChayimFriedman2) [reply crates/hir-expand/src/name.rs:68]: Would a method be acceptable?

File: crates/hir-ty/src/diagnostics/decl_check.rs [hunk 8]
```diff
@@ -748,12 +764,19 @@ impl<'a> DeclValidator<'a> {
             return;
         };
 
+        let edition = match file_id.repr() {
+            HirFileIdRepr::FileId(it) => it.edition(),
+            HirFileIdRepr::MacroFile(it) => {
+                let krate = it.macro_call_id.lookup(self.db.upcast()).def.krate;
+                self.db.crate_graph()[krate].edition
+            }
+        };
```
[the remark this answers is not in the document]
Comment (ChayimFriedman2) [reply crates/hir-ty/src/diagnostics/decl_check.rs:773]: [There is no such trait](https://github.com/search?q=repo%3Arust-lang%2Frust-analyzer%20HirFileExt&type=code) (neither locally).

File: crates/ide/src/inlay_hints/param_name.rs (hunk 3 above)
Comment (ChayimFriedman2) [reply crates/ide/src/inlay_hints/param_name.rs:135]: Either is fine, but I agree this makes more sense.

File: crates/ide/src/rename.rs (hunk 4 above)
Comment (ChayimFriedman2) [reply crates/ide/src/rename.rs:1425]: Oops, forgot to handle the renaming of `mod` in the definition (it is in its own function).

File: crates/hir-ty/src/diagnostics/decl_check.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (Veykril) [reply crates/hir-ty/src/diagnostics/decl_check.rs:773]: ah wrong name https://github.com/rust-lang/rust-analyzer/blob/d14aa61794b99a516a233a8ad8f88a85bf061113/crates/hir-expand/src/lib.rs#L281

**Comment by ChayimFriedman2** [comment]
Fixed all comments.

File: crates/hir-def/src/import_map.rs [hunk 9]
```diff
@@ -78,12 +84,13 @@ impl ImportMap {
...
         let map = Self::collect_import_map(db, krate);
 
+        let edition = db.crate_graph()[krate].edition;
         let mut importables: Vec<_> = map
             .iter()
             // We've only collected items, whose name cannot be tuple field so unwrapping is fine.
             .flat_map(|(&item, (info, _))| {
                 info.iter().enumerate().map(move |(idx, info)| {
-                    (item, info.name.display(db.upcast()).to_smolstr(), idx as u32)
+                    (item, info.name.display(db.upcast(), edition).to_smolstr(), idx as u32)
```
Comment (Veykril) [inline crates/hir-def/src/import_map.rs:93]: This should also ignore the edition I think

**Comment by Veykril** [comment]
> There should be a convenience method on `HirFileId` now via `HirFileExt::edition` for this

Turns out I was dumb, that function is something I introduced in a non yet merged branch of mine 🙃 apologies for that confusion
