### PR TITLE
fix:add a case in which remainig is None in resolveing types when resolving hir path. 

### LINKED ISSUE #14030: The variable type is being determined incorrectly
In the following example, instead of `pub struct FOO`, `pub fn FOO()` is displayed. Also `Go to Definition` jumps to `pub fn FOO()`.

[main.rs.txt](https://github.com/rust-lang/rust-analyzer/files/10508632/main.rs.txt)

изображение

The problem is observed if a path is specified before `FOO`. There is no such problem in line 14 and 15.

rust-analyzer version: 0.3.1377-standalone (daa0138e4 2023-01-21)

```
>rustup show
...
active toolchain
----------------
stable-x86_64-pc-windows-msvc (default)
rustc 1.66.1 (90743e729 2023-01-10)
```

VS Code 
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: Yes

### PR DESCRIPTION
**Pull request by Kohei316**
fix #14030 The variable type is being determined incorrectly
This PR fixed a problem in which `go to definition` is jumping to the incorrect position because it was failing to resolve the type in case it defined in the module when resolving hir.
In addition, I added a test for this issue and refactored the related code.
This is my first PR and I am using a translation tool to write this text. Let me know if you have any problems.

### CODE REVIEW

File: crates/hir/src/source_analyzer.rs [hunk 1]
```diff
@@ -946,14 +946,14 @@ fn resolve_hir_path_(
                 let (ty, remaining) =
                     resolver.resolve_path_in_type_ns(db.upcast(), path.mod_path())?;
                 match remaining {
-                    Some(remaining) if remaining > 1 => {
+                    Some(remaining) => {
                         if remaining + 1 == path.segments().len() {
```
Comment (lowr) [inline crates/hir/src/source_analyzer.rs:950]: `remaining` is a confusing name, I'm guessing this bug was introduced by misinterpreting this variable as the number of remaining segments while it actually indicates the index of first unresolved segment. Could you rename it to something like `remaining_idx`?

**Review by lowr — COMMENTED** [review]
This looks correct. Can you squash all the commits into one?

File: crates/hir/src/source_analyzer.rs (hunk 1 above)
Comment (Kohei316) [reply crates/hir/src/source_analyzer.rs:950]: Sure! Thank you for suggestion!
