### PR TITLE
fix: avoid adding enum parens in use path

### LINKED ISSUE #12420: Variant completions in use paths add parentheses and braces
```rs

use module::Enum::$0;
mod module {
    pub enum Enum {
        UnitVariant,
        TupleVariant(),
        RecordVariant {},
    }
}
```

### PR DESCRIPTION
**Pull request by yue4u**
close #12420

### CODE REVIEW

File: crates/ide-completion/src/render/literal.rs [hunk 1]
```diff
@@ -50,9 +50,15 @@ fn render(
...
-        matches!(completion.path_context(), Some(PathCompletionCtx { has_call_parens: true, .. }));
+    let mut kind = thing.kind(db);
+    let should_add_parens = match completion.path_context() {
+        Some(PathCompletionCtx { has_call_parens: true, .. }) => false,
+        Some(PathCompletionCtx { kind: PathKind::Use | PathKind::Type { .. }, .. }) => {
+            cov_mark::hit!(no_parens_in_use_item);
+            false
+        }
+        _ => true,
+    };
```
Comment (yue4u) [inline crates/ide-completion/src/render/literal.rs:61]: This is similar to https://github.com/rust-lang/rust-analyzer/blob/995a17fbd9f7cdedfdafec946b1d9e44eff448b4/crates/ide-completion/src/render/function.rs#L201-L210 but that one is limited `has_call_parens` to `PathKind::Expr`

File: crates/ide-completion/src/render/literal.rs [hunk 2]
```diff
@@ -82,6 +88,11 @@ fn render(
         rendered.literal.push_str("$0");
     }
 
+    // only show name in label if not adding parens
+    if !should_add_parens {
+        kind = StructKind::Unit;
+    }
+
```
Comment (yue4u) [inline crates/ide-completion/src/render/literal.rs:95]: It feels strange to me when completion labels still have parens

**Comment by Veykril** [comment]
Thanks!
@bors r+
