### PR TITLE
fix: run flycheck without rev_deps when target is specified

### LINKED ISSUE #17829: Pass `--bin` to `cargo check` when a binary is changed
I marked this as important because it affects Rust beginners and I don't want them to get a bad expression while learning with Rustlings. It causes Rustlings to freeze for a long time because Rust-Analyzer blocks Cargo.

The issue is described here with a video: https://github.com/rust-lang/rustlings/issues/2071

I was able to reproduce it in VS-Code in a Windows 10 VM (probably not a Windows problem, didn't test on Linux).

You don't even need to have Rustlings running in the background to see how Rust-Analyzer rebuilds everything on every file save:
- Initialize Rustlings with `rustlings inti`
- Open VS-Code in the generated `rustlings/` directory
- Wait for Rust-Analyzer to be done
- Open a file and trigger a save
- See that Rust-Analyzer **rebuilds all 188 binaries!**

~It looks like an issue in the Rust-Analyzer VS-Code plugin because it doesn't happen in Helix in the same VM.~

The effect probably became more dramatic after I added `--keep-going` in https://github.com/rust-lang/rust-analyzer/pull/17561

### PR DESCRIPTION
**Pull request by alibektas**
Since querying for a crate's target is a call to salsa and therefore blocking, flycheck task is now deferred out of main thread by using `GlobalState`s `deferred_task_queue`. Fixes #17829  and https://github.com/rust-lang/rustlings/issues/2071

### CODE REVIEW

**Comment by alibektas** [comment]
It has been mentioned that this particular case is not only limited to binary targets. I would be happy to add also other cases.

**Review by Veykril — COMMENTED** [review]
Okay two things, I think I was wrong with this requiring a queued task as we have already been doing all the work within the spawned task (and can still continue to do so), so we can undo that part. The other thing is that when we do have the binary case here, we should not only skip the reverse dependency stuff, we should also tell flycheck to pass `--bin <bin-name>` for its check, that will require some more changes in the flycheck restart logic

File: crates/rust-analyzer/src/flycheck.rs [hunk 1]
```diff
@@ -396,6 +400,10 @@ impl FlycheckActor {
                     None => cmd.arg("--workspace"),
                 };
 
+                if let Some(tgt) = bin_target {
+                    cmd.arg("--bin").arg(tgt);
```
Comment (mo8it) [inline crates/rust-analyzer/src/flycheck.rs:404]: We probably should also pass the package here (non-optional). Two packages in a workspace can have the a binary with the same name. In that case, Cargo checks both of them (tested it).

File: crates/rust-analyzer/src/handlers/notification.rs [hunk 2]
```diff
@@ -347,8 +365,11 @@ fn run_flycheck(state: &mut GlobalState, vfs_path: VfsPath) -> bool {
                     if id == flycheck.id() {
                         updated = true;
                         match package.filter(|_| !world.config.flycheck_workspace()) {
-                            Some(package) => flycheck.restart_for_package(package),
-                            None => flycheck.restart_workspace(saved_file.clone()),
+                            Some(package) => {
+                                flycheck.restart_for_package(package, target_is_bin.clone())
```
Comment (mo8it) [inline crates/rust-analyzer/src/handlers/notification.rs:369]: We could break here if the target is a binary and avoid cloning.

File: crates/rust-analyzer/src/flycheck.rs [hunk 3]
```diff
@@ -118,14 +118,14 @@ impl FlycheckHandle {
     }
 
     /// Schedule a re-start of the cargo check worker to do a workspace wide check.
-    pub(crate) fn restart_workspace(&self, saved_file: Option<AbsPathBuf>) {
-        self.sender.send(StateChange::Restart { package: None, saved_file }).unwrap();
+    pub(crate) fn restart_workspace(&self, saved_file: Option<AbsPathBuf>, target: Option<String>) {
```
Comment (mo8it) [inline crates/rust-analyzer/src/flycheck.rs:121]: Workspace with target binary isn't a good fit (see comment below). So only allow passing target binary in `restart_for_package`.

File: crates/rust-analyzer/src/flycheck.rs [hunk 4]
```diff
@@ -281,11 +281,14 @@ impl FlycheckActor {
                         }
                     }
 
-                    let command =
-                        match self.check_command(package.as_deref(), saved_file.as_deref()) {
-                            Some(c) => c,
-                            None => continue,
-                        };
+                    let command = match self.check_command(
```
Comment (Veykril) [inline crates/rust-analyzer/src/flycheck.rs:284]: This can be rewritte as a `let else` statement now (there should be an assist for that)

File: crates/rust-analyzer/src/flycheck.rs (hunk 1 above)
Comment (Veykril) [reply crates/rust-analyzer/src/flycheck.rs:404]: I think its fine to support either, the package is passed above if a package was set (which should be usually the case)

File: crates/rust-analyzer/src/flycheck.rs [hunk 5]
```diff
@@ -183,7 +183,7 @@ pub(crate) enum Progress {
 }
 
 enum StateChange {
-    Restart { package: Option<String>, saved_file: Option<AbsPathBuf> },
+    Restart { package: Option<String>, saved_file: Option<AbsPathBuf>, target: Option<String> },
```
Comment (Veykril) [inline crates/rust-analyzer/src/flycheck.rs:186]:
```suggestion
    Restart { package: Option<String>, saved_file: Option<AbsPathBuf>, target: Option<Target>},
```
```rs
enum Target {
    Bin(String)
}
```
would be better to change that to an enum up front so we can support other targets more easily (mainly examples come to mind), as those require different flags than bin

File: crates/rust-analyzer/src/handlers/notification.rs [hunk 6]
```diff
@@ -287,16 +288,33 @@ fn run_flycheck(state: &mut GlobalState, vfs_path: VfsPath) -> bool {
...
+                        TargetSpec::ProjectJson(p) => Some(p.label),
+                    };
+                }
+
+                None
+            });
+
+            let crate_ids = if target_is_bin.is_some() {
+                // Trigger flychecks for the only workspace which the binary crate belongs to
+                world.analysis.crates_for(file_id)?.into_iter().unique().collect::<Vec<_>>()
```
Comment (Veykril) [inline crates/rust-analyzer/src/handlers/notification.rs:305]: We should already have that information in the `TargetSpec`, it should contain the relevant crate id

File: crates/rust-analyzer/src/handlers/notification.rs (hunk 2 above)
Comment (Veykril) [reply crates/rust-analyzer/src/handlers/notification.rs:369]: The clone is fine, this isn't really performance critical code. I'd rather we don't break here as it just makes this more complicated than necessary

File: crates/rust-analyzer/src/flycheck.rs (hunk 5 above)
Comment (mo8it) [reply crates/rust-analyzer/src/flycheck.rs:186]: Bin, example, test and bench

File: crates/rust-analyzer/src/flycheck.rs (hunk 1 above)
Comment (mo8it) [reply crates/rust-analyzer/src/flycheck.rs:404]: Not for Rustlings. But if we extend this to tests instead of only bins, a workspace could have multiple packages with the test `integration_tests` for example. I don't see why rust-analyzer should check all of them if only one changes.

Comment (Veykril) [reply crates/rust-analyzer/src/flycheck.rs:404]: Fair, I'd still leave the logic as is though and just change the restart callers as this invocation isn't technically invalid.

File: crates/rust-analyzer/src/handlers/notification.rs [hunk 7]
```diff
@@ -347,8 +365,11 @@ fn run_flycheck(state: &mut GlobalState, vfs_path: VfsPath) -> bool {
                     if id == flycheck.id() {
                         updated = true;
                         match package.filter(|_| !world.config.flycheck_workspace()) {
```
Comment (Veykril) [inline crates/rust-analyzer/src/handlers/notification.rs:367]:
```suggestion
                        match package.filter(|_| !world.config.flycheck_workspace() || target_is_bin.is_some()) {
```
As per https://github.com/rust-lang/rust-analyzer/pull/17912#discussion_r1724704318

File: crates/rust-analyzer/src/handlers/notification.rs (hunk 6 above)
Comment (alibektas) [reply crates/rust-analyzer/src/handlers/notification.rs:305]: this is the only bit I couldn't really come up with a solution because the package information for `RustProjectJson` is not really clear.

Comment (Veykril) [reply crates/rust-analyzer/src/handlers/notification.rs:313]: No worries, https://github.com/rust-lang/rust-analyzer/pull/17946 the data was there but not exposed that's all
