### PR TITLE
internal: Be more resilient to bad language item definitions in binop inference

### LINKED ISSUE #16286: ice: assertion failed `2 == 3` `[Type, Type, Type]`
`rust-analyzer 1.77.0-nightly (595bc6f 2024-01-05)`
```rust
#[lang="shr"]
pub trait Shr<RHS,Result> {
    fn shr(&self, rhs: &RHS) -> Result;
}

macro_rules! shr_impl(
    ($($t:ty)*) => ($(
        impl Shr<$t, $t> for $t {
            fn shr -> $t { (*self) >>  }
        }
    )*)
)

shr_impl!(u8)

```

`rust-analyzer highlight  < a.rs`

```
thread 'main' panicked at crates/hir-ty/src/builder.rs:66:9:
assertion `left == right` failed: [Type, Type, Type]
  left: 2
 right: 3
stack backtrace:
   0: rust_begin_unwind
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:337:23
   3: core::panicking::assert_failed::<usize, usize>
   4: <hir_ty::builder::TyBuilder<()>>::build
   5: <hir_ty::infer::InferenceContext>::infer_overloadable_binop
   6: <hir_ty::infer::InferenceContext>::infer_expr_inner
   7: <hir_ty::infer::InferenceContext>::infer_expr_coerce
   8: <hir_ty::infer::InferenceContext>::infer_block
   9: <hir_ty::infer::InferenceContext>::infer_expr_inner
  10: <hir_ty::infer::InferenceContext>::infer_return
  11: hir_ty::infer::infer_query
  12: <salsa::derived::slot::Slot<hir_ty::db::InferQueryQuery, salsa::derived::AlwaysMemoizeValue>>::execute
  13: <_ as hir_ty::db::HirDatabase>::infer_query::__shim
  14: hir_ty::db::infer_wait
  15: <hir::semantics::SemanticsImpl>::analyze_impl
  16: <hir::semantics::SemanticsImpl>::resolve_path
  17: <ide_db::defs::NameRefClass>::classify
  18: ide::syntax_highlighting::highlight
  19: <ide::Analysis>::highlight_as_html
  20: <rust_analyzer::cli::flags::Highlight>::run
  21: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### LINKED ISSUE #16287: ice: `self.remaining() > 0`
`rust-analyzer 1.77.0-nightly (595bc6f 2024-01-05)`
`rust-analyzer highlight <  a.rs`

```rust
#[lang="eq"]
pub trait Eq {
    fn eq(&self, ) -> bool;
    
}

macro_rules! totaleq_impl(
    ($t:ty) => {
        impl TotalEq for $t {
            #
            fn equals(&self, other: &$t) -> bool { *self == *other }
        }
    }
)


totaleq_impl!(i16)

```

```
thread 'main' panicked at crates/hir-ty/src/builder.rs:78:9:
assertion failed: self.remaining() > 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:144:5
   3: <hir_ty::builder::TyBuilder<()>>::push::<chalk_ir::Ty<hir_ty::interner::Interner>>
   4: <hir_ty::infer::InferenceContext>::infer_overloadable_binop
   5: <hir_ty::infer::InferenceContext>::infer_expr_inner
   6: <hir_ty::infer::InferenceContext>::infer_expr_coerce
   7: <hir_ty::infer::InferenceContext>::infer_block
   8: <hir_ty::infer::InferenceContext>::infer_expr_inner
   9: <hir_ty::infer::InferenceContext>::infer_return
  10: hir_ty::infer::infer_query
  11: <salsa::derived::slot::Slot<hir_ty::db::InferQueryQuery, salsa::derived::AlwaysMemoizeValue>>::execute
  12: <_ as hir_ty::db::HirDatabase>::infer_query::__shim
  13: hir_ty::db::infer_wait
  14: <hir::semantics::SemanticsImpl>::analyze_impl
  15: <hir::semantics::SemanticsImpl>::resolve_path
  16: <ide_db::defs::NameRefClass>::classify
  17: ide::syntax_highlighting::highlight
  18: <ide::Analysis>::highlight_as_html
  19: <rust_analyzer::cli::flags::Highlight>::run
  20: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #16287
Fixes #16286

There's one more in `write_fn_trait_method_resolution`, but I'm not sure if it won't cause further problems in `infer_closures`.

### CODE REVIEW

File: crates/hir-ty/src/infer/expr.rs [hunk 1]
```diff
@@ -793,11 +793,12 @@ impl InferenceContext<'_> {
...
                         .method_by_name(&Name::new_symbol_root(sym::index.clone()))
                     {
-                        let substs = TyBuilder::subst_for_def(self.db, index_trait, None)
-                            .push(self_ty.clone())
-                            .push(index_ty.clone())
-                            .build();
-                        self.write_method_resolution(tgt_expr, func, substs);
+                        let subst = TyBuilder::subst_for_def(self.db, index_trait, None);
+                        if subst.remaining() != 2 {
+                            return self.err_ty();
```
Comment (lnicola) [inline crates/hir-ty/src/infer/expr.rs:798]: We modify `adj` above, not sure if it will cause problems.

**Review by flodiebold — APPROVED** [review]
