### PR TITLE
fix(21943): remove duplicate lints

### LINKED ISSUE #21943: Duplicate `warnings` lint complete
**rust-analyzer version**: rust-analyzer 0.4.2848-standalone

**rustc version**: rustc 1.95.0-nightly (a293cc4af 2026-01-30)

**editor or extension**: Vim

**code snippet to reproduce**:
```rust
#[allow(w$0)]
```

```text
#[allow(w)]
        warnings                                    f [LS]   mass-change the level for lints which produce
        warnings                                    f [LS]   warnings
        wasm_c_abi                                  f [LS]
```

### PR DESCRIPTION
**Pull request by jdrouet**
In this PR, I filter the lints that have already been added by name.
There are 2 main groups, the default lints and the rustdoc lints.
This should avoid having duplicates.

Fixes rust-lang/rust-analyzer#21943

PS: I've tried regenerating the lints, it introduced many changes which are not really related, so I manually removed them instead.

### CODE REVIEW

File: crates/ide-completion/src/tests/attribute.rs [hunk 1]
```diff
@@ -1372,6 +1372,13 @@ mod lint {
             r#"#[allow(rustdoc::bare_urls struct Test;"#,
         );
     }
+
+    #[test]
```
Comment (ChayimFriedman2) [inline crates/ide-completion/src/tests/attribute.rs]: We don't need a test for this IMO.

**Review by ChayimFriedman2 — CHANGES_REQUESTED** [review]
Using a hashmap for deduplication, especially with the default hasher but not only, risks ordering changes across runs. Instead, sort and `dedup()`.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22054/17d028e9d7161cf6ebf21e21d3c4a1835099e039..96cfb4999c325b946fffa8d59491ac6a1d132c48)*

**Comment by jdrouet** [comment]
> Using a hashmap for deduplication, especially with the default hasher but not only, risks ordering changes across runs. Instead, sort and `dedup()`.
> 
> _[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22054/17d028e9d7161cf6ebf21e21d3c4a1835099e039..96cfb4999c325b946fffa8d59491ac6a1d132c48)_

Thanks for your answer, but I'm not sure I understand properly.
As you said, the `HashSet` is only used for deduplication, so, as long as we don't change the order of the values in the `Vec`, the result will be the same considering we only call `.contains` 🤔 The hasher is not involved in this, is it?

Thanks in advance 😉

**Review by ChayimFriedman2 — APPROVED** [review]
Right, my mistake (I thought the deduplication is also inside lints and groups, not just between lints and groups). But please remove the test.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22054/17d028e9d7161cf6ebf21e21d3c4a1835099e039..96cfb4999c325b946fffa8d59491ac6a1d132c48)*

File: crates/ide-completion/src/tests/attribute.rs (hunk 1 above)
Comment (jdrouet) [reply crates/ide-completion/src/tests/attribute.rs]: addressed in https://github.com/rust-lang/rust-analyzer/pull/22054/commits/2c933e46ebd346950f3f1878b0cd51aa602f79bb 👍

**Review by ChayimFriedman2 — APPROVED** [review]
Please squash, then LGTM.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22054/17d028e9d7161cf6ebf21e21d3c4a1835099e039..2c933e46ebd346950f3f1878b0cd51aa602f79bb)*

**Comment by jdrouet** [comment]
One commit is probably enough for this 😉 done!

**Review by ShoyuVanilla — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22054/c41c134c0f767b149c0c20a4adea1b05da947844..07cf5e4ebeadb977adc1248374614e18b9c8a0fa)*
