### PR TITLE
fix: local items should not be completed in parent signature

### LINKED ISSUE #11959: local items are being completed in parent signature
We get a `Bar` completion for the following snippet which is wrong as the item is not visible in that position.
```rust
fn foo() -> $0 {
    struct Bar;
}
```

### PR DESCRIPTION
**Pull request by XFFXFF**
fixes #11959 

> We get a Bar completion for the following snippet which is wrong as the item is not visible in that position.
> ``` rust
> fn foo() -> $0 {
>    struct Bar;
> }
> ```

I investigated the problem and found that the scope of the cursor offset, also `CompletionContext.scope` is the body of the function

### CODE REVIEW

File: crates/hir/src/source_analyzer.rs [hunk 1]
```diff
@@ -600,13 +603,11 @@ fn scope_for_offset(
...
             Some((source.value.text_range(), scope))
         })
-        // find containing scope
-        .min_by_key(|(expr_range, _scope)| {
-            (
-                !(expr_range.start() <= offset.value && offset.value <= expr_range.end()),
-                expr_range.len(),
-            )
+        .filter(|(expr_range, _scope)| {
+            expr_range.start() <= offset.value && offset.value <= expr_range.end()
```
Comment (XFFXFF) [inline crates/hir/src/source_analyzer.rs:607]: Filter out scopes whose text range does not contain the `offset`, why do we need to take them into account when we are looking for containing scope before?

But after this change, one of the old tests doesn't pass

image

Then I found that in the above test case, the `offset.file_id` here is a `MarcoFile` , which is not reasonable, the `offset.value` is relative to the original file, the `offset.file_id` should also be the original file. Wrong `offset.file_id` affects the scope of the `offset`, related code: 

https://github.com/rust-lang/rust-analyzer/blob/7ade4d49fc59ec939294897890375a8b86c743e2/crates/hir/src/source_analyzer.rs#L587-L602

That's why I changed lines 91-94. After I changed this, all the tests passed.

Comment (Veykril) [reply crates/hir/src/source_analyzer.rs:607]: Sounds reasonable to me, though the same change should be done for `new_for_body` in line 68-71
