### PR TITLE
fix: Prevent wrong invocations of `needs_parens_in` with non-ancestral "parent"s

### LINKED ISSUE #19323: inline veriable assist changes semantics (forgets to add parantheses)
**rust-analyzer version**: rust-analyzer version: 0.3.2330-standalone (02862f5d52 2025-03-03)

**rustc version**: rustc 1.85.0 (4d91de4e4 2025-02-17)

**editor or extension**: Code OSS (vscode), extension version: 0.3.2330

**relevant settings**: None

**code snippet to reproduce**: 
```rust
let a = 123 < 456;
let b = !a;
```

Right click `a` (does not matter which one) and choose "Inline variable".
The result should be `!(123 < 456)`, but actually is `!123 < 456`, which is equivalent to `(!123) < 456`.

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #19323

This also migrates `inline_local_variable` to `SyntaxEditor` as a part of #18285

### CODE REVIEW

File: crates/ide-assists/src/handlers/apply_demorgan.rs [hunk 1]
```diff
@@ -392,15 +394,19 @@ fn f() { !(S <= S || S < S) }
...
 
     #[test]
-    fn demorgan_removes_pars_in_eq_precedence() {
+    fn demorgan_keeps_pars_in_eq_precedence() {
         check_assist(
             apply_demorgan,
             "fn() { let x = a && !(!b |$0| !c); }",
-            "fn() { let x = a && b && c; }",
+            "fn() { let x = a && (b && c); }",
         )
```
Comment (ShoyuVanilla) [inline crates/ide-assists/src/handlers/apply_demorgan.rs:410]: These test chages might be a regression, but I think that the changed ones are more consistent with other test cases

File: crates/ide-assists/src/handlers/inline_local_variable.rs [hunk 2]
```diff
@@ -73,40 +57,60 @@ pub(crate) fn inline_local_variable(acc: &mut Assists, ctx: &AssistContext<'_>)
...
-            let usage_parent_option = usage_node.and_then(|it| it.parent());
+            let usage_parent_option = usage_node.as_ref().and_then(|it| it.parent());
             let usage_parent = match usage_parent_option {
                 Some(u) => u,
-                None => return Some((range, name_ref, false)),
+                None => return Some((name_ref, false)),
             };
-            Some((range, name_ref, initializer_expr.needs_parens_in(&usage_parent)))
+            let should_wrap = initializer_expr
+                .needs_parens_in_place_of(&usage_parent, usage_node.as_ref().unwrap());
```
Comment (ShoyuVanilla) [inline crates/ide-assists/src/handlers/inline_local_variable.rs:66]:
```rust
let a = 123 < 456;
let b = !a;
```
In the above code, `initializer_expr` is `123 < 456` and `usage_parent` is `let b = !a`. So, inside `needs_parens_in`, it assumes that `initializer_expr` "comes before parent" because its text range is earlier, and decides that it needs no parentheses

**Review by Veykril — APPROVED** [review]
