### PR TITLE
fix: Fix postfix completions inside macros

### LINKED ISSUE #19069: Broken snippets being applied in `assert!`, `debug_assert!` and `format!`
**rust-analyzer version**: rust-analyzer 1 (248bd511ae 2025-01-18)

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: Zed, Neovim (via rustaceanvim)

**relevant settings**: No environment variables, default settings for both editors and rustaceanvim.

**repository link (if public, optional)**: No need, see the snippet.

When applying a snippet in `assert!`, `debug_assert!` or `format!` any whitespace (excluding ones inside string literals) get removed, and possibly broken code is inserted.
The problematic snippets I tested are `box` and `unsafe` but there might be more.
The exact behavior depends on the snippet, but using another snippet breaks things further and instead of just removing whitespaces. See a few examples in the reproducer.

**code snippet to reproduce**: 

This is the code before applying the snippet. 
```rust
fn main() {
    let a = true;
    assert!(if a == false { true } else { false });
}
```
After applying the snippet the whitespace's are removed from whatever was inside of it.
The example is with the `unsafe` snippet but it works with any of the snippets mentioned above.
```rust
fn main() {
    let a = true;
    assert!(unsafe { ifa==false{true}else{false} })
}
```
Not only does this break any code that needs whitespace's, it tampers with undo's in Zed as well (not in Neovim so Im unsure if this part is an editor bug or configuration bug of some kind).
Issuing an undo after applying the snippet yields us with:
```rust
fn main() {
    let a = true;
    assert!(if a == false { true } else { false }.unsafe { ifa==false{true}else{false} })
}
```

There are many snippet combinations that could be broken so just leaving a few examples instead of all possible combinations. 

Applying a box snippet followed by an unsafe snippet. 
Reversiving the order of how the snippet is applied yields us the correct result except of the missing whitespace's.
```rust
fn main() {
    let a = true;
    assert!(Box::new(ifa==false{true}else{false}).unsafe {
        
    })
}
```

Applying a box snippet twice.
```rust
fn main() {
    let a = true;
    assert!(Box::new(ifa==false{true}else{false}).Box)
}
```

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Previously the receiver text was taken directly from the AST, which in macros is missing trivia, leading to corruption (or just unintended replacement of user code).

Now we upmap the range, and extract the original file text in it.

Fixes #19069.

### CODE REVIEW

File: crates/ide-completion/src/completions/postfix.rs [hunk 1]
```diff
@@ -284,15 +294,15 @@ fn escape_snippet_bits(text: &mut String) {
     stdx::replace(text, '$', "\\$");
 }
 
-fn include_references(initial_element: &ast::Expr) -> (ast::Expr, ast::Expr) {
+fn include_references(initial_element: &ast::Expr) -> (ast::Expr, String) {
```
Comment (ChayimFriedman2) [inline crates/ide-completion/src/completions/postfix.rs:297]: I had to change this method so that the node we use will be derived from the Semantics.

**Review by Veykril — APPROVED** [review]
