### PR TITLE
fix: preceding QualifiedPathType for into_to_from assist

### LINKED ISSUE #15598: The `into` to `from` assist outputs wrong syntax for some types
The "convert `into` to fully qualified `from`" assist breaks code for some output types, eg arrays:
```rust
fn tuple_to_array() -> [i32; 2] {
    (0,1).into()
}
```
produces `[i32; 2]::from((0,1))` instead of `<[i32; 2]>::from((0,1))` resulting in an "error: missing angle brackets in associated item path".

**rust-analyzer version**: 0.3.1657-standalone
**rustc version**: 1.72.0 (5680fa18f 2023-08-23)

### PR DESCRIPTION
**Pull request by alibektas**
fixes #15598

### CODE REVIEW

File: crates/ide-assists/src/handlers/into_to_qualified_from.rs [hunk 1]
```diff
@@ -52,18 +52,24 @@ pub(crate) fn into_to_qualified_from(acc: &mut Assists, ctx: &AssistContext<'_>)
...
+
+        if adjusted_tc.is_unknown() && adjusted_tc.contains_unknown() {
+            return None;
+        }
+
+        let qualified_from = format!(
+            "<{}>::from({})",
+            adjusted_tc.display_source_code(db, scope.module().into(), true).ok()?,
+            receiver
+        );
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/into_to_qualified_from.rs:65]: We can move everything but the `adjusted_tc.display_source_code(db, scope.module().into(), true).ok()?` line into the builder closure

File: crates/ide-assists/src/handlers/into_to_qualified_from.rs [hunk 2]
```diff
@@ -52,18 +52,24 @@ pub(crate) fn into_to_qualified_from(acc: &mut Assists, ctx: &AssistContext<'_>)
         == FamousDefs(sema, scope.krate()).core_convert_Into()?
     {
         let type_call = sema.type_of_expr(&method_call.clone().into())?;
-        let type_call_disp =
-            type_call.adjusted().display_source_code(db, scope.module().into(), true).ok()?;
+        let adjusted_tc = type_call.adjusted();
+
+        if adjusted_tc.is_unknown() && adjusted_tc.contains_unknown() {
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/into_to_qualified_from.rs:57]:
```suggestion
        if adjusted_tc.contains_unknown() {
```
should suffice

**Review by Veykril — COMMENTED** [review]
While this is completely valid, it is a bit odd ending up with `<Foo>::thing` when `Foo::thing` is encouraged. We can probably iterate the rendered type string and check whether all characters are identifier chars and omit the `<>` then. (Ideally we could do that check on the hir::Type somehow but I don't think we have the infra for that and it sounds non trivial, not sure though).

File: crates/ide-assists/src/handlers/into_to_qualified_from.rs [hunk 3]
```diff
@@ -52,17 +52,25 @@ pub(crate) fn into_to_qualified_from(acc: &mut Assists, ctx: &AssistContext<'_>)
...
+        let sc = adjusted_tc.display_source_code(db, scope.module().into(), true).ok()?;
         acc.add(
             AssistId("into_to_qualified_from", AssistKind::Generate),
             "Convert `into` to fully qualified `from`",
             nameref.syntax().text_range(),
             |edit| {
                 edit.replace(
                     method_call.syntax().text_range(),
-                    format!("{}::from({})", type_call_disp, receiver),
+                    if sc.chars().find(|c| !c.is_alphanumeric() && c != &':').is_some() {
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/into_to_qualified_from.rs:69]:
```suggestion
                    if sc.chars().any(|&c| !c.is_alphanumeric() && c != ':') {
```
Alternatively (with the then and else branches flipped)
```rs
                    if sc.chars().all(|&c| c.is_alphanumeric() || c = ':') {
                        format!("{}::from({})", sc, receiver)
                    } else {
                        format!("<{}>::from({})", sc, receiver)
                    },
```
would be a bit more readable due to less negations
