### PR TITLE
fix stack overflow in `is_ty_uninhabited_from`

### LINKED ISSUE #14421: thread 'Worker' has overflowed its stack
This code crashes rust-analyzer. (`thread 'Worker' has overflowed its stack`)

```rust
pub enum Tree {
  Node(TreeNode),
  Leaf(TreeLeaf),
}

pub struct TreeNode {
  pub depth: usize,
  pub children: [Box<Tree>; 8]
}

pub struct TreeLeaf {
  pub depth: usize,
  pub data: u8
}

pub fn test() {
  let tree = Tree::Leaf(
    TreeLeaf {
      depth: 0,
      data: 0
    }
  );
}
```

The issue seems to be with the creation of the tree, commenting out the body of the `test` function stops the error from occurring.

rust-analyzer version (VS-code): v0.3.1451

also tried pre-release version: v0.4.1450, the error still occurs.

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #14421

### CODE REVIEW

File: crates/hir-ty/src/inhabitedness.rs [hunk 1]
```diff
@@ -45,6 +51,9 @@ pub(crate) fn is_enum_variant_uninhabited_from(
 
 struct UninhabitedFrom<'a> {
     target_mod: ModuleId,
+    recursive_ty: FxHashMap<Ty, ()>,
```
Comment (Veykril) [inline crates/hir-ty/src/inhabitedness.rs:54]:
```suggestion
    recursive_ty: FxHashSet<Ty>,
```

**Review by Veykril — APPROVED** [review]
