### PR TITLE
Properly handle different defaults for severity of lints

### LINKED ISSUE #18462: Bug in handling `unsafe_op_in_unsafe_fn`
Handling of `unsafe_op_in_unsafe_fn` warning introduced by #18135 is unfortunately a bit broken (@ChayimFriedman2).

In our project, we deny warnings, which only has an effect on *enabled* warnings. In edition 2021 (which is the current default) the warning `unsafe_op_in_unsafe_fn` is not enabled (allow-by-default).

When compiling regularly with `#[deny(warnings)]`, the compiler doesn't complain. However, `rust-analyzer` produces a lot of warnings/errors for all unsafe-in-unsafe calls in our code (one library in our project being an async executor implementation naturally has a lot of unsafe code).

**rust-analyzer version**: 0.3.2162-standalone (3b3a87fe9 2024-10-27)

**rustc version**: rustc 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: VSCode

**relevant settings**: (nothing specific, trivial project shows it)

**code snippet to reproduce**: 

The minimal example I came up with is this one:

Contents of `main.rs`:
```rust
#![warn(warnings)] // <- or `deny` - it activates the warning in Edition 2021!
unsafe fn dangerous() {}
unsafe fn call_dangerous() { dangerous(); }
fn main() { unsafe { call_dangerous(); } }
```

For completeness, here the `Cargo.toml`:
```toml
[package]
name = "test_unsafe"
version = "0.1.0"
edition = "2021"
```

It seems like the warning is improperly enabled when `#[warn(warnings)]` or `#[deny(warnings)]` is in place. It should be only enabled if either edition is set to 2024 or if it's explicitly enabled by `#[warn(unsafe_op_in_unsafe_fn)]` or `#[deny(unsafe_op_in_unsafe_fn)]`.

Please fix the warning activation and ideally name a workaround for the time being. Thanks in advance.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Previously all lints were assumed to be `#[warn]`, and we had a hand-coded list of `#[allow]` exceptions. Now the severity is autogenerated from rustdoc output.

Also support lints that change status between editions, and the `warnings` lint group.

Fixes #18462.

### CODE REVIEW

File: crates/edition/src/lib.rs [hunk 1]
```diff
@@ -1,6 +1,5 @@
 //! The edition of the Rust language used in a crate.
-// Ideally this would be defined in the span crate, but the dependency chain is all over the place
-// wrt to span, parser and syntax.
+// This should live in a separate crate because we use it in both actual code and codegen.
```
Comment (Veykril) [inline crates/edition/src/lib.rs:2]: Can we just `include!` this file in xtask instead? I personally don't really like this small thing being a crate. Or just duplicate what we need given its not much

Comment (ChayimFriedman2) [reply crates/edition/src/lib.rs:2]: I don't want to duplicate because then adding edition will need to touch both. But `include!()` seems fine.

Comment (ChayimFriedman2) [reply crates/edition/src/lib.rs:2]: It works for rustc but r-a is unable to find the file both with `#[path = "..."] mod edition;` and with `include!()`, do you know why?

Comment (Veykril) [reply crates/edition/src/lib.rs]: Ahaha, right. This fails in r-a because the include lies outside of the source root of the crate itself so we fail to resolve the path... This is one of the outstanding problems with our VFS system

Comment (ChayimFriedman2) [reply crates/edition/src/lib.rs:2]: Done.

@rustbot ready

**Comment by ChayimFriedman2** [comment]
@Veykril can you re-approve? Thanks.

**Comment by ChayimFriedman2** [comment]
I cannot reproduce the failure locally - @Veykril do you have any idea what's going on?

**Comment by lnicola** [comment]
Are you on Windows with your profile on a `D:` drive or something like that?

**Comment by Veykril** [comment]
Oh no are we still racing in that test?
