### PR TITLE
fix: Implement mixed site hygiene

### LINKED ISSUE #10535: `goto_definition` should not navigate to the local variable defined in macros.
As @matklad mentions [here](https://youtu.be/GPyTaoI_x3c?t=1122)，`goto_definition` should not navigate to the local variable defined in macros.   
```rust
macro_rules! m {
    () => {
        let x = 2;
    };
}

#[test]
fn test_hygiene() {
    let x = 1;
    m!();
    println!("{}", x)
}
```
When I put the cursor on the x in `println!`, use `goto_definition`, it will navigate to macro call `m!()`.
Similarly, `highlight_related` should not highlight `m!` when I put the cursor on the x.

### LINKED ISSUE #11681: Hygiene not taken into account for name resolution (wrong type inference with `izip!`)
In this line:
https://github.com/rust-analyzer/rust-analyzer/blob/69e5bd5a2532cfe47e5517d720eb70cbf3f4a908/crates/ide_assists/src/handlers/inline_call.rs#L347
we infer the wrong type for `expr`, namely we infer `Vec<PathExpr>`. The reason for this seems to be our expansion of the `izip!(params, param_use_nodes, arguments)` macro call:
```rust
$crate::__std_iter::IntoIterator::into_iter(params).zip(param_use_nodes).zip(arguments).map(|((a,b),b)|(a,b,b))
```
note the `.map(|((a,b),b)| (a,b,b))`. This seems to be a hygiene issue, where the different `b`s come from different macro expansions and so we need to consider hygiene to correctly resolve them.

Part of #8961.

### LINKED ISSUE #13758: type-mismatch returns an error on a correct use of the scan_fmt macro
**rust-analyzer version**: 0.3.1309-standalone (a2beeb8db 2022-12-04); also affects pre-release v0.4.1314.
**rustc version**: rustc 1.65.0 (897e37553 2022-11-02)
**relevant settings**: None - I've used VSCode's rust-analyzer extension defaults everywhere, except for
```json
{"rust-analyzer.inlayHints.typeHints.enable": false, "rust-analyzer.checkOnSave.command": "clippy"}
```

I've found a reproducible case where rust-analyzer returns a type mismatch error on code that compiles and runs correctly. (Caveat: I'm relatively new to the Rust ecosystem; equally, I can't see a case in which rustc and RA disagreeing about the type system isn't a bug!)

The offending code below is based on the example given in [scan_fmt](https://crates.io/crates/scan_fmt/).

```rust
#[macro_use]
extern crate scan_fmt;

fn main() {
    let word = scan_fmt!("hello", "{}", String).unwrap();
    println!("{}", word);
}
```

The "problems" tab in VS Code contains the following:

```
expected String, found &str  rust-analyzer(type-mismatch)  [Ln 5, Col 16]
expected String, found &str  rust-analyzer(type-mismatch)  [Ln 5, Col 16]
expected String, found &str  rust-analyzer(type-mismatch)  [Ln 5, Col 16]
```

By comparison, clippy doesn't raise any errors, and compiling and running the example works fine:

```
PS C:\[...]\ra-bug-report> cargo run --bin repro
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\repro.exe`
hello
```

The RA error has the following verbose result:

```json
[{
	"resource": "/c:/[...]/ra-bug-report/src/bin/repro.rs",
	"owner": "rustc",
	"code": {
		"value": "type-mismatch",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#type-mismatch",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "type-mismatch"
		}
	},
	"severity": 8,
	"message": "expected String, found &str",
	"source": "rust-analyzer",
	"startLineNumber": 5,
	"startColumn": 16,
	"endLineNumber": 5,
	"endColumn": 48
}]
```

### LINKED ISSUE #16342: The complete list of calls outside of macro_rules contains macro_rules local variables within macro_rules
```rust
fn main() {
    macro_rules! foo {
        () => {
            let var = 2;
            dbg!(var);
        };
    }
    foo!();
    var;
}
```
**cargo check**
```
error[E0425]: cannot find value `var` in this scope
 --> src/main.rs:9:5
  |
9 |     var;
  |     ^^^ not found in this scope
  |
```
**from line9 open complete list output**
```
var i32                   [LS]
self::                    [LS]
crate::                   [LS]
foo!() macro_rules! foo   [LS]
main()~ fn()              [LS]
...
```

**rust-analyzer version**: `rust-analyzer 1.74.0 (79e9716c 2023-11-13)` and `rust-analyzer 1.77.0-nightly (bf8716f1 2023-12-24)`

**rustc version**: `rustc 1.74.0 (79e9716c9 2023-11-13)` and `rustc 1.77.0-nightly (bf8716f1c 2023-12-24)`

**relevant settings**: NONE

### LINKED ISSUE #18262: Macro place is not taken into account in variable name resolution
In the following code:
```rust
fn foo() {
    let v: i32 = 0;
    macro_rules! m {
        () => {
            v
        };
    }
    let v: String = String::new();
    bar(m!());
}

fn bar(_: i32) {}
```
r-a reports an (experimental) diagnostics, because it infers `m!()` to `String`, because it resolves `v` in the macro to the second `v`:
```rust
expected i32, found String (rust-analyzer(E0308))
```

I'm going to work on this (because without this, my hygiene work generates a huge number of false positives), but it's nice to have an issue to close. So:
@rustbot claim

I expect this quite hard to do since we currently expand the macros during HIR lowering and then when we resolve them we have no idea that the second `v` came from a macro, but we'll see (I also haven't checked yet what rustc does).

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
The realization that made me do this (as explained in detail in the first commit) is that while def-site hygiene is incredibly hard for us, mixed-site hygiene should be easy (well, I underestimated it due to the need of the second commit, but still). And the best part in that is that mixed-site hygiene rules: def-site hygiene is available only on nightly and without a clear path to stabilization, and even when (if) it will stabilize this will still help solving the case of variables/labels.

This brings diagnostics on self down to four (from five, I think? or more) 🎉 and the remaining diagnostics all require next solver (three due to coercion issue, one due to the issue of trait bounds not being preferred).

Best reviewed commit by commit.

Fixes #18262.
Fixes #16342.
Fixes #13758.
Fixes #11681.
Fixes #10535.

(Wow, so many issues! That's heart-filling :heart:)

### CODE REVIEW

File: crates/hir-def/src/body.rs [hunk 1]
```diff
@@ -53,6 +69,20 @@ pub struct Body {
...
+    /// If a binding does not appear here it has `SyntaxContextId::ROOT`.
+    ///
+    /// Note that this may not be the direct `SyntaxContextId` of the binding's expansion, because transparent
+    /// expansions are attributed to their parent expansion (recursively).
+    binding_hygiene: FxHashMap<BindingId, HygieneId>,
+    /// A map from an variable usages to their hygiene ID.
+    ///
+    /// Expressions that can be recorded here are single segment path, although not all single segments path refer
+    /// to variables and have hygiene (some refer to items, we don't know at this stage).
+    expr_hygiene: FxHashMap<ExprId, HygieneId>,
```
Comment (Veykril) [inline crates/hir-def/src/body.rs:85]: I guess this wouldnt be necessary if our `Name`s were storing the `SyntaxContextId`? Given path expressions would then have hygienic paths, bindings also already containing `Name`s, is there a reason we are doing it this way instead of giving `Name`'s its `SyntaxContextId` (which currently is just a `()`)?

File: crates/hir-def/src/body/scope.rs [hunk 2]
```diff
@@ -22,6 +22,7 @@ pub struct ExprScopes {
 #[derive(Debug, PartialEq, Eq)]
 pub struct ScopeEntry {
     name: Name,
+    hygiene: HygieneId,
```
Comment (Veykril) [inline crates/hir-def/src/body/scope.rs:25]: (just noting things here now) This wouldn't be needed if `Name` has its syntax context populated either. Though I guess here it would be duplicated, once in `name: Name` and once in the `Binding` referred to by the `binding: BindingId`

File: crates/hir-def/src/expander.rs [hunk 3]
```diff
@@ -49,6 +49,10 @@ impl Expander {
         }
     }
 
+    pub(crate) fn span_map(&self) -> Option<&SpanMap> {
+        self.span_map.get()
+    }
```
Comment (Veykril) [inline crates/hir-def/src/expander.rs:54]: This seems a bit weird of an API, this shouldnt be optional (it only is due to not always being initialized given the lazy OnceCell)

Comment (Veykril) [reply crates/hir-def/src/expander.rs:54]: We also need to be careful with the span map as that currently accessing it unfortunately completely breaks incrementality :( Though it probably is fine here (as bodies are invalidated anyways), and type inference only when its actually using macros then (assuming we only access it then)

File: crates/hir-def/src/body/lower.rs [hunk 4]
```diff
@@ -60,6 +62,13 @@ pub(super) fn lower(
     krate: CrateId,
     is_async_fn: bool,
 ) -> (Body, BodySourceMap) {
+    // We cannot leave the root span map empty and let any identifier from it be treated as root,
+    // because when inside nested macros `SyntaxContextId`s from the outer macro will be interleaved
+    // with the inner macro, and that will cause confusion because they won't be the same as `ROOT`
+    // even though they should be the same. Also, when the body comes from multiple expansions, their
+    // hygiene is different.
+    let span_map =
+        expander.current_file_id().macro_file().map(|file_id| db.expansion_span_map(file_id));
```
Comment (Veykril) [inline crates/hir-def/src/body/lower.rs:71]: The expander contains a `span_map: OnceCell<SpanMap>`, we can populate that in this case

File: crates/hir-expand/src/lib.rs [hunk 5]
```diff
@@ -217,8 +220,27 @@ pub struct MacroCallLoc {
...
+pub enum MacroId {
+    Macro2Id(Macro2Id),
+    MacroRulesId(MacroRulesId),
+    ProcMacroId(ProcMacroId),
+}
+impl_from!(Macro2Id, MacroRulesId, ProcMacroId for MacroId);
+
 #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
 pub struct MacroDefId {
+    pub id: MacroId,
```
Comment (Veykril) [inline crates/hir-expand/src/lib.rs:243]: Instead of doing this, can we just resolve the `MacroId` to its `MacroDefId` for now via `DefDatabase::macro_def`?

File: crates/hir-def/src/body.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/hir-def/src/body.rs:85]: Yes, this won't be necessary, but this is the entire point of this PR - giving every `Name` hygiene, while required for def-site hygiene, is likely to be much more intrusive and introduce performance penalty, so we instead do it only for variables/labels.

File: crates/hir-def/src/expander.rs (hunk 3 above)
Comment (ChayimFriedman2) [reply crates/hir-def/src/expander.rs:54]: I only need this after expanding a macro (to access the new span map), and a span map is always available in this case, so it doesn't really matter if it returns an `Option` or initializes the cell. At first I tried making `enter_expand()` return the span map too, but this is a more intrusive change (even if it saves an unwrap).

Also inference can't access this since this is `pub(crate)`.

File: crates/hir-expand/src/lib.rs (hunk 5 above)
Comment (ChayimFriedman2) [reply crates/hir-expand/src/lib.rs:243]: Hmm... `MacroDefId` contains an `AstId`. Won't it hurt incrementality?

File: crates/hir-def/src/body.rs (hunk 1 above)
Comment (Veykril) [reply crates/hir-def/src/body.rs:85]: Ah okay, that was the reasoning behind it gotcha

File: crates/hir-expand/src/lib.rs (hunk 5 above)
Comment (Veykril) [reply crates/hir-expand/src/lib.rs]: Only if we store it in some query result again which I don't think is the case? (will double check that tomorrow)

Comment (ChayimFriedman2) [reply crates/hir-expand/src/lib.rs]: That means we will have to store `MacroDefId` in body, and then access it during it inference etc. Although macro definitions in bodies are quite rare, so maybe it's okay.

File: crates/hir-def/src/body.rs (hunk 1 above)
Comment (Veykril) [reply crates/hir-def/src/body.rs:85]: Unresolving this once, can we drop a FIXME *somewhere* talking about this decision just so if someone comes in and fully implements hygiene that they know why this special stuff exists right now?

File: crates/hir-def/src/body/lower.rs [hunk 6]
```diff
@@ -92,6 +103,12 @@ struct ExprCollector<'a> {
     is_lowering_assignee_expr: bool,
     is_lowering_coroutine: bool,
 
+    /// Legacy (`macro_rules!`) macros can have multiple definitions and shadow each other,
+    /// and we need to find the current definition. So we track the number of definitions we saw.
+    current_block_legacy_macro_defs_count: FxHashMap<Name, usize>,
```
Comment (Veykril) [inline crates/hir-def/src/body/lower.rs:108]: I wonder, does this work properly across blocks (that is shadowing in different nesting levels? Feels like it should but just double checking here. Aside, we still need to figure out something similar for def map name resolution, though macro resolution in there is generally too messy right now

File: crates/hir-expand/src/lib.rs (hunk 5 above)
Comment (Veykril) [reply crates/hir-expand/src/lib.rs]: Ah we store this in the `ScopeData` right, I missed that. That still shouldn't be a problem though I think, if the Macro's AstId changes we recompute a bunch of base queries anyways so we aren't losing out on incrementality here. (still looking into this more though to see if there is other problems)

Comment (Veykril) [reply crates/hir-expand/src/lib.rs]: https://github.com/Veykril/rust-analyzer/commit/883c4b9c9dd3328bd3678546cd2a9b6d31ffa865 is the change changing this back, from what I can tell this should be fine (aside from `ScopeData` becoming bigger, that might be a bit much)

Main reason I don't like the change from your PR here is that it makes the Macro ID stuff even more confusing (it is already a nightmare to grasp imo), I'd love if we could simplify it somehow but that likely should wait for the next salsa either way.

File: crates/hir-def/src/body/lower.rs [hunk 7]
```diff
@@ -1145,10 +1206,44 @@ impl ExprCollector<'_> {
...
+                let Some(name) = macro_.name() else {
+                    statements.push(Statement::Item(Item::Other));
+                    return;
+                };
+                let name = name.as_name();
+                let macro_id = self.def_map.modules[DefMap::ROOT]
+                    .scope
+                    .get(&name)
+                    .take_macros()
+                    .expect("def map should have macro definition, but it doesn't");
```
Comment (Veykril) [inline crates/hir-def/src/body/lower.rs:1219]:
```suggestion
                    .expect("def map should have macro definition, but it doesn't");
```
Might be better to skip with a `never!` instead, this feels like we could easily write a bug that reaches this

**Review by Veykril — COMMENTED** [review]
Okay one more last thing, does this have a significant impact on memory (sorry, I'll keep asking this 😬), and does this have a noticable perf impact on the `integrated_benchmark` benches?

File: crates/hir-def/src/body/lower.rs (hunk 6 above)
Comment (ChayimFriedman2) [reply crates/hir-def/src/body/lower.rs:112]: Yes, because each block will have a new defmap. I added a test.

File: crates/hir-expand/src/lib.rs (hunk 5 above)
Comment (ChayimFriedman2) [reply crates/hir-expand/src/lib.rs]: Okay, I changed this to store `MacroDefId`.

File: crates/hir-def/src/body.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/hir-def/src/body.rs:85]: Done.

**Comment by ChayimFriedman2** [comment]
@Veykril Addressed comments.

About perf impact:

This does not have a significant impact on memory (nor do I expect it to have after the removal of the `MacroId` from `MacroDefId`), around 5mb but that's in the unstable range.

For speed, the integrated benchmarks do not show a meaningful difference, but they are very flaky. If I benchmark the whole thing (including workspace loading) using hyperfine, it is up to 200ms slower, but I tend to think this should be attributed to the workspace loading and not the benchmark itself, if this is even a true regression and not just a measurement error..

`analysis-stats .` is not affected.
