### PR TITLE
fix: highlighting for tail expr in labelled blocks

### LINKED ISSUE #19138: Missing exit point highlighting for labeled block tail
```rs
        'a: {
            if true { break 'a None}
            None // this exit point is not being highlighted
        }
```

When the cursor is on `'a` or the `break` we do not highlighting the tail `None` even though it is also an exit point for the block.

### PR DESCRIPTION
**Pull request by roife**
fix rust-lang/rust-analyzer#19138.

This PR adds highlighting for tail expressions of labeled blocks.

### CODE REVIEW

File: crates/ide/src/highlight_related.rs [hunk 1]
```diff
@@ -232,6 +232,22 @@ fn highlight_references(
             }
         }
 
+        if matches!(def, Definition::Label(_)) {
+            let label = token.parent_ancestors().find_map(ast::Label::cast);
```
Comment (Veykril) [inline crates/ide/src/highlight_related.rs:236]:
```suggestion
            let label = token.parent().and_then(ast::Label::cast);
```

File: crates/ide/src/highlight_related.rs [hunk 2]
```diff
@@ -232,6 +232,22 @@ fn highlight_references(
             }
         }
 
+        if matches!(def, Definition::Label(_)) {
```
Comment (Veykril) [inline crates/ide/src/highlight_related.rs:235]: We should start commenting this file a bit more (I am partially at fault for not doing so here :)

So lets put a comment above this stating what this is doing, highlighting the tail expr of labelled blocks

File: crates/ide/src/highlight_related.rs (hunk 1 above)
Comment (roife) [reply crates/ide/src/highlight_related.rs:236]: The hierarchy of an `ast::Label` is structured as `(Label (Lifetime ident) colon)`, which suggests that the `token` here may refer to the `ident` within `Lifetime`.

If we don't use `token.parent_ancestors`, we should write:

```rust
let label = token.parent().and_then(|token| {
    ast::Label::cast(token.clone())
        .or_else(|| token.parent().and_then(ast::Label::cast))
});
```

... which is more complicated 🤔

Comment (Veykril) [reply crates/ide/src/highlight_related.rs:236]: Ah right, lifetime is a node as well, then lets do
```suggestion
let label = token.parent_ancestors().nth(1).and_then(ast::Label::cast);
```

**Review by Veykril — APPROVED** [review]
