### PR TITLE
fix: Fix a bug with missing binding in MBE

### LINKED ISSUE #18876: Hang / High CPU usage with `tracing` macros
**rust-analyzer version**: 0.3.2253-standalone

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: VS Code

**relevant settings**: none

**code snippet to reproduce**: 
```rust
fn main() {
    tracing::error!()
}
```

This snippet causes rust-analyzer to take 100% of one CPU for several dozen seconds. It is completely unresponsive during that time, so this is making it pretty hard to use.

This is with `tracing = "0.1.41"`.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
We should immediately mark them as finished, on the first entry.

The funny (or sad) part was that this bug was pre-existing, but previously to #18327, it was causing us to generate bindings non-stop, 65535 of them, until we get to the hardcoded repetition limit, and then throw it all away. And it was so Blazingly Fast that nobody noticed.

With #18327 however, this is still what happens, except that now instead of *merging* the fragments into the result, we write them on-demand. Meaning that when we hit the limit, we've already written all previous entries. This is a minor change, I thought for myself when I was writing this, and it's actually for the better, so who cares. Minor change? Not so fast. This caused us to emit 65535 repetitions, all of which the MBE infra needs to handle when calling other macros with the expansion, and convert to rowan tree etc., which resulted a *massive* hang.

The test (and also `analysis-stats`) used to crash with stack overflow on this macro, because we were dropping some crazily deep rowan tree. Now they work properly. Because I am lazy, and also because I could not find the exact conditions that causes a macro match but with a missing binding, I just copied all macros from tracing. Easy.

Fixes #18876.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

File: crates/ide-diagnostics/src/tests/overly_long_real_world_cases.rs [hunk 1]
```diff
@@ -0,0 +1,2726 @@
+//! Overly long excerpts of failures from real world cases, that I was too lazy to minimize.
```
Comment (Veykril) [inline crates/ide-diagnostics/src/tests/overly_long_real_world_cases.rs:1]: Honestly might not be too bad to basically have the tracing macro as a test 😬

**Comment by lnicola** [comment]
This is now available in the v0.3.2257 release.
