### PR TITLE
fix: Panic in debug profile for tuple deconstruct with arity mismatch

### LINKED ISSUE #17585: Tuple pattern failure causes panic in Rust Analyzer debug build
Edit: At first, I thought that this was regression between lastest release and `HEAD`, but this happens `debug` but not on `release` profile 🤔   

**rust-analyzer version**: `HEAD` of `master` branch, `ffbc5ad993d5cd2f3b8bcf9a511165470944ab91`

**rustc version**: `rustc 1.79.0 (129f3b996 2024-06-10)`

 
**code snippet to reproduce**: 

```rust
fn main() {
    let (_, _, _, ..) = (true, 42);
}
```

Running `rust-analyzer diagnostics` on the following code in `ffbc5ad993d5cd2f3b8bcf9a511165470944ab91` with debug profile panics with following;

```
thread 'BIG_STACK_THREAD' panicked at crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs:507:9:
internal error: entered unreachable code: uncaught type error: pattern <write_variant_name unsupported>(_ : Bool, _ : Int(I32), _ : {error}) has inconsistent arity (expected arity <= 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

while running it on the same revision with release profile works just fine;

```
2024-07-12T21:39:03.778314Z ERROR hir_ty::diagnostics::match_check::pat_analysis: uncaught type error: pattern <write_variant_name unsupported>(_ : Bool, _ : Int(I32), _ : {error}) has inconsistent arity (expected arity <=
2)
Diagnostic { code: RustcHardError("E0308"), message: "expected (bool, i32), found (bool, i32, {unknown})", range: FileRange { file_id: FileId(11), range: 20..33 }, severity: Error, unused: false, experimental: true, fixes:
None, main_node: None }

diagnostic scan complete

Error: diagnostic error detected
```

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #17585, which doesn't affect daily use cases but quite annoying in development of r-a itself like writing tests.

This PR applies similar approach as in #17534, skipping match usefulness check for patterns containing errors

### CODE REVIEW

File: crates/ide-diagnostics/src/handlers/type_mismatch.rs [hunk 1]
```diff
@@ -745,6 +745,18 @@ fn f() {
...
+        );
+    }
+
+    #[test]
+    fn regression_17585() {
+        check_diagnostics(
+            r#"
+fn f() {
+    let (_, _, _, ..) = (true, 42);
+     // ^^^^^^^^^^^^^ error: expected (bool, i32), found (bool, i32, {unknown})
```
Comment (ShoyuVanilla) [inline crates/ide-diagnostics/src/handlers/type_mismatch.rs:758]: This has been panicking instead of a type mismatch diagnostic

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
