### PR TITLE
"Show implementations" link display error fix

### LINKED ISSUE #9926: "Show implementations" display error
https://user-images.githubusercontent.com/38807139/129599376-82549267-f51d-4693-ab6c-987a8d566a59.mp4

### PR DESCRIPTION
**Pull request by listochkin**
While VSCode [uses it's own implementation for URIs](https://github.com/microsoft/vscode-uri)
which notably doesn't have any limits of URI size, the renderer itself
relies on Web platform engine, that limits the length of the URLs and
bails out when the attribute length of an `href` inside `a` tag is too
long.

Command URIs have a form of `command:command-name?arguments`, where
`arguments` is a percent-encoded array of data we want to pass along to
the command function. For "Show References" this is a list of all file
URIs with locations of every reference, and it can get quite long.

This PR introduces another intermediary `linkToCommand` command. When
we render a command link, a reference to a command with all its arguments
is stored in a map, and instead a `linkToCommand` link is rendered
with the key to that map.

For now the map is cleaned up periodically (I've set it to every
10 minutes). In general case we'll probably need to introduce TTLs or
flags to denote ephemeral links (like these in hover popups) and
persistent links and clean those separately. But for now simply keeping
the last few links in the map should be good enough. Likewise, we could
add code to remove a target command from the map after the link is
clicked, but assuming most links in hover sheets won't be clicked anyway
this code won't change the overall memory use much.

Closes #9926

### CODE REVIEW

File: editors/code/src/client.ts [hunk 1]
```diff
@@ -7,14 +7,28 @@ import { WorkspaceEdit } from "vscode";
...
+import { randomUUID } from "crypto";
 
 export interface Env {
     [name: string]: string;
 }
 
-function renderCommand(cmd: ra.CommandLink) {
-    return `[${cmd.title}](command:${cmd.command}?${encodeURIComponent(
-        JSON.stringify(cmd.arguments)
+export const LINKED_COMMANDS = new Map<string, ra.CommandLink>();
```
Comment (jonas-schievink) [inline editors/code/src/client.ts:16]: I think it would be good to document this workaround in-tree, so could you copy part of the PR description here as an inline comment?

**Review by jonas-schievink — APPROVED** [review]
