### PR TITLE
handle {self} when removing unused imports

### LINKED ISSUE #17139: removing unused imports generates invalid `use module_name::self`
**rust-analyzer version**: rust-analyzer version: 0.3.1932-standalone (47a901b9b 2024-04-21)

**rustc version**: rustc 1.79.0-nightly (ef8b9dcf2 2024-04-24)

**editor or extension**: VScode v0.3.1932

**code snippet to reproduce**: 
```rust

mod inner {
    pub struct X();
    pub struct Y();
}

mod z {
    use super::inner::{self, X}$0;

    fn f() {
        let y = inner::Y();
    }
}

```

becomes

```
mod inner {
    pub struct X();
    pub struct Y();
}

mod z {
    use super::inner:self;

    fn f() {
        let y = inner::Y();
    }
}
```
which is invalid. It should be `use super::inner` instead.

### PR DESCRIPTION
**Pull request by harrysarson**
Fixes #17139 

On master

```rs
mod inner {
    pub struct X();
    pub struct Y();
}

mod z {
    use super::inner::{self, X}$0;

    fn f() {
        let y = inner::Y();
    }
}
```

becomes

```rs
mod inner {
    pub struct X();
    pub struct Y();
}

mod z {
    use super::inner:self;

    fn f() {
        let y = inner::Y();
    }
}
```

with this fix it instead becomes

```

```rs
mod inner {
    pub struct X();
    pub struct Y();
}

mod z {
    use super::inner;

    fn f() {
        let y = inner::Y();
    }
}
```

### CODE REVIEW

**Comment by Veykril** [comment]
That transform is generally not valid, `use foo::bar::{self}` imports only the type namespace, where as `use foo::bar;` imports value, type and macro namespace. So transforming like that can actually cause name collisions.

Now there is still a bug here in that we produce malformed syntax but we need to keep the braces.

File: crates/syntax/src/ast/node_ext.rs [hunk 1]
```diff
@@ -376,11 +376,24 @@ impl ast::UseTreeList {
             .filter_map(|it| it.into_token().filter(|it| it.kind() == T![,]))
     }
 
+    pub fn is_just_self(&self) -> bool {
+        if let Some((single_subtree,)) = self.use_trees().collect_tuple() {
+            fn path_is_self(path: &ast::Path) -> bool {
```
Comment (Veykril) [inline crates/syntax/src/ast/node_ext.rs:381]: This can be a closure

Comment (harrysarson) [reply crates/syntax/src/ast/node_ext.rs]: have made this into a closure

**Comment by harrysarson** [comment]
> That transform is generally not valid, 

The normalize import IDE assist (https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-assists/src/handlers/normalize_import.rs) does transform `{self}`. I.e. the following unit test would parse if added to normalize_import.rs

```rs

    #[test]
    fn test_collapses_self() {
        check_assist_variations!("std::fmt::{self}", "std::fmt");
    }
```

Is that a bug?

**Comment by Veykril** [comment]
Unless the assist there checks that `fmt` only refers to a type namespace there I'd consider that a bug

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
