### PR TITLE
fix: Wrong closure kind deduction for closures with predicates

### LINKED ISSUE #16421: False positive "cannot mutate immutable variable (E0384)" error
**rust-analyzer version**: 0.4.1816-standalone (d410d4a2b 2024-01-21)

**rustc version**: 1.77.0-nightly (d5fd09972 2024-01-22)

Code https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=143f7fbac71c9d440720ae04f8c9018c gives error `cannot mutate immutable variable f` at the line 21, but compiles fine in rustc.

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Completes #16472, fixes #16421

The changed closure kind deduction is mostly simlar to `rustc_hir_typeck/src/closure.rs`.
Porting closure sig deduction from it seems possible too and I'm considering doing it with another PR

### CODE REVIEW

File: crates/hir-ty/src/infer/unify.rs [hunk 1]
```diff
@@ -31,6 +32,72 @@ impl InferenceContext<'_> {
...
+        &mut self,
+        self_ty: InferenceVar,
+    ) -> SmallVec<[WhereClause; 4]> {
+        self.table.resolve_obligations_as_possible();
+
+        let root = self.table.var_unification_table.inference_var_root(self_ty);
+        let pending_obligations = mem::take(&mut self.table.pending_obligations);
+        let obligations = pending_obligations
+            .iter()
+            .filter_map(|obligation| match obligation.value.value.goal.data(Interner) {
```
Comment (Veykril) [inline crates/hir-ty/src/infer/unify.rs:46]: Could make use of https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain I think?

Comment (ShoyuVanilla) [reply crates/hir-ty/src/infer/unify.rs:46]: Since we are not mutating `obligations` - it should be returned to its original place `pending_obligations` - I think that to use `Vec::retain()`, we should clone the whole `obligations`

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
