### PR TITLE
fix: handle raw identifiers in move_module_to_file

### LINKED ISSUE #12045: Incorrect file name when extracting module whose name is a raw keyword.
E.g.

```
mod r#static {
}
```

When extracting this module to a file, rust-analyzer will name the file `r#static.rs`, instead of the correct `static.rs` .

### PR DESCRIPTION
**Pull request by lowr**
Fixes #12045 

Note that I special case'd mod named `r#mod` as commented in the code. Although it's very unlikely that one would use such name, I included it in this fix for the sake of completeness.

### CODE REVIEW

File: crates/ide_assists/src/handlers/move_module_to_file.rs [hunk 1]
```diff
@@ -58,9 +58,18 @@ pub(crate) fn move_module_to_file(acc: &mut Assists, ctx: &AssistContext) -> Opt
                 }
                 let segments = iter::successors(Some(module_ast.clone()), |module| module.parent())
                     .filter_map(|it| it.name())
+                    .map(|name| SmolStr::from(name.text().trim_start_matches("r#")))
```
Comment (lowr) [inline crates/ide_assists/src/handlers/move_module_to_file.rs:61]: I'm not sure if using `SmolStr` is appropriate here. I wanted to avoid copying strings but couldn't find any way to do so (correct me if I'm wrong but `SmolStr::from()` copies the source string right?).

Practically I don't think it'd cause major performance issues, though, as module names are usually not that long.

**Comment by jonas-schievink** [comment]
Thanks! @bors r+

File: crates/ide_assists/src/handlers/move_module_to_file.rs (hunk 1 above)
Comment (Veykril) [reply crates/ide_assists/src/handlers/move_module_to_file.rs:61]: Fwiw, SmolStr also allocates if the string is bigger than 15 characters, otherwise it's inline.

And yes, performance here does not matter that much since this is only executed when the assist is being executed.
