### PR TITLE
fix: Temporary fix for `remove_unused_imports` not handling import aliases correctly

### LINKED ISSUE #18129: "Remove all unused imports" code action incorrectly removes `as` aliased imports.
**rust-analyzer version**: 0.3.2112-standalone

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**editor or extension**: VScode - latest version (seems to be `v0.3.2112`)

**relevant settings**: None

**repository link (if public, optional)**: Irrelevant

**code snippet to reproduce**: 
```rust
// Any aliased import would really work.

use std::io::Error as IoError; // Here (read after code snippet)

fn main() -> Result<(), IoError> { // Any usage of the alias (it's now clearly used).
    Ok(())
}
```

Place your cursor at the marked spot in the code, click <kbd>ctrl + .</kbd> (or your keybind for code actions) and select "Remove all the unused imports".

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #18129

### CODE REVIEW

File: crates/ide-db/src/search.rs [hunk 1]
```diff
@@ -447,6 +449,11 @@ impl<'a> FindUsages<'a> {
         self
     }
 
+    pub fn with_rename(mut self, rename: Option<&'a Rename>) -> Self {
```
Comment (Veykril) [inline crates/ide-db/src/search.rs:452]: This should be a temporary thing. Ideally this would trivially fix itself once we handle renamed `use`s as proper `Definition`s

Comment (ShoyuVanilla) [reply crates/ide-db/src/search.rs:452]: Oh, that's right. This should be handled as TypeAlias, right? I'll add a comment and modify the commit and PR message
