### PR TITLE
fix: sort and deduplicate auto traits in trait object types

### LINKED ISSUE #12739: Error reported over different `Send` and `Sync` ordering
Hey, first issue over here! Thanks everyone for the hard work put into this tool!

I ran into a small issue where I get an error that the order of `Send + Sync` is 'wrong'. Here is an example error message:
```
expected &(dyn Fn(&GameType) -> ScoreType + Send + Sync), found &(dyn Fn(&GameType) -> ScoreType + Sync + Send)
```
image

Notice the only difference being the order of `Send` and `Sync` at the end of each type. This code compiles fine with rustc but rust-analyzer (via nvim for me) is showing this error. Changing the order of `Send` and `Sync` in my code, so each site matches, resolves the error.

Is this intended behavior or a bug?
I fixed my usage, as it makes sense for both sites to have the same ordering! But was midly surprised me that it showed an error, especially when rustc did not.

**Minimal Example**: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ac7efd618222cb33058c459d2d9b98de

**rust-analyzer version**: rust-analyzer 0.0.0 (5342f47f4 2022-07-09)
Also present on the latest (https://github.com/rust-lang/rust-analyzer/tree/2022-07-04) release, both downloaded from Github Releases for arm64 apple

**rustc version**: rustc 1.62.0 (a8314ef7d 2022-06-27)

**relevant settings**: None that I know of

### PR DESCRIPTION
**Pull request by lowr**
Fixes #12739

Chalk solver doesn't sort and deduplicate auto traits in trait object types, so we need to handle them ourselves in the lowering phase, just like [`rustc`](https://github.com/rust-lang/rust/blob/880416180b0a9ee1141c07d4d17667edb77daebd/compiler/rustc_typeck/src/astconv/mod.rs#L1487-L1488) and [`chalk-integration`](https://github.com/rust-lang/chalk/blob/master/chalk-integration/src/lowering.rs#L575) do.

Quoting from [the Chalk book](https://rust-lang.github.io/chalk/book/types/rust_types.html#dyn-types):

> Note that -- for this purpose -- ordering of bounds is significant. That means that if you create a `dyn Foo + Send` and a `dyn Send + Foo`, chalk would consider them distinct types. The assumption is that bounds are ordered in some canonical fashion somewhere else.

Also, trait object types with more than one non-auto traits were previously allowed, but are now disallowed with this patch.

### CODE REVIEW

File: crates/hir-ty/src/lower.rs [hunk 1]
```diff
@@ -969,13 +969,44 @@ impl<'a> TyLoweringContext<'a> {
...
+                } else {
+                    other_bounds.push(bound);
+                }
+            }
+
+            if regular_traits.len() > 1 {
+                return None;
+            }
+
+            auto_traits.sort_by_key(|b| b.trait_id().unwrap());
```
Comment (ChayimFriedman2) [inline crates/hir-ty/src/lower.rs:994]: Shouldn't `sort_unstable_by_key()` be preferred?

Comment (lowr) [reply crates/hir-ty/src/lower.rs:994]: Sounds right, we don't need stability here. Thanks for pointing out!

**Comment by Veykril** [comment]
Thanks!
@bors r+
