### PR TITLE
fix: Fix an incorrect `ExpressionStore` that was passed

### LINKED ISSUE #19561: thread 'Worker' panicked at crates\hir-ty\src\display.rs:2254:22:
```

thread 'Worker' panicked at crates\hir-ty\src\display.rs:2254:22:
index out of bounds: the len is 3 but the index is 3
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library\std\src\panicking.rs:695
   1: core::panicking::panic_fmt
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library\core\src\panicking.rs:75
   2: core::panicking::panic_bounds_check
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library\core\src\panicking.rs:273
   3: <hir_def::hir::type_ref::TypeBound as hir_ty::display::HirDisplayWithExpressionStore>::hir_fmt
   4: hir::display::write_where_predicates
   5: hir::display::<impl hir_ty::display::HirDisplay for hir::Function>::hir_fmt
   6: <hir_ty::display::HirDisplayWrapper<T> as core::fmt::Display>::fmt
   7: ide::hover::render::definition
   8: ide::hover::hover_for_definition
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  11: ide::hover::hover
  12: ide::hover::hover
  13: salsa::cancelled::Cancelled::catch
  14: ide::Analysis::hover
  15: rust_analyzer::handlers::request::handle_hover
  16: core::ops::function::FnOnce::call_once{{vtable.shim}}
```
Happened while I was hovering some type in a body. I imagine this is caused by my PR where we try to lookup a body type ref in a signature expression store

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
It caused panics everywhere.

Fixes rust-lang/rust-analyzer#19561.

### CODE REVIEW

File: crates/hir/src/display.rs [hunk 1]
```diff
@@ -178,7 +178,7 @@ impl HirDisplay for Function {
                 AssocItemContainer::Impl(_) => "impl",
             };
             write!(f, "\n    // Bounds from {container_name}:",)?;
-            write_where_predicates(&container_params, &data.store, f)?;
```
Comment (davidbarsky) [inline crates/hir/src/display.rs:181]: the type confusion here seems... suboptimal. can do this later, but would be nice to make this impossible to express in the future.

**Review by davidbarsky — APPROVED** [review]

File: crates/hir/src/display.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/hir/src/display.rs:181]: Unfortunately I don't see how. It's not even a confusion between a body and a signature store, it's between a signature store and the signature store of the container.
