### PR TITLE
fix: Insert `pub(crate)` after doc comments and attribute macros

### LINKED ISSUE #12790: Extract Module disorganizes doc comments and attribute macros
**rust-analyzer version**: v0.3.1123 VS Code Extension

**rustc version**: 1.61.0

**relevant settings**: N/A

rust-analyzer produces refactored code with syntax errors due to failing to preserve attribute macro and document comment positioning when adding `pub(crate)`

Examples:

Before: (Everything except for `fn main() {...}` is selected for extracting to module)
```rust
/// A documented function
fn documented_fn() {}

// A commented function with a #[] attribute macro
#[cfg(test)]
fn attribute_fn() {}

// A normally commented function
fn normal_fn() {}

/// A documented Struct
struct DocumentedStruct {
    // Normal field
    x: i32,

    /// Documented field
    y: i32,

    // Macroed field
    #[cfg(test)]
    z: i32,
}

// A macroed Struct
#[cfg(test)]
struct MacroedStruct {
    // Normal field
    x: i32,

    /// Documented field
    y: i32,

    // Macroed field
    #[cfg(test)]
    z: i32,
}

// A normal Struct
struct NormalStruct {
    // Normal field
    x: i32,

    /// Documented field
    y: i32,

    // Macroed field
    #[cfg(test)]
    z: i32,
}

fn main() {
    println!("Hello, world!");
}

```
After:
```rust
mod modname {
    pub(crate) /// A documented function
    fn documented_fn() {}

    pub(crate) // A commented function with a #[] attribute macro
    #[cfg(test)]
    fn attribute_fn() {}

    pub(crate) // A normally commented function
    fn normal_fn() {}

    pub(crate) /// A documented Struct
    struct DocumentedStruct {
        pub(crate) // Normal field
        x: i32,

        pub(crate) /// Documented field
        y: i32,

        pub(crate) // Macroed field
        #[cfg(test)]
        z: i32,
    }

    pub(crate) // A macroed Struct
    #[cfg(test)]
    struct MacroedStruct {
        pub(crate) // Normal field
        x: i32,

        pub(crate) /// Documented field
        y: i32,

        pub(crate) // Macroed field
        #[cfg(test)]
        z: i32,
    }

    pub(crate) // A normal Struct
    struct NormalStruct {
        pub(crate) // Normal field
        x: i32,

        pub(crate) /// Documented field
        y: i32,

        pub(crate) // Macroed field
        #[cfg(test)]
        z: i32,
    }
}

fn main() {
    println!("Hello, world!");
}

```

Expected:
```rust
mod modname {
    /// A documented function
    pub(crate) fn documented_fn() {}

    // A commented function with a #[] attribute macro
    #[cfg(test)]
    pub(crate) fn attribute_fn() {}

    // A normally commented function
    pub(crate) fn normal_fn() {}

    /// A documented Struct
    pub(crate) struct DocumentedStruct {
        // Normal field
        pub(crate) x: i32,

        /// Documented field
        pub(crate) y: i32,

        // Macroed field
        #[cfg(test)]
        pub(crate) z: i32,
    }

    // A macroed Struct
    #[cfg(test)]
    pub(crate) struct MacroedStruct {
        // Normal field
        pub(crate) x: i32,

        /// Documented field
        pub(crate) y: i32,

        // Macroed field
        #[cfg(test)]
        pub(crate) z: i32,
    }

    // A normal Struct
    pub(crate) struct NormalStruct {
        // Normal field
        pub(crate) x: i32,

        /// Documented field
        pub(crate) y: i32,

        // Macroed field
        #[cfg(test)]
        pub(crate) z: i32,
    }
}

fn main() {
    println!("Hello, world!");
}

```

### PR DESCRIPTION
**Pull request by TopGunSnake**
Fixes #12790 

Original behavior was to insert `pub(crate)` at the `first_child_or_token`, which for an item with a comment or attribute macro, would put the visibility marker before the comment or macro, instead of after.

This merge request alters the call to find the node with appropriate `SyntaxKind` in the `children_or_tokens`. It also adds a test case to the module to verify the behavior. Test case verifies function, module, records, enum, impl, trait, and type cases.

### CODE REVIEW

**Comment by TopGunSnake** [comment]
Need verification that the cases added are sufficient for all known cases to add a `pub(crate)`.

File: crates/ide-assists/src/handlers/extract_module.rs [hunk 1]
```diff
@@ -380,7 +380,25 @@ impl Module {
...
+                    | SyntaxKind::CONST_KW
+                    | SyntaxKind::MOD_KW => true,
+                    // If we didn't find a keyword, we want to cover the record fields in a struct
+                    SyntaxKind::NAME => true,
+                    // Otherwise, the token shouldn't have pub(crate) before it
+                    _ => false,
+                }
+            });
+
+            add_change_vis(vis, item);
```
Comment (Veykril) [inline crates/ide-assists/src/handlers/extract_module.rs:401]: This logic seems inverted to me, we should pick the first token that is NOT a comment or attribute, so we should skip `SyntaxKind::COMMENT`, `SyntaxKind::ATTR` and (I think also) `SyntaxKind::WHITESPACE` and pick the first thing that is not one of those 3. That way we don't have to explicitly list the things that we expect should be there at the start.

Comment (TopGunSnake) [reply crates/ide-assists/src/handlers/extract_module.rs]: I agree, realized a few cases this already didn't cover, such as `async`, `extern`, and `union`. Explicitly skipping these three kinds works for the tests in extract_module.rs.

**Comment by Veykril** [comment]
Thanks!
@bors r+
