### PR TITLE
fix: incorrect file_id used for ranges in outgoing calls

### LINKED ISSUE #18800: thread 'Worker' panicked with `invalid offset` when `show outgoing call`
**rust-analyzer version**: 0.3.2237-standalone (59bc7b49d0 2024-12-29) 

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: VSCode

**code snippet to reproduce**: 
```rust
fn main() {
    let a  = Some(5).take();
    //               ^^^^  invoke outgoing call on take
}
```
```
thread 'Worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\line-index-0.1.2\src/lib.rs:111:35:
invalid offset
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: core::panicking::panic_display
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:264
   3: core::option::expect_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\option.rs:2021
   4: rust_analyzer::lsp::to_proto::range
   5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: rust_analyzer::handlers::request::handle_call_hierarchy_outgoing
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

### PR DESCRIPTION
**Pull request by roife**
fix #18800

https://github.com/rust-lang/rust-analyzer/blob/dae15045a76ec3d7d98901cbb2bcfeafbd96c80b/crates/ide/src/call_hierarchy.rs#L16-L20

Here `target` refers to the definition of the fn which is called, while `ranges` indicates the location of the call site.

For example:

```
fn f() {
    g(); // ranges[0]
}

// another file
fn g() {} // target
```

### CODE REVIEW

File: crates/rust-analyzer/src/handlers/request.rs [hunk 1]
```diff
@@ -1846,7 +1844,10 @@ pub(crate) fn handle_call_hierarchy_outgoing(
                 .into_iter()
                 // This is the range relative to the caller
                 .filter(|it| it.file_id == fpos.file_id)
-                .map(|it| to_proto::range(&line_index, it.range))
+                .filter_map(|it| {
+                    let line_index = snap.file_line_index(it.file_id).ok()?;
```
Comment (Veykril) [inline crates/rust-analyzer/src/handlers/request.rs:1848]: This is always the file index for `fpos.file_id` so we can just hoist this out of the for loop `let line_index = snap.file_line_index(fpos.file_id)`

Comment (roife) [reply crates/rust-analyzer/src/handlers/request.rs]: I didn't notice that we had filtered out other files.

**Review by Veykril — APPROVED** [review]
