### PR TITLE
Fix render of literal to be rendered in codeblock

### LINKED ISSUE #18765: Quote or escape the raw string correctly in popup
Currently, the popup for raw string syntax uses the following code:

https://github.com/rust-lang/rust-analyzer/blob/1ce4de2585cb9802c4d5a99d1a904b11fdba9501/crates/ide/src/hover/render.rs#L709-L713

So `r#"A "quoted" string"#` will be rendered like this:

> value of literal: A "quoted" string

Image

However, when the code contains special characters in Markdown like `*` (which is common in regex), the popup is messed up.

For example, `r".*regex.*"` became:

> value of literal: .*regex.*

Image

With a proper quotation or escaping, this could be rendered as:

> value of literal: `.*regex.*`

> value of literal: .\*regex.\*  (Less preferable, since leading and trailing spaces are hard to distinguish.)

### PR DESCRIPTION
**Pull request by dfireBird**
Fixes #18765.

Chose this approach to simplify finding the needed n back ticks, instead of finding the consecutive back ticks. 
Tested for about 100 consecutive back ticks, it was working fine. 

Regarding tests, I'll add some soon. Just wanted to review the implementation.

### CODE REVIEW

File: crates/ide/src/hover/render.rs [hunk 1]
```diff
@@ -715,10 +715,17 @@ pub(super) fn literal(
...
             if let Some(newline) = value.find('\n') {
-                format_to!(s, "value of literal (truncated up to newline): {}", &value[..newline])
+                format_to!(
+                    s,
+                    "value of literal (truncated up to newline): {backticks} {} {backticks}",
+                    &value[..newline]
+                )
             } else {
-                format_to!(s, "value of literal: {value}")
+                format_to!(s, "value of literal: {backticks} {value} {backticks}")
```
Comment (Veykril) [inline crates/ide/src/hover/render.rs:728]:
```suggestion
                format_to!(s, "value of literal: {backticks}{value}{backticks}")
```

Comment (Veykril) [reply crates/ide/src/hover/render.rs:728]: Ah wait I just realized this is allowed by the spec (and required to quote a backtick) nvm

**Review by Veykril — APPROVED** [review]

File: crates/ide/src/hover/render.rs (hunk 1 above)
Comment (dfireBird) [reply crates/ide/src/hover/render.rs:728]: I forgot to mention in the PR initial comment, the space is needed, otherwise single back tick or back tick at last position will mess the formatting

**Comment by dfireBird** [comment]
Added tests as part of same commit, they basically test the number of back ticks that is before and after. Nothing much can be done apart from that I guess.

**Comment by Jisu-Woniu** [comment]
What if the string consists entirely of space characters?

> If the resulting string both begins and ends with a [space](https://spec.commonmark.org/0.31.2/#space) character, but does not consist entirely of [space](https://spec.commonmark.org/0.31.2/#space) characters, a single [space](https://spec.commonmark.org/0.31.2/#space) character is removed from the front and back.

e.g.

```markdown
`  `   (the rendered form of an empty string)
`   `  (the rendered form of string " ", or 1 space)
```

will become 

`  ` (2 spaces) and `   ` (3 spaces)

**Comment by Veykril** [comment]
Ah indeed, fully whitespace strings we need to special case thats a good point!

**Comment by dfireBird** [comment]
We should do that, but fun thing in vscode hover renderer trims all leading and trailing spaces inside codeblock. Like even with current implementation hovering over something like `r" hello "` will only render `hello`

**Comment by Veykril** [comment]
That is unfortunate but not much we can do about then I think, ultimately markdown rendering differs from implementation to implementation. We could note down the number of leading / trailing whitespace in parenthesis after I suppose (if there are any)

**Comment by Jisu-Woniu** [comment]
Is it possible to use `<code>` `</code>` to wrap the values instead?

**Comment by dfireBird** [comment]
From my research about it, VSC only allows `<span></span` by default and others are sanitized. There is user config that can control it, but I'm not sure if that can be used here.
