### PR TITLE
fix: fix ambigious package name in flycheck

### LINKED ISSUE #18121: cargo check -p fails with ambiguous package names
**rust-analyzer version**: 0.3.2112-standalone

**rustc version**: rustc 1.79.0-nightly (244da22fa 2024-04-23)

**editor or extension**: VSCode

**relevant settings**: None

**repository link (if public, optional)**: https://github.com/benjamin-lieser/rand/tree/cdf_testing

I get the following error message:
```
2024-09-16T13:22:58.748136Z ERROR Flycheck failed to run the following command: CommandHandle { program: "/home/benjamin/.cargo/bin/cargo", arguments: ["check", "-p", "rand_distr", "--test", "cdf", "--message-format=json-diagnostic-rendered-ansi", "--manifest-path", "/home/benjamin/git/myrand/Cargo.toml", "--keep-going", "--all-targets"], current_dir: Some("/home/benjamin/git/myrand") }, error=Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
error: There are multiple `rand_distr` packages in your project, and the specification `rand_distr` is ambiguous.
Please re-run this command with one of the following specifications:
  rand_distr@0.4.3
  rand_distr@0.5.0-alpha.1
```

The package `rand_distr` is there in version 0.5.0-alpha.1 and in version 0.4.3 inside the dependency tree.
I guess this is related to [#3781](https://github.com/rust-lang/rust-analyzer/pull/3781)

Running the tests from VS code works fine, it executes `cargo test --package rand_distr:0.5.0-alpha.1 --test cdf -- normal --exact --show-output`

### PR DESCRIPTION
**Pull request by jhgg**
fixes #18121

### CODE REVIEW

File: crates/rust-analyzer/src/handlers/notification.rs [hunk 1]
```diff
@@ -357,7 +357,7 @@ fn run_flycheck(state: &mut GlobalState, vfs_path: VfsPath) -> bool {
                             .targets
                             .iter()
                             .any(|&it| crate_root_paths.contains(&cargo[it].root.as_path()));
-                        has_target_with_root.then(|| cargo[pkg].name.clone())
+                        has_target_with_root.then(|| cargo.package_flag(&cargo[pkg]))
```
Comment (Veykril) [inline crates/rust-analyzer/src/handlers/notification.rs:360]: Why are we calling this `package_flag`? That feels like the wrong name for what this does

**Review by Veykril — APPROVED** [review]
