### PR TITLE
internal: Upgrade to the next Salsa

### LINKED ISSUE #19455: Wrong lifetime variance in hover for recursive types
**rust-analyzer version**: `rust-analyzer version: 0.3.2353-standalone (37acea8052 2025-03-23)`

**rustc version**: `rustc 1.84.1 (e71f9a9a9 2025-01-27)`

**editor or extension**: VSCode with rust-analyzer version `0.3.2353`

**code snippet to reproduce**: 
```rust
use std::cell::RefCell;

/// This type is covariant:
/// ```
/// use rust_playground::lifetimes::Recursive;
/// fn is_covariant<'long, 'short>(value: Recursive<'long>)
/// where
///     'long: 'short,
/// {
///     let _: Recursive<'short> = value;
/// }
/// ```
/// and not contravariant:
/// ```compile_fail
/// use rust_playground::lifetimes::Recursive;
/// fn is_contravariant<'long, 'short>(value: Recursive<'short>)
/// where
///     'long: 'short,
/// {
///     let _: Recursive<'long> = value;
/// }
/// ```
pub struct Recursive<'a> {
    v: &'a i32,
    parent: Option<Box<Recursive<'a>>>,
}

/// This type is not covariant:
/// ```compile_fail
/// use rust_playground::lifetimes::Recursive1;
/// fn is_covariant<'long, 'short>(value: Recursive1<'long>)
/// where
///     'long: 'short,
/// {
///     let _: Recursive1<'short> = value;
/// }
/// ```
/// and not contravariant
/// ```compile_fail
/// use rust_playground::lifetimes::Recursive1;
/// fn is_contravariant<'long, 'short>(value: Recursive1<'short>)
/// where
///     'long: 'short,
/// {
///     let _: Recursive1<'long> = value;
/// }
/// ```
/// i.e. it is invariant
pub struct Recursive1<'a>(&'a i32, Option<Box<Recursive2<'a>>>);
pub struct Recursive2<'a>(RefCell<Recursive1<'a>>);
```
For all three defined structs if I hover over the `'a` parameter in VSCode it shows me `bivariant` although `Recursive` is covariant and `Recursive1` and `Recursive2` are invariant over `'a`.

This gets worse if for example the invariant structs are used together with other covariant types for example:
```
pub struct Mixed<'a>(&'a i32, Recursive1<'a>);
```

In this case when I hover over it, it shows `covariant` although in fact it is invariant.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
This depends on Salsa from GitHub; should maybe wait until there is a release.

Fixes rust-lang/rust-analyzer#19455.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
It'll be better if you could also insert https://github.com/salsa-rs/salsa/pull/803 into it :)

**Comment by Veykril** [comment]
Alright can you verify things work with latest salsa master? If yes I'll cut a release there

**Comment by ChayimFriedman2** [comment]
Just checked - it's work fine! 🚀

**Comment by Veykril** [comment]
0.20.0 released

File: crates/hir-ty/src/mapping.rs [hunk 1]
```diff
@@ -136,7 +136,8 @@ pub fn from_assoc_type_id(id: AssocTypeId) -> TypeAliasId {
 
 pub fn from_placeholder_idx(db: &dyn HirDatabase, idx: PlaceholderIndex) -> TypeOrConstParamId {
     assert_eq!(idx.ui, chalk_ir::UniverseIndex::ROOT);
-    let interned_id = FromId::from_id(Id::from_u32(idx.idx.try_into().unwrap()));
+    // SAFETY: We cannot really encapsulate this unfortunately, so just hope this is sound.
+    let interned_id = FromId::from_id(unsafe { Id::from_u32(idx.idx.try_into().unwrap()) });
```
Comment (Veykril) [inline crates/hir-ty/src/mapping.rs:140]: This is really fishy in general I have to say, salsa even seems to allocate its own `PlaceholderIndex`es so we just gotta hope those don't ever leak out of it 😅 

(this was kind of unsound already etiher way)

Hopefully whatever the new trait solver does allows us to get rid of this weird interning here.

File: crates/span/src/hygiene.rs [hunk 2]
```diff
@@ -27,7 +27,10 @@ use crate::Edition;
 #[cfg(feature = "salsa")]
 #[derive(Copy, Clone, PartialEq, PartialOrd, Eq, Ord, Hash)]
 pub struct SyntaxContext(
-    salsa::Id,
+    /// # Invariant
+    ///
+    /// This is either a valid `salsa::Id` or a root `SyntaxContext`.
+    u32,
```
Comment (Veykril) [inline crates/span/src/hygiene.rs:33]: Why do we need this change? Ideally in the future we will be able to use the salsa macros to define the type here and then this change is moot.

File: crates/hir-ty/src/mapping.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/hir-ty/src/mapping.rs:140]: > salsa even seems to allocate its own `PlaceholderIndex`es

You mean Chalk?

Comment (Veykril) [reply crates/hir-ty/src/mapping.rs:140]: Yes

Comment (ChayimFriedman2) [reply crates/hir-ty/src/mapping.rs:140]: In general I'm not sure how unsafe using an incorrect Id is; it should not cause UB because you can safely create an `Id` then use it on a different database.

File: crates/span/src/hygiene.rs (hunk 2 above)
Comment (ChayimFriedman2) [reply crates/span/src/hygiene.rs:33]: I did it in order to encapsulate the unsafety of creating an `Id` well; previously it was already an `Id` and you could just hope nobody will ever use it incorrectly if it's a root `SyntaxContext` (that isn't really an `Id`), now the conversion to `Id` checks if it is a root.

If/when we convert this to Salsa macros this can go.

**Review by Veykril — APPROVED** [review]

**Comment by ChayimFriedman2** [comment]
Okay. Rebased and changed to use Salsa from crates.io.
