### PR TITLE
fix: handle character boundary in search mode

### LINKED ISSUE #18918: Bug Report: Panic When Using Japanese Function Names in Rust Analyzer(boundary issue)
**rust-analyzer version**: 0.3.2257-standalone

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: VSCode

# Code Snippet to Reproduce
```rust
fn main() {
    あ // Typing "あ" here causes a panic.
}

fn あい() {}
```

# Expected Behavior
Rust Analyzer should handle the input without errors.

# Actual Behavior
Rust Analyzer panics with the following error message:

```
Panic context:
> 
version: 0.3.2257-standalone
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/kazune/workspace/hoge/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 1,
            character: 5,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at crates/hir-def/src/import_map.rs:323:41:
byte index 1 is not a char boundary; it is inside 'あ' (bytes 0..3) of `あい`
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
   4: hir_def::import_map::SearchMode::check
   5: ide_db::symbol_index::Query::search_maps
   6: ide_db::items_locator::items_with_name
   7: ide_db::imports::import_assets::ImportAssets::search_for
   8: ide_db::imports::import_assets::ImportAssets::search_for_imports
   9: ide_completion::completions::flyimport::import_on_the_fly_path
  10: ide_completion::completions::complete_name_ref
  11: ide_completion::completions
  12: ide::Analysis::completions
  13: rust_analyzer::handlers::request::handle_completion
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:10:50 AM] Request textDocument/completion failed.
  Message: request handler panicked: byte index 1 is not a char boundary; it is inside 'あ' (bytes 0..3) of `あい`
  Code: -32603
```

# Additional Information
The error appears to be related to how Rust Analyzer handles Unicode input, specifically in the context of Japanese characters. The error suggests a boundary issue with UTF-8 characters.

Please let me know if further details or logs are needed. Thank you for your support!

### PR DESCRIPTION
**Pull request by roife**
fix #18918 

I also used Clippy to scan and check usages of slicing in the project, and found that only here could cause a panic.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
There is another slicing that looks like it may panic in line 305 (`let prefix = &candidate[..query.len()];`).

But do you know why it panics? We use `match_indices()`, it should return a correct index.

File: crates/hir-def/src/import_map.rs [hunk 1]
```diff
@@ -320,7 +320,7 @@ impl SearchMode {
                     };
                     match m {
                         Some((index, _)) => {
-                            name = &name[index + 1..];
+                            name = &name[ceil_char_boundary(name, index + 1)..];
```
Comment (Veykril) [inline crates/hir-def/src/import_map.rs:323]: Given we want to discard the string up to (and including, hence the + 1) the `query_char`, I think we can just do
```rs
let mut chars = name[index..].chars();
chars.next();
chars.as_str()
```
instead?

Comment (Veykril) [reply crates/hir-def/src/import_map.rs:323]: Or
```rs
name = name[index..].strip_prefix(|_: char| true).unwrap_or_default()
```

**Comment by Veykril** [comment]
> But do you know why it panics? We use `match_indices()`, it should return a correct index.

We panic because we slice one byte after the character, so if the character is multi byte we slice into it instead of beyond it.

**Comment by ChayimFriedman2** [comment]
> > There is another slicing that looks like it may panic in line 305 (`let prefix = &candidate[..query.len()];`).
> 
> That one shouldn't cause issues, given the searcher in that mode does a prefix search and so the prefix should match fully (it would be a bug if not)

But it might not match.

**Comment by Veykril** [comment]
Then we shouldn't even reach that far, the fst automaton should only give us prefix matches, the only thing that can differ at that point is the ascii casing which will not cause issues here. (if we were doing general casing changes it might)
