### PR TITLE
fix: Dont assume ascii in remove_markdown

### LINKED ISSUE #16142: Panic when calling `ra_ap_ide::Analysis::hover`
I am writing a program that uses rust analyzer ide crate version `0.0.190`. While testing on `bytes-1.5.0` crate, I always get a panic when trying to get hovers for `bytes-1.5.0/src/bytes.rs Position 99:11` (position is zero based).

My program uses the `StaticIndex::compute()` function to compute the static index and then traverses the token to generate the needed output.

The `HoverConfig` I am providing is:
```rust
            ra_ap_ide::HoverConfig {
                links_in_hover: false,
                memory_layout: Some(ra_ap_ide::MemoryLayoutHoverConfig {
                    size: Some(ra_ap_ide::MemoryLayoutHoverRenderKind::Decimal),
                    offset: Some(ra_ap_ide::MemoryLayoutHoverRenderKind::Hexadecimal),
                    alignment: Some(ra_ap_ide::MemoryLayoutHoverRenderKind::Hexadecimal),
                    niches: false,
                }),
                documentation: true,
                keywords: true,
                format: ra_ap_ide::HoverDocFormat::PlainText,
            },
```

Backtrace:
```rust
thread 'main' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/string.rs:1713:9:
assertion failed: self.is_char_boundary(start)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
   3: alloc::string::String::drain
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/string.rs:1713:9
   4: ra_ap_ide::markdown_remove::remove_markdown
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_ide-0.0.190/src/markdown_remove.rs:29:9
   5: ra_ap_ide::hover::hover
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_ide-0.0.190/src/hover.rs:118:27
   6: ra_ap_ide::Analysis::hover::{{closure}}
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_ide-0.0.190/src/lib.rs:470:27
   7: ra_ap_ide::Analysis::with_db::{{closure}}
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_ide-0.0.190/src/lib.rs:758:29
   8: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
   9: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  10: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  11: salsa::Cancelled::catch
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rust-analyzer-salsa-0.17.0-pre.4/src/lib.rs:626:15
  12: ra_ap_ide::Analysis::with_db
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_ide-0.0.190/src/lib.rs:758:9
  13: ra_ap_ide::Analysis::hover
             at /home/waqar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra_ap_ide-0.0.190/src/lib.rs:470:14
  14: codebrowser_rust_generator::CodeBrowser::get_hover
             at ./src/main.rs:247:30
```

**rustc version**: rustc 1.74.1 (a28077b28 2023-12-04)

### PR DESCRIPTION
**Pull request by Waqar144**
Fixes #16142

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

File: crates/ide/src/markdown_remove.rs [hunk 1]
```diff
@@ -25,7 +25,10 @@ pub(crate) fn remove_markdown(markdown: &str) -> String {
         }
     }
 
-    if let Some(p) = out.rfind(|c| c != '\n') {
+    if let Some(mut p) = out.rfind(|c| c != '\n') {
+        while !out.is_char_boundary(p + 1) {
+            p += 1;
+        }
         out.drain(p + 1..);
```
Comment (lnicola) [inline crates/ide/src/markdown_remove.rs:32]: I wonder if there's any reason for `drain` vs. `truncate` here.
