### PR TITLE
Purge of unwraps

### LINKED ISSUE #15176: Assists are broken
Since today I am unable to use any of our assists, none of them trigger (except for diagnostic quickfixes)

### PR DESCRIPTION
**Pull request by alibektas**
Removes unnecessary unwraps that I have overlooked in #15101 ( fixes #15176 )

### CODE REVIEW

File: crates/rust-analyzer/src/handlers/request.rs [hunk 1]
```diff
@@ -2039,20 +2039,19 @@ fn to_url(path: VfsPath) -> Option<Url> {
...
+            .caps()
+            .workspace
+            .as_ref()?
+            .workspace_edit
+            .as_ref()?
+            .resource_operations
+            .as_ref()
+    })();
+
+    if resops.is_none() || !resops.unwrap().contains(&kind) {
```
Comment (Veykril) [inline crates/rust-analyzer/src/handlers/request.rs:2054]:
```suggestion
    if !matches!(resops, Some(resops) if resops.contains(&kind)) {
```
