### PR TITLE
fix: filter unnecessary completions after colon

### LINKED ISSUE #13597: Completions on single colons
We seem to calculate completions for single colons of paths, we clearly shouldn't do that.

```rs
:$0 // shows completions
ResolvedThing:$0 // shows completions
UnresolvedThing:$0 // shows completions
```

### PR DESCRIPTION
**Pull request by yue4u**
close #13597
related: #10173

This PR also happens to fix two extra issues:

1. The test case in https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/tests/attribute.rs#L778-L801 was never triggered in previous behavior.

after:

https://user-images.githubusercontent.com/26110087/201476995-56adf955-0fa7-4f75-ab32-28a8e6cb9504.mp4

<del>
2. completions were triggered even in invalid paths, like

```rust
fn main() {
    core:::::$0
}
```

```rust
#[:::::$0]
struct X;
```

</del>

only `:::` is excluded as discussed in https://github.com/rust-lang/rust-analyzer/pull/13611#discussion_r1031845205

### CODE REVIEW

File: crates/ide-completion/src/tests/special.rs [hunk 1]
```diff
@@ -893,3 +902,89 @@ fn f() {
         "#]],
     );
 }
+
```
Comment (yue4u) [inline crates/ide-completion/src/tests/special.rs:905]: not sure if putting tests here (special.rs) is better than https://github.com/rust-lang/rust-analyzer/blob/45ec315e01dc8dd1146dfeb65f0ef6e5c2efed78/crates/ide-completion/src/tests.rs

File: crates/ide-completion/src/context.rs [hunk 2]
```diff
@@ -569,6 +569,28 @@ impl<'a> CompletionContext<'a> {
...
+
+                // only has a single colon
+                if prev_token.kind() != T![:] {
+                    return None;
+                }
+
+                if !is_prev_token_valid_path_start_or_segment(&prev_token) {
+                    return None;
+                }
+            }
```
Comment (Veykril) [inline crates/ide-completion/src/context.rs:587]: I think we can just return None if we find a `T![:]` without any additional checks? The previous token can't be another `T![:]` as the parser should produce a `T![::]` then I think?

File: crates/ide-completion/src/context.rs [hunk 3]
```diff
@@ -569,6 +569,28 @@ impl<'a> CompletionContext<'a> {
...
+            T![::] if !is_prev_token_valid_path_start_or_segment(&original_token) => {
```
Comment (Veykril) [inline crates/ide-completion/src/context.rs:588]: I don't think we need to check for the `is_prev_token_valid_path_start_or_segment` stuff, `::` can follow a lot of different characters just fine, `}::` for example works, in whic hcase it just starts an absolute path.

**Review by Veykril — COMMENTED** [review]
Apologies, I thought I had already reviewed this last week

File: crates/ide-completion/src/context.rs (hunk 2 above)
Comment (yue4u) [reply crates/ide-completion/src/context.rs:587]: Parser will produce two continuous `T![:]` if we are inside token streams and that's the case I wanted to support as the video in the description.

Comment (yue4u) [reply crates/ide-completion/src/context.rs:587]: However that will produce too much noise if we are accidentally typing like `:::`. Every single `:` after will trigger the completion again. So I introduced `is_prev_token_valid_path_start_or_segment` to solve that. I know it's invalid input but felt this behavior pretty annoying during testing without the check.

File: crates/ide-completion/src/context.rs (hunk 3 above)
Comment (yue4u) [reply crates/ide-completion/src/context.rs:588]: This check is similar for the case in https://github.com/rust-lang/rust-analyzer/pull/13611#discussion_r1027110327 but happens less frequently. As you pointed out current check is insufficient so it's seems better to just remove this one.

**Comment by yue4u** [comment]
I removed the check before `::` in [7a568f7](https://github.com/rust-lang/rust-analyzer/pull/13611/commits/7a568f7f9571c2c93fd8e60712878736d942c787) but still not sure about https://github.com/rust-lang/rust-analyzer/pull/13611#discussion_r1027087278
1. if we don't bother completing inside token tree then it's ok to remove the checking (same as current behavior)
2. if we want to completing inside token tree
    1. I think it's better to deal with the `:::` case but it's not necessary
    2. more invalid completions might be triggered than before

File: crates/ide-completion/src/context.rs (hunk 2 above)
Comment (Veykril) [reply crates/ide-completion/src/context.rs:587]: Oh I see, ye then we need something like that here. Though I think this is still too restrictive, so maybe let's instead check that we either have a `::`, or exactly two `:` tokens in a row (but not three)? I think that's a decent trade off unless I am missing something else.

Comment (yue4u) [reply crates/ide-completion/src/context.rs]: updated in b701b14ca5b195fd6e227b913a912a4fcc87efb0

File: crates/ide-completion/src/tests/special.rs [hunk 4]
```diff
@@ -967,16 +967,10 @@ fn foo { crate:$0 }
...
+fn no_completions_in_after_tripple_colon() {
     check(
         r#"
 fn foo { crate:::$0 }
-"#,
-        expect![""],
-    );
-    check(
-        r#"
-fn foo { crate::::$0 }
```
Comment (Veykril) [inline crates/ide-completion/src/tests/special.rs]: Ah wait, we no longer catch this because the token here is a `::` again right? Let's add that to the check as well as it is simple, I forgot that :) That is, `t.kind() == T![:] || t.kind() == T![::]` for the previous token check

Comment (yue4u) [reply crates/ide-completion/src/tests/special.rs]: done 1ca5cb7ed9928fad4222cb26727da41ff9ac148f
