### PR TITLE
fix: completion detail shows `{unknown}` for async functions and for RPITs

### LINKED ISSUE #11438: completion detail always renders {unknown} for return type from async fn.
while working on #11437 i noticed that async fn's return type renders as `{unknown}`  in completion detail:

take this minimal repro:

```rust
async fn returns_a_string() -> String {
    todo!()
}

fn main() {
    returns_a_$0
}
```
image

### PR DESCRIPTION
**Pull request by iDawer**
Fix: completion detail shows `{unknown}` for `impl Trait` in return position.
Fix #11438 : completion detail shows `{unknown}` for return types in async functions.

#### API changes
Add `hir::Function::async_ret_type` method

### CODE REVIEW

File: crates/ide_completion/src/render/function.rs [hunk 1]
```diff
@@ -228,7 +228,7 @@ fn should_add_parens(ctx: &CompletionContext) -> bool {
 }
 
 fn detail(db: &dyn HirDatabase, func: hir::Function) -> String {
-    let ret_ty = func.ret_type(db);
+    let ret_ty = func.async_ret_type(db).unwrap_or_else(|| func.ret_type(db));
```
Comment (lnicola) [inline crates/ide_completion/src/render/function.rs:231]: Nit: I think this would be clearer with the `is_async` check pulled outside, but it doesn't matter too much.

Comment (iDawer) [reply crates/ide_completion/src/render/function.rs]: Done! I also left that check inside `hir::Function::async_ret_type` in case someone misuse it on `impl AnyOtherTrait` types

**Comment by Veykril** [comment]
meh, you gotta type it out on this one

@bors delegate+
