### PR TITLE
fix: try to infer array type from slice pattern

### LINKED ISSUE #16609: Inference failure since slice patterns does not serve as type expections
Types of `a` and `b` in this code below cannot be inferred by rust-analyzer, but it compiles fine with rustc.
```rust
// edition = "2021"
fn main() {
    let [a, b] = vec![1u32, 2u32].try_into().unwrap();
    //   ^ {unknown}
}
```

**rust-analyzer version**: 2024-02-19

**rustc version**: rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: N/A

### PR DESCRIPTION
**Pull request by alibektas**
fixes #16609

### CODE REVIEW

File: crates/hir-ty/src/infer/pat.rs [hunk 1]
```diff
@@ -553,6 +581,63 @@ impl InferenceContext<'_> {
...
+            consteval::usize_const(self.db, Some(len as u128), self.owner.krate(self.db.upcast()));
+
+        let elem_ty = self.table.new_type_var();
+        let array_ty = TyKind::Array(elem_ty.clone(), size).intern(Interner);
+        Some(array_ty)
+    }
+
+    /// Determines whether we can infer the expected type in the slice pattern to be of type array.
+    /// This is only possible if we're in an irrefutable pattern. If we were to allow this in refutable
+    /// patterns we wouldn't e.g. report ambiguity in the following situation:
```
Comment (ChayimFriedman2) [inline crates/hir-ty/src/infer/pat.rs:606]: The compiler doesn't report ambiguity (https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=574bb654d0bd9905773ec8a82246c446), are you sure this logic is correct?

File: crates/hir-ty/src/infer/pat.rs [hunk 2]
```diff
@@ -478,14 +492,28 @@ impl InferenceContext<'_> {
...
         suffix: &[PatId],
         default_bm: BindingMode,
+        decl: Option<DeclContext>,
     ) -> Ty {
+        let expected = self.resolve_ty_shallow(expected);
+
+        // If `expected` is an infer ty, we try to equate it to an array if the given pattern
+        // allows it. See issue #16609
+        if self.decl_allows_array_type_infer(decl) && expected.is_ty_var() {
+            if let Some(resolved_array_ty) =
```
Comment (ChayimFriedman2) [inline crates/hir-ty/src/infer/pat.rs:502]: We shouldn't do this if there is a rest pattern.

File: crates/hir-ty/src/infer/pat.rs [hunk 3]
```diff
@@ -553,6 +581,63 @@ impl InferenceContext<'_> {
...
+    /// ```
+    ///
+    /// If we're in an irrefutable pattern we prefer the array impl candidate given that
+    /// the slice impl candidate would be be rejected anyway (if no ambiguity existed).
+    fn decl_allows_array_type_infer(&self, decl_ctxt: Option<DeclContext>) -> bool {
+        if let Some(decl_ctxt) = decl_ctxt {
+            !decl_ctxt.has_else && matches!(decl_ctxt.origin, DeclOrigin::LocalDecl)
+        } else {
+            false
+        }
```
Comment (Veykril) [inline crates/hir-ty/src/infer/pat.rs:639]:
```suggestion
        matches!(decl_ctxt, Some(DeclContext { origin: DeclOrigin::LocalDecl, has_else: true})
```

File: crates/hir-ty/src/infer/pat.rs (hunk 1 above)
Comment (Veykril) [reply crates/hir-ty/src/infer/pat.rs:606]: That's copied from the corresponding rustc PR, though not sure why the text wasnt just copied verbatim https://github.com/rust-lang/rust/pull/113199/files#diff-9f26e4ec8d6ac64edbb3532a590592556b268b0e33f9fd4264d5d449aebbecf7R2061-R2090

File: crates/hir-ty/src/lib.rs [hunk 4]
```diff
@@ -1049,3 +1049,24 @@ pub fn known_const_to_ast(
...
     Some(make::expr_const_value(konst.display(db, edition).to_string().as_str()))
 }
+
+#[derive(Debug, Copy, Clone)]
+pub(crate) enum DeclOrigin {
+    // from an `if let` expression
+    // Due to the limited use of `DeclOrigin` it has so far been
+    // necessary to have the `LetExpr` variant. However, to have the
+    // identical struct to its rustc counterpart, we keep this variant here.
+    // LetExpr,
```
Comment (Veykril) [inline crates/hir-ty/src/lib.rs:1059]: This comment makes no sense to me at all

File: crates/hir-ty/src/lib.rs [hunk 5]
```diff
@@ -1049,3 +1049,24 @@ pub fn known_const_to_ast(
...
+    LocalDecl,
+}
+
+/// Provides context for checking patterns in declarations. More specifically this
+/// allows us to infer array types if the pattern is irrefutable and allows us to infer
+/// the size of the array. See issue #76342.
+#[derive(Debug, Copy, Clone)]
+pub(crate) struct DeclContext {
+    // whether we're in a let-else context
+    pub(crate) has_else: bool,
```
Comment (Veykril) [inline crates/hir-ty/src/lib.rs:1070]: This should really be encoded in `DeclOrigin::LocalDecl { has_else: bool }`

File: crates/hir-ty/src/lib.rs [hunk 6]
```diff
@@ -1049,3 +1049,24 @@ pub fn known_const_to_ast(
...
+    // necessary to have the `LetExpr` variant. However, to have the
+    // identical struct to its rustc counterpart, we keep this variant here.
+    // LetExpr,
+    /// from `let x = ..`
+    LocalDecl,
+}
+
+/// Provides context for checking patterns in declarations. More specifically this
+/// allows us to infer array types if the pattern is irrefutable and allows us to infer
+/// the size of the array. See issue #76342.
```
Comment (Veykril) [inline crates/hir-ty/src/lib.rs:1066]:
```suggestion
/// the size of the array. See issue rust-lang/rust#76342.
```

File: crates/hir-ty/src/infer/pat.rs [hunk 7]
```diff
@@ -553,6 +581,63 @@ impl InferenceContext<'_> {
...
+    /// fn main() {
+    ///     let &[a, b]: &[usize] = Zeroes.into() else {
+    ///       ..
+    ///     };
+    /// }
+    /// ```
+    ///
+    /// If we're in an irrefutable pattern we prefer the array impl candidate given that
+    /// the slice impl candidate would be be rejected anyway (if no ambiguity existed).
+    fn decl_allows_array_type_infer(&self, decl_ctxt: Option<DeclContext>) -> bool {
```
Comment (Veykril) [inline crates/hir-ty/src/infer/pat.rs:634]: I'd prefer the name of the original rustc PR, that shows the intent more clearly behind this

File: crates/hir-ty/src/infer/expr.rs [hunk 8]
```diff
@@ -334,7 +334,7 @@ impl InferenceContext<'_> {
                     ExprIsRead::No
                 };
                 let input_ty = self.infer_expr(expr, &Expectation::none(), child_is_read);
-                self.infer_top_pat(pat, &input_ty);
+                self.infer_top_pat(pat, &input_ty, None);
```
Comment (Veykril) [inline crates/hir-ty/src/infer/expr.rs:337]: While we have no use for it now, we should put a `Some(DeclContext { origin: DeclOrigin::LetExpr }` here

**Comment by Veykril** [comment]
Looks good to me now 👍 
Could you squash the history / give the last two commits a bit more descriptive names?
