### PR TITLE
fix: Fix a stack overflow when computing the sizedness of a struct that includes itself as the tail field

### LINKED ISSUE #18556: Rust Analyzer Language Server crashes on infinite size structs with napi
**rust-analyzer version**: rust-analyzer version: 0.3.2196-standalone 

**rustc version**: rustc 1.82.0 (f6e511eec 2024-10-15)

**editor or extension**: Vscode, v0.3.2196

**code snippet to reproduce**: 
```rust
#[napi]
pub struct SomeType{
  pub(crate) field: SomeType,
}

```
What happens: When the following code is created in a napi-rs project, rust-analizer crashes with the following error:

```
thread 'Worker' has overflowed its stack
fatal runtime error: stack overflow
[Error - 15:00:04] Server process exited with signal SIGABRT.
[Info  - 15:00:04] Connection to server got closed. Server will restart.
true
```

It's not required to save the file for the following bug to happen. Extension will enter a crash loop while the following snippet is present in editor.

If the field causing the struct to be infinite is not last field in the struct, rust-analizer work correctly. f.ex.:
```rust
#[napi]
pub struct SomeType{
  pub(crate) field1: SomeType,
  pub(crate) field2: Box<SomeType>,
}
```

Visibility of the field doesn't affect this issue.

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Fixes #18556.

**Warning to the reviewer:** If you are going to open this in your editor of choice (with r-a of course), r-a will restart again and again, because we provide (some) IDE functionality to our tests which implies this actually overflows the stack when the test is present... Ask me how I know.

### CODE REVIEW

**Comment by ChayimFriedman2** [comment]
Wait this isn't enough we can still conduct a chain that overflows the stack... *Ugh*.

**Comment by ChayimFriedman2** [comment]
Fixed it now I think.

File: crates/hir-ty/src/infer/unify.rs [hunk 1]
```diff
@@ -916,6 +916,31 @@ impl<'a> InferenceTable<'a> {
...
     /// Check if given type is `Sized` or not
     pub(crate) fn is_sized(&mut self, ty: &Ty) -> bool {
+        let mut ty = ty.clone();
+        {
+            let mut structs = SmallVec::<[_; 8]>::new();
+            // Must use a loop here and not recursion because otherwise users will conduct completely
+            // artificial examples of structs that have themselves as the tail field and complain r-a crashes.
+            while let Some((AdtId::StructId(id), subst)) = ty.as_adt() {
+                let struct_data = self.db.struct_data(id);
+                if let Some((last_field, _)) = struct_data.variant_data.fields().iter().last() {
```
Comment (lnicola) [inline crates/hir-ty/src/infer/unify.rs:926]: Should we do `struct_data.variant_data.fields().iter().rev().next()` here? It's `DoubleEndedIterator`, so it might be a bit faster.

**Review by lnicola — APPROVED** [review]

File: crates/hir-ty/src/infer/unify.rs (hunk 1 above)
Comment (ChayimFriedman2) [reply crates/hir-ty/src/infer/unify.rs:926]: I didn't touch this part but yeah I guess. Do you want me to change this in this PR?

Comment (lnicola) [reply crates/hir-ty/src/infer/unify.rs:926]: Sure, let's do that if it works. LTGM otherwise.

Comment (ChayimFriedman2) [reply crates/hir-ty/src/infer/unify.rs]: Done.

Comment (lnicola) [reply crates/hir-ty/src/infer/unify.rs]: I think you have a stray semicolon.

**Review by lnicola — APPROVED** [review]

File: crates/hir-ty/src/infer/unify.rs [hunk 2]
```diff
@@ -916,6 +916,32 @@ impl<'a> InferenceTable<'a> {
...
+                    // Structs can have DST as its last field and such cases are not handled
+                    // as unsized by the chalk, so we do this manually.
+                    ty = last_field_ty;
+                } else {
+                    break;
+                };
+            }
+        }
+
         // Early return for some obvious types
```
Comment (Veykril) [inline crates/hir-ty/src/infer/unify.rs:945]: Any reason this was moved above the early return? Now this does more work for trivially sized types (by putting 8*8 bytes on the stack via the smallvec)

Comment (ChayimFriedman2) [reply crates/hir-ty/src/infer/unify.rs:945]: This is a trade-off; if we keep them before they won't apply to struct tails.

Comment (Veykril) [reply crates/hir-ty/src/infer/unify.rs:945]: Ah right, I guess we could wrap the loop in another `if let` so that we don't put the small vec on the stack
