### PR TITLE
Fix the length displayed for byte string literals with escaped newlines

### LINKED ISSUE #13567: Length of byte strings containing escaped newlines is displayed two bytes longer in a certain condition
I found a small issue that the length of byte strings containing escaped newlines is displayed two bytes longer when the first escaped character is a newline.

I have looked through the source code and may have fixed the issue. I will send PR later.

### Examples

```rust
let _ = b"
a
bc"; // &[u8, 5] is shown; OK

let _ = b"\
a
bc"; // &[u8, 6] is shown; 4 is correct

let _ = b"
a\
bc"; // &[u8, 6] is shown; 4 is correct

let _ = b"\
a\
bc"; // &[u8, 5] is shown; 3 is correct

let _ = b"\x61
bc"; // &[u8, 4] is shown; OK

let _ = b"\x61\
bc"; // &[u8, 3] is shown; OK

let _ = b"a\
bc"; // &[u8, 5] is shown; 3 is correct

let _ = b"\
\x61bc"; // &[u8, 5] is shown; 3 is correct
```

### Version info

**rust-analyzer version**: `rust-analyzer version: 0.3.1266-standalone (ba28e19b7 2022-10-29)`

**rustc version**: `rustc 1.65.0 (897e37553 2022-11-02)`

**relevant settings**: N/A

### PR DESCRIPTION
**Pull request by noritada**
This is a fix for the problem I reported earlier: "the length of byte strings containing escaped newlines is displayed two bytes longer when the first escaped character is a newline".

I would appreciate it if you could review the fix.
Many thanks.

Closes #13567

### CODE REVIEW

File: crates/syntax/src/ast/token_ext.rs [hunk 1]
```diff
@@ -445,6 +449,12 @@ mod tests {
         check_string_value(r"\foobar", None);
         check_string_value(r"\nfoobar", "\nfoobar");
         check_string_value(r"C:\\Windows\\System32\\", "C:\\Windows\\System32\\");
+        check_string_value(r"\x61bcde", "a\x62cde");
```
Comment (Veykril) [inline crates/syntax/src/ast/token_ext.rs:452]: Shouldn't the second string here be `abcde`?

Comment (noritada) [reply crates/syntax/src/ast/token_ext.rs:452]: Thank you very much for reviewing. As you suggest, `abcde` would be clearer in intent, so I will modify the code accordingly. Also, since the existing test code is only for strings, I will add test code for byte strings.

**Comment by Veykril** [comment]
Thanks!
@bors r+
