### PR TITLE
fix: Panic when a TAIT exists in a RPIT

### LINKED ISSUE #17921: Chalk panic with async function with type parameter returning TAIT
**rust-analyzer version**: rust-analyzer 0.0.0 (e4edf6ca94 2024-08-17)

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**code snippet to reproduce**: 
```rust
trait Foo {}
type Bar = impl Foo;

async fn f<A>() -> Bar {}
```
Panic:
```
assertion `left == right` failed
  left: 0
 right: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/core/src/panicking.rs:367:5
   4: chalk_ir::Binders<T>::substitute
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/lib.rs:2238:9
   5: hir_ty::infer::InferenceContext::insert_inference_vars_for_impl_trait::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/infer.rs:900:37
   6: hir_ty::fold_tys::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:675:45
   7: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::TypeFolder<hir_ty::interner::Interner>>::fold_ty
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:704:13
   8: hir_ty::fold_tys_and_consts::_::<impl chalk_ir::fold::FallibleTypeFolder<hir_ty::interner::Interner> for hir_ty::fold_tys_and_consts::TyFolder<F>>::try_fold_ty
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:688:14
   9: <chalk_ir::Ty<I> as chalk_ir::fold::TypeFoldable<I>>::try_fold_with
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/fold.rs:663:9
  10: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::AliasEq<I>>::try_fold_with
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/lib.rs:2025:38
  11: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::WhereClause<I>>::try_fold_with
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/lib.rs:1730:38
  12: chalk_ir::fold::TypeFoldable::fold_with
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/fold.rs:629:9
  13: hir_ty::fold_tys_and_consts
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:711:5
  14: hir_ty::fold_tys
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:672:5
  15: hir_ty::infer::InferenceContext::insert_inference_vars_for_impl_trait
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/infer.rs:875:9
  16: hir_ty::infer::InferenceContext::insert_inference_vars_for_impl_trait::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/infer.rs:904:41
  17: hir_ty::fold_tys::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:675:45
  18: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::TypeFolder<hir_ty::interner::Interner>>::fold_ty
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:704:13
  19: hir_ty::fold_tys_and_consts::_::<impl chalk_ir::fold::FallibleTypeFolder<hir_ty::interner::Interner> for hir_ty::fold_tys_and_consts::TyFolder<F>>::try_fold_ty
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:688:14
  20: <chalk_ir::Ty<I> as chalk_ir::fold::TypeFoldable<I>>::try_fold_with
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/fold.rs:663:9
  21: chalk_ir::fold::TypeFoldable::fold_with
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/fold.rs:629:9
  22: hir_ty::fold_tys_and_consts
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:711:5
  23: hir_ty::fold_tys
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/lib.rs:672:5
  24: hir_ty::infer::InferenceContext::insert_inference_vars_for_impl_trait
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/infer.rs:875:9
  25: hir_ty::infer::InferenceContext::collect_fn
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/infer.rs:848:26
  26: hir_ty::infer::infer_query
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/infer.rs:91:13
  27: <hir_ty::db::InferQuery as salsa::plumbing::QueryFunction>::execute
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/db.rs:34:21
  28: salsa::derived::slot::Slot<Q>::execute::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/derived/slot.rs:224:43
  29: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/core/src/panic/unwind_safe.rs:272:9
  30: std::panicking::try::do_call
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/std/src/panicking.rs:554:40
  31: ___rust_try
  32: std::panicking::try
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/std/src/panicking.rs:518:19
  33: std::panic::catch_unwind
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/std/src/panic.rs:345:14
  34: salsa::Cycle::catch
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/lib.rs:692:15
  35: salsa::derived::slot::Slot<Q>::execute
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/derived/slot.rs:224:27
  36: salsa::derived::slot::Slot<Q>::read_upgrade
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/derived/slot.rs:202:9
  37: salsa::derived::slot::Slot<Q>::read
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/derived/slot.rs:140:9
  38: <salsa::derived::DerivedStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::fetch
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/derived.rs:108:62
  39: salsa::QueryTable<Q>::get
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/lib.rs:502:9
  40: <DB as hir_ty::db::HirDatabase>::infer::__shim
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/db.rs:32:1
  41: <DB as hir_ty::db::HirDatabase>::infer
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/db.rs:32:1
  42: hir::source_analyzer::SourceAnalyzer::new_for_body
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir/src/source_analyzer.rs:72:57
  43: hir::semantics::SemanticsImpl::analyze_impl
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir/src/semantics.rs:1446:21
  44: hir::semantics::SemanticsImpl::analyze
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir/src/semantics.rs:1416:9
  45: hir::semantics::SemanticsImpl::resolve_path
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir/src/semantics.rs:1344:9
  46: ide_db::defs::NameRefClass::classify
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide-db/src/defs.rs:625:20
  47: ide_db::defs::IdentClass::classify_node
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide-db/src/defs.rs:291:43
  48: ide_db::defs::IdentClass::classify_token
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide-db/src/defs.rs:312:9
  49: ide_db::helpers::get_definition
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide-db/src/helpers.rs:122:19
  50: ide::static_index::StaticIndex::add_file
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/static_index.rs:188:29
  51: ide::static_index::StaticIndex::compute
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/static_index.rs:257:13
  52: rust_analyzer::cli::scip::<impl rust_analyzer::cli::flags::Scip>::run
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/rust-analyzer/src/cli/scip.rs:66:18
  53: rust_analyzer::actual_main
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:89:46
  54: rust_analyzer::main
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:39:9
  55: core::ops::function::FnOnce::call_once
             at /rustc/41dd149fd6a6a06795fc6b9f54cb49af2f61775f/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes  #17921

When there is a TAIT inside of a RPIT like;

```rust
trait Foo {}
type Bar = impl Foo;
fn foo<A>() -> impl Future<Output = Bar> { .. }
```

while inferencing `fn foo`, `insert_inference_vars_for_impl_trait` tries to substitute impl trait bounds of `Bar`, i.e. `Implemented(Foo)` with RPITs `placeholders`, and this causes panic

https://github.com/rust-lang/rust-analyzer/blob/fa003262474185fd62168379500fe906b331824b/crates/hir-ty/src/infer.rs#L903-L905

### CODE REVIEW

File: crates/hir-ty/src/infer.rs [hunk 1]
```diff
@@ -825,13 +830,13 @@ impl<'a> InferenceContext<'a> {
...
         }
-        let mut params_and_ret_tys = Vec::new();
+        let mut tait_candidates = FxHashSet::default();
         for (ty, pat) in param_tys.zip(&*self.body.params) {
             let ty = self.insert_type_vars(ty);
             let ty = self.normalize_associated_types_in(ty);
 
             self.infer_top_pat(*pat, &ty);
-            params_and_ret_tys.push(ty);
+            tait_candidates.insert(ty);
```
Comment (Veykril) [inline crates/hir-ty/src/infer.rs:839]:
```suggestion
			if ty.data(Interner).flags.intersects(TypeFlags::HAS_TY_OPAQUE) {
	            tait_candidates.insert(ty);
	        }
```
(just noticed the flag exists)

File: crates/hir-ty/src/infer.rs [hunk 2]
```diff
@@ -863,11 +873,16 @@ impl<'a> InferenceContext<'a> {
         // Functions might be defining usage sites of TAITs.
         // To define an TAITs, that TAIT must appear in the function's signatures.
         // So, it suffices to check for params and return types.
-        params_and_ret_tys.push(self.return_ty.clone());
-        self.make_tait_coercion_table(params_and_ret_tys.iter());
+        tait_candidates.insert(self.return_ty.clone());
```
Comment (Veykril) [inline crates/hir-ty/src/infer.rs:876]:
```suggestion
		if self.return_ty.data(Interner).flags.intersects(TypeFlags::HAS_TY_OPAQUE) {
	        tait_candidates.insert(self.return_ty.clone());
	    }
```

**Comment by Veykril** [comment]
Thanks!
@bors delegate+

File: crates/hir-ty/src/infer.rs (hunk 1 above)
Comment (ShoyuVanilla) [reply crates/hir-ty/src/infer.rs:839]: It's strange that this makes the tests fail 🤔 

```
failures:

---- tests::diagnostics::no_mismatches_on_atpit stdout ----
thread 'tests::diagnostics::no_mismatches_on_atpit' panicked at crates/hir-ty/src/tests/diagnostics.rs:102:5:
Unexpected type mismatches:
257..259: expected impl Sized, got ()

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::type_alias_impl_traits::associated_type_impl_trait stdout ----
thread 'tests::type_alias_impl_traits::associated_type_impl_trait' panicked at crates/hir-ty/src/tests/type_alias_impl_traits.rs:7:5:
Unexpected type mismatches:
203..205: expected impl Foo + ?Sized, got S1


---- tests::type_alias_impl_traits::associated_type_impl_traits_complex stdout ----
thread 'tests::type_alias_impl_traits::associated_type_impl_traits_complex' panicked at crates/hir-ty/src/tests/type_alias_impl_traits.rs:35:5:
Unexpected type mismatches:
293..295: expected impl Foo + ?Sized, got S1
585..587: expected impl Foo + ?Sized, got S1
595..597: expected impl Bar + ?Sized, got S2



failures:
    tests::diagnostics::no_mismatches_on_atpit
    tests::type_alias_impl_traits::associated_type_impl_trait
    tests::type_alias_impl_traits::associated_type_impl_traits_complex

test result: FAILED. 783 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.67s
```

Comment (ShoyuVanilla) [reply crates/hir-ty/src/infer.rs:839]: Oh, I see. It seems that the types we are inserting has some inference vars inside and

https://github.com/rust-lang/rust-analyzer/blob/c9955bf86bd7fb779c44048ef67e8bf0fec76291/crates/hir-ty/src/infer.rs#L949

this line is adding opaque types when the top type doesn't have the flag `HAS_TY_OPAQUE`

Comment (Veykril) [reply crates/hir-ty/src/infer.rs:839]: I guess we can check for either `HAS_TY_OPAQUE` or `HAS_TY_INFER` then? If not feel free to merge as is

Comment (ShoyuVanilla) [reply crates/hir-ty/src/infer.rs:839]: Reasonable alternative 👍
