### PR TITLE
fix: rewrite code_action `generate_delegate_trait`

### LINKED ISSUE #15108: Delegate trait impl assist does not subsitute generic params
Okay, this mostly looks good but there is one thing that we should fix still, which can be seen in your second gif (im not talking about the unstable thing being proposed). We forget to account for the substituted generics. Example:
```rs
struct S { f: Foo<i32>$0 }

struct Foo<U>(U);

trait T<U> {
    type Ty;
    fn f(self) -> Self::Ty;
}
impl<U> T<U> for Foo<U> {
    type Ty = U;
    fn f(self) -> Self::Ty {
        self.0
    }
}

```
Current assist would generate the following which is invalid
```rs
impl<U> T<U> for S {
    type Ty = <Foo<U> as T<U>>::Ty;
    fn f(self) -> Self::Ty {
        <Foo<U> as T<U>>::f(self.f) // type error, `<Foo<U> as T<U>>::f` expects a value of type `Foo<U>`, but here we give it a `Foo<i32>`
    }
}
```
It should instead generate this:
```rs
impl T<i32> for S {
    type Ty = <Foo<i32> as T<i32>>::Ty;
    fn f(self) -> Self::Ty {
        <Foo<i32> as T<i32>>::f(self.f)
    }
}
```

_Originally posted by @Veykril in https://github.com/rust-lang/rust-analyzer/pull/14948#pullrequestreview-1492858502_

### LINKED ISSUE #15804: Arrays as struct members causes panic
Example file
```rust
const MAX_ONE_BYTE_PICTURE_ID: i16 = 0x7F; // 7 bits
const MAX_TWO_BYTE_PICTURE_ID: i16 = 0x7FFF; // 15 bits
const NO_SPATIAL_IDX: u8 = 0xFF;
const NO_GOF_IDX: u8 = 0xFF;
const NUM_VP9_BUFFERS: u8 = 8;
const MAX_VP9_REF_PICS: usize = 3;
const MAX_VP9_FRAMES_IN_GOF: usize = 0xFF; // 8 bits
const MAX_VP9_NUMBER_OF_SPATIAL_LAYERS: usize = 8;

const MIN_VP9_SPATIAL_LAYER_LONG_SIDE_LENGTH: usize = 240;
const MIN_VP9_SPATIAL_LAYER_SHORT_SIDE_LENGTH: usize = 135;

pub struct Gof {
    pub num_frames_in_gof: usize,
    pub temporal_idx: [u8; MAX_VP9_FRAMES_IN_GOF],
    pub temporal_up_switch: [bool; MAX_VP9_FRAMES_IN_GOF],
    pub num_ref_pics: [u8; MAX_VP9_FRAMES_IN_GOF],
    pub pid_diff: [[u8; MAX_VP9_REF_PICS]; MAX_VP9_FRAMES_IN_GOF],
    pub pid_start: u16,
}
```

ra version: 2023-10-23
rustc: rustc 1.73.0 (cc66ad468 2023-10-03)
Pop_OS, Emacs

Hovering a cursor anywhere over the array literals breaks the LSP.:

```
Saving file /home/nate/dev/icarus/lib/webrtc/src/video/codecs/vp9/gof.rs...
LSP :: No formatting changes provided
Wrote /home/nate/dev/icarus/lib/webrtc/src/video/codecs/vp9/gof.rs
LSP :: Error from the Language Server: request handler panicked: Can't find CONST_ARG@158..159 in AstIdMap:
[SyntaxNodePtr { kind: USE, range: 153..192 }, SyntaxNodePtr { kind: USE, range: 193..218 }, ...truncated, but should get the point across
lsp-request: request handler panicked: Can’t find CONST_ARG@158..159 in AstIdMap:
```

### LINKED ISSUE #15968: thread 'Worker' panicked at crates/hir-expand/src/ast_id_map.rs:176:21
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```
Panic context:
> 
version: 0.3.1740-standalone
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/var/home/msivak/.var/app/com.vscodium.codium/data/cargo/registry/src/index.crates.io-6f17d22bba15001f/heapless-0.7.16/src/vec.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 42,
            character: 11,
        },
        end: Position {
            line: 42,
            character: 11,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at crates/hir-expand/src/ast_id_map.rs:176:21:
Can't find CONST_ARG@167..168 in AstIdMap:
[SyntaxNodePtr { kind: USE, range: 153..192 }, SyntaxNodePtr { kind: USE, range: 193..218 }, SyntaxNodePtr { kind: USE, range: 219..261 }, SyntaxNodePtr { kind: USE, range: 262..286 }, SyntaxNodePtr { kind: USE, range: 287..302 }, SyntaxNodePtr { kind: USE, range: 303..333 }, SyntaxNodePtr { kind: USE, range: 334..369 }, SyntaxNodePtr { kind: USE, range: 370..406 }, SyntaxNodePtr { kind: USE, range: 407..527 }, SyntaxNodePtr { kind: USE, range: 528..562 }, SyntaxNodePtr { kind: MODULE, range: 564..574 }, SyntaxNodePtr { kind: MODULE, range: 575..585 }, SyntaxNodePtr { kind: MODULE, range: 586..599 }, SyntaxNodePtr { kind: MODULE, range: 600..609 }, SyntaxNodePtr { kind: USE, range: 611..650 }, SyntaxNodePtr { kind: USE, range: 652..733 }, SyntaxNodePtr { kind: FN, range: 735..1975 }, SyntaxNodePtr { kind: FN, range: 1977..3736 }, SyntaxNodePtr { kind: FN, range: 3738..4117 }, SyntaxNodePtr { kind: FN, range: 4119..4526 }, SyntaxNodePtr { kind: STRUCT, range: 4528..4719 }, SyntaxNodePtr { kind: IMPL, range: 4721..4962 }, SyntaxNodePtr { kind: IMPL, range: 4964..5160 }, SyntaxNodePtr { kind: IMPL, range: 5162..5346 }, SyntaxNodePtr { kind: IMPL, range: 5348..5512 }, SyntaxNodePtr { kind: IMPL, range: 5514..5690 }, SyntaxNodePtr { kind: IMPL, range: 5692..5845 }, SyntaxNodePtr { kind: IMPL, range: 5847..6015 }, SyntaxNodePtr { kind: IMPL, range: 6017..6719 }, SyntaxNodePtr { kind: IMPL, range: 6721..7466 }, SyntaxNodePtr { kind: IMPL, range: 7468..8382 }, SyntaxNodePtr { kind: IMPL, range: 8384..9370 }, SyntaxNodePtr { kind: IMPL, range: 9372..9927 }, SyntaxNodePtr { kind: IMPL, range: 9929..10144 }, SyntaxNodePtr { kind: IMPL, range: 10146..10374 }, SyntaxNodePtr { kind: IMPL, range: 10376..10622 }, SyntaxNodePtr { kind: IMPL, range: 10624..10919 }, SyntaxNodePtr { kind: IMPL, range: 10921..11199 }, SyntaxNodePtr { kind: IMPL, range: 11201..11893 }, SyntaxNodePtr { kind: IMPL, range: 11895..12187 }, SyntaxNodePtr { kind: IMPL, range: 12189..12299 }, SyntaxNodePtr { kind: IMPL, range: 12301..12604 }, SyntaxNodePtr { kind: TRAIT, range: 12606..12699 }, SyntaxNodePtr { kind: IMPL, range: 12701..12878 }, SyntaxNodePtr { kind: IMPL, range: 12880..13010 }, SyntaxNodePtr { kind: MACRO_RULES, range: 13211..13755 }, SyntaxNodePtr { kind: MACRO_CALL, range: 13757..13846 }, SyntaxNodePtr { kind: IMPL, range: 13848..23903 }, SyntaxNodePtr { kind: FN, range: 23905..24376 }, SyntaxNodePtr { kind: FN, range: 24378..24976 }, SyntaxNodePtr { kind: FN, range: 24978..26268 }, SyntaxNodePtr { kind: STRUCT, range: 26270..26894 }, SyntaxNodePtr { kind: IMPL, range: 26896..27544 }, SyntaxNodePtr { kind: IMPL, range: 27546..27932 }, SyntaxNodePtr { kind: FN, range: 27934..29067 }, SyntaxNodePtr { kind: FN, range: 29069..30103 }, SyntaxNodePtr { kind: PARAM, range: 1870..1875 }, SyntaxNodePtr { kind: CONST_ARG, range: 1884..1885 }, SyntaxNodePtr { kind: PARAM, range: 1906..1911 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 1919..1975 }, SyntaxNodePtr { kind: PARAM, range: 3245..3250 }, SyntaxNodePtr { kind: CONST_ARG, range: 3287..3288 }, SyntaxNodePtr { kind: PARAM, range: 3310..3315 }, SyntaxNodePtr { kind: CONST_ARG, range: 3373..3374 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 3378..3736 }, SyntaxNodePtr { kind: PARAM, range: 3992..3997 }, SyntaxNodePtr { kind: CONST_ARG, range: 4007..4008 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 4010..4117 }, SyntaxNodePtr { kind: PARAM, range: 4383..4392 }, SyntaxNodePtr { kind: CONST_ARG, range: 4406..4407 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 4409..4526 }, SyntaxNodePtr { kind: TUPLE_FIELD, range: 4715..4717 }, SyntaxNodePtr { kind: FN, range: 4819..4960 }, SyntaxNodePtr { kind: FN, range: 5053..5158 }, SyntaxNodePtr { kind: FN, range: 5274..5344 }, SyntaxNodePtr { kind: CONST_ARG, range: 5437..5438 }, SyntaxNodePtr { kind: FN, range: 5446..5510 }, SyntaxNodePtr { kind: CONST_ARG, range: 5603..5604 }, SyntaxNodePtr { kind: FN, range: 5612..5688 }, SyntaxNodePtr { kind: CONST_ARG, range: 5789..5790 }, SyntaxNodePtr { kind: FN, range: 5798..5843 }, SyntaxNodePtr { kind: CONST_ARG, range: 5947..5948 }, SyntaxNodePtr { kind: FN, range: 5956..6013 }, SyntaxNodePtr { kind: CONST_ARG, range: 6524..6525 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 6552..6583 }, SyntaxNodePtr { kind: FN, range: 6589..6717 }, SyntaxNodePtr { kind: CONST_ARG, range: 7278..7279 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 7306..7337 }, SyntaxNodePtr { kind: FN, range: 7343..7464 }, SyntaxNodePtr { kind: CONST_ARG, range: 7989..7990 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 7998..8029 }, SyntaxNodePtr { kind: FN, range: 8035..8380 }, SyntaxNodePtr { kind: CONST_ARG, range: 8963..8964 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 8972..9003 }, SyntaxNodePtr { kind: FN, range: 9009..9368 }, SyntaxNodePtr { kind: CONST_ARG, range: 9825..9826 }, SyntaxNodePtr { kind: FN, range: 9834..9925 }, SyntaxNodePtr { kind: CONST_ARG, range: 10030..10031 }, SyntaxNodePtr { kind: FN, range: 10039..10142 }, SyntaxNodePtr { kind: CONST_ARG, range: 10245..10246 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 10254..10272 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 10277..10305 }, SyntaxNodePtr { kind: FN, range: 10311..10372 }, SyntaxNodePtr { kind: CONST_ARG, range: 10479..10480 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 10488..10510 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 10515..10546 }, SyntaxNodePtr { kind: FN, range: 10552..10620 }, SyntaxNodePtr { kind: CONST_ARG, range: 10731..10732 }, SyntaxNodePtr { kind: TYPE_ALIAS, range: 10765..10805 }, SyntaxNodePtr { kind: FN, range: 10811..10917 }, SyntaxNodePtr { kind: CONST_ARG, range: 11031..11032 }, SyntaxNodePtr { kind: FN, range: 11068..11197 }, SyntaxNodePtr { kind: CONST_ARG, range: 11302..11303 }, SyntaxNodePtr { kind: FN, range: 11311..11447 }, SyntaxNodePtr { kind: FN, range: 11452..11558 }, SyntaxNodePtr { kind: FN, range: 11563..11669 }, SyntaxNodePtr { kind: FN, range: 11674..11780 }, SyntaxNodePtr { kind: FN, range: 11785..11891 }, SyntaxNodePtr { kind: CONST_ARG, range: 12071..12072 }, SyntaxNodePtr { kind: FN, range: 12080..12185 }, SyntaxNodePtr { kind: CONST_ARG, range: 12294..12295 }, SyntaxNodePtr { kind: CONST_ARG, range: 12408..12409 }, SyntaxNodePtr { kind: FN, range: 12417..12498 }, SyntaxNodePtr { kind: FN, range: 12504..12602 }, SyntaxNodePtr { kind: FN, range: 12640..12697 }, SyntaxNodePtr { kind: FN, range: 12743..12876 }, SyntaxNodePtr { kind: FN, range: 12921..13008 }, SyntaxNodePtr { kind: CONST_ARG, range: 13876..13877 }, SyntaxNodePtr { kind: FN, range: 13885..15721 }, SyntaxNodePtr { kind: FN, range: 15727..17113 }, SyntaxNodePtr { kind: FN, range: 17119..17385 }, SyntaxNodePtr { kind: FN, range: 17391..17611 }, SyntaxNodePtr { kind: FN, range: 17617..18725 }, SyntaxNodePtr { kind: FN, range: 18731..19357 }, SyntaxNodePtr { kind: FN, range: 19363..20607 }, SyntaxNodePtr { kind: FN, range: 20613..21600 }, SyntaxNodePtr { kind: FN, range: 21606..22880 }, SyntaxNodePtr { kind: FN, range: 22886..23901 }, SyntaxNodePtr { kind: PARAM, range: 24262..24300 }, SyntaxNodePtr { kind: CONST_ARG, range: 24309..24310 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 24312..24376 }, SyntaxNodePtr { kind: PARAM, range: 24444..24482 }, SyntaxNodePtr { kind: CONST_ARG, range: 24513..24514 }, SyntaxNodePtr { kind: CONST_ARG, range: 24577..24578 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 24582..24976 }, SyntaxNodePtr { kind: PARAM, range: 25766..25795 }, SyntaxNodePtr { kind: PARAM, range: 25801..25838 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 25900..26268 }, SyntaxNodePtr { kind: RECORD_FIELD, range: 26724..26800 }, SyntaxNodePtr { kind: RECORD_FIELD, range: 26806..26891 }, SyntaxNodePtr { kind: FN, range: 26923..27542 }, SyntaxNodePtr { kind: FN, range: 27582..27930 }, SyntaxNodePtr { kind: PARAM, range: 28515..28549 }, SyntaxNodePtr { kind: CONST_ARG, range: 28567..28568 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 28587..29067 }, SyntaxNodePtr { kind: PARAM, range: 29398..29427 }, SyntaxNodePtr { kind: PARAM, range: 29433..29467 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 29492..30103 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 3583..3728 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 4070..4115 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 4477..4524 }, SyntaxNodePtr { kind: SELF_PARAM, range: 4840..4845 }, SyntaxNodePtr { kind: PARAM, range: 4847..4873 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 4890..4960 }, SyntaxNodePtr { kind: SELF_PARAM, range: 5093..5098 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 5108..5158 }, SyntaxNodePtr { kind: PARAM, range: 5282..5295 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 5318..5344 }, SyntaxNodePtr { kind: SELF_PARAM, range: 5470..5475 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 5485..5510 }, SyntaxNodePtr { kind: SELF_PARAM, range: 5636..5645 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 5659..5688 }, SyntaxNodePtr { kind: SELF_PARAM, range: 5808..5813 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 5823..5843 }, SyntaxNodePtr { kind: SELF_PARAM, range: 5970..5979 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 5993..6013 }, SyntaxNodePtr { kind: PARAM, range: 6615..6626 }, SyntaxNodePtr { kind: CONST_ARG, range: 6642..6643 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 6665..6717 }, SyntaxNodePtr { kind: PARAM, range: 7369..7384 }, SyntaxNodePtr { kind: CONST_ARG, range: 7400..7401 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 7423..7464 }, SyntaxNodePtr { kind: PARAM, range: 8061..8075 }, SyntaxNodePtr { kind: CONST_ARG, range: 8095..8096 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 8118..8380 }, SyntaxNodePtr { kind: PARAM, range: 9035..9053 }, SyntaxNodePtr { kind: CONST_ARG, range: 9077..9078 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 9100..9368 }, SyntaxNodePtr { kind: SELF_PARAM, range: 9859..9864 }, SyntaxNodePtr { kind: PARAM, range: 9866..9879 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 9881..9925 }, SyntaxNodePtr { kind: SELF_PARAM, range: 10046..10051 }, SyntaxNodePtr { kind: PARAM, range: 10053..10079 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 10096..10142 }, SyntaxNodePtr { kind: SELF_PARAM, range: 10324..10328 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 10345..10372 }, SyntaxNodePtr { kind: SELF_PARAM, range: 10565..10569 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 10589..10620 }, SyntaxNodePtr { kind: SELF_PARAM, range: 10834..10839 }, SyntaxNodePtr { kind: PARAM, range: 10841..10849 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 10868..10917 }, SyntaxNodePtr { kind: SELF_PARAM, range: 11095..11104 }, SyntaxNodePtr { kind: PARAM, range: 11106..11114 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 11137..11197 }, SyntaxNodePtr { kind: SELF_PARAM, range: 11340..11345 }, SyntaxNodePtr { kind: PARAM, range: 11347..11361 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 11383..11447 }, SyntaxNodePtr { kind: SELF_PARAM, range: 11472..11477 }, SyntaxNodePtr { kind: PARAM, range: 11479..11493 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 11503..11558 }, SyntaxNodePtr { kind: SELF_PARAM, range: 11583..11588 }, SyntaxNodePtr { kind: PARAM, range: 11590..11604 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 11614..11669 }, SyntaxNodePtr { kind: SELF_PARAM, range: 11694..11699 }, SyntaxNodePtr { kind: PARAM, range: 11701..11715 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 11725..11780 }, SyntaxNodePtr { kind: SELF_PARAM, range: 11805..11810 }, SyntaxNodePtr { kind: PARAM, range: 11812..11826 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 11836..11891 }, SyntaxNodePtr { kind: SELF_PARAM, range: 12101..12106 }, SyntaxNodePtr { kind: PARAM, range: 12108..12122 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 12136..12185 }, SyntaxNodePtr { kind: SELF_PARAM, range: 12440..12445 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 12455..12498 }, SyntaxNodePtr { kind: SELF_PARAM, range: 12532..12541 }, SyntaxNodePtr { kind: PARAM, range: 12543..12555 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 12557..12602 }, SyntaxNodePtr { kind: PARAM, range: 12665..12682 }, SyntaxNodePtr { kind: CONST_ARG, range: 12694..12695 }, SyntaxNodePtr { kind: PARAM, range: 12790..12804 }, SyntaxNodePtr { kind: CONST_ARG, range: 12813..12814 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 12816..12876 }, SyntaxNodePtr { kind: PARAM, range: 12960..12974 }, SyntaxNodePtr { kind: CONST_ARG, range: 12983..12984 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 12986..13008 }, SyntaxNodePtr { kind: SELF_PARAM, range: 15595..15599 }, SyntaxNodePtr { kind: PARAM, range: 15601..15605 }, SyntaxNodePtr { kind: CONST_ARG, range: 15614..15615 }, SyntaxNodePtr { kind: PARAM, range: 15644..15645 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 15657..15721 }, SyntaxNodePtr { kind: SELF_PARAM, range: 16874..16878 }, SyntaxNodePtr { kind: PARAM, range: 16880..16884 }, SyntaxNodePtr { kind: CONST_ARG, range: 16921..16922 }, SyntaxNodePtr { kind: PARAM, range: 16952..16953 }, SyntaxNodePtr { kind: CONST_ARG, range: 17019..17020 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 17028..17113 }, SyntaxNodePtr { kind: SELF_PARAM, range: 17350..17355 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 17365..17385 }, SyntaxNodePtr { kind: SELF_PARAM, range: 17568..17577 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 17591..17611 }, SyntaxNodePtr { kind: SELF_PARAM, range: 18657..18662 }, SyntaxNodePtr { kind: CONST_ARG, range: 18672..18673 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 18675..18725 }, SyntaxNodePtr { kind: SELF_PARAM, range: 19277..19286 }, SyntaxNodePtr { kind: CONST_ARG, range: 19300..19301 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 19303..19357 }, SyntaxNodePtr { kind: SELF_PARAM, range: 20531..20536 }, SyntaxNodePtr { kind: CONST_ARG, range: 20547..20548 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 20557..20607 }, SyntaxNodePtr { kind: SELF_PARAM, range: 21508..21517 }, SyntaxNodePtr { kind: CONST_ARG, range: 21532..21533 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 21546..21600 }, SyntaxNodePtr { kind: SELF_PARAM, range: 22803..22808 }, SyntaxNodePtr { kind: CONST_ARG, range: 22825..22826 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 22829..22880 }, SyntaxNodePtr { kind: SELF_PARAM, range: 23808..23817 }, SyntaxNodePtr { kind: CONST_ARG, range: 23842..23843 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 23846..23901 }, SyntaxNodePtr { kind: MACRO_CALL, range: 24588..24620 }, SyntaxNodePtr { kind: FN, range: 24626..24945 }, SyntaxNodePtr { kind: PARAM, range: 25827..25832 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 26020..26211 }, SyntaxNodePtr { kind: SELF_PARAM, range: 27128..27137 }, SyntaxNodePtr { kind: PARAM, range: 27139..27146 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 27148..27542 }, SyntaxNodePtr { kind: SELF_PARAM, range: 27590..27599 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 27601..27930 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 28729..28868 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 28897..29059 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 29611..30065 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 3662..3718 }, SyntaxNodePtr { kind: CONST_ARG, range: 4108..4109 }, SyntaxNodePtr { kind: CONST_ARG, range: 4517..4518 }, SyntaxNodePtr { kind: PARAM, range: 6705..6706 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 8148..8318 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 8324..8374 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 9130..9306 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 9312..9362 }, SyntaxNodePtr { kind: CONST_ARG, range: 11359..11360 }, SyntaxNodePtr { kind: CONST_ARG, range: 11491..11492 }, SyntaxNodePtr { kind: CONST_ARG, range: 11602..11603 }, SyntaxNodePtr { kind: CONST_ARG, range: 11713..11714 }, SyntaxNodePtr { kind: CONST_ARG, range: 11824..11825 }, SyntaxNodePtr { kind: CONST_ARG, range: 12120..12121 }, SyntaxNodePtr { kind: CONST_ARG, range: 12680..12681 }, SyntaxNodePtr { kind: CONST_ARG, range: 12802..12803 }, SyntaxNodePtr { kind: CONST_ARG, range: 12972..12973 }, SyntaxNodePtr { kind: PARAM, range: 17062..17066 }, SyntaxNodePtr { kind: PARAM, range: 24637..24679 }, SyntaxNodePtr { kind: PARAM, range: 24695..24700 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 24707..24945 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 26167..26204 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 27376..27536 }, SyntaxNodePtr { kind: MACRO_CALL, range: 27611..27666 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 27746..27924 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 28809..28857 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 28991..29048 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 29655..29933 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 30021..30058 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 3668..3716 }, SyntaxNodePtr { kind: CONST_ARG, range: 8201..8202 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 8288..8308 }, SyntaxNodePtr { kind: CONST_ARG, range: 9185..9186 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 9272..9296 }, SyntaxNodePtr { kind: PARAM, range: 24723..24724 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 24726..24939 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 24897..24929 }]
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: hir_expand::ast_id_map::AstIdMap::erased_ast_id
   3: hir_def::hir::type_ref::ConstRef::from_const_arg
   4: hir_def::hir::type_ref::TypeRef::from_ast
   5: hir_def::path::lower::lower_generic_args
   6: hir_def::path::lower::lower_path
   7: hir::semantics::SemanticsScope::speculative_resolve
   8: ide_db::path_transform::Ctx::transform_path
   9: ide_db::path_transform::Ctx::apply
  10: ide_db::path_transform::PathTransform::apply
  11: ide_assists::handlers::generate_delegate_trait::Struct::delegate
  12: ide_assists::handlers::generate_delegate_trait::generate_delegate_trait
  13: ide_assists::assists
  14: std::panicking::try
  15: ide::Analysis::assists_with_fixes
  16: rust_analyzer::handlers::request::handle_code_action
  17: std::panicking::try
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**rustc version**: (eg. output of `rustc -V`)

rustc 1.75.0-nightly (e0d7ed1f4 2023-10-01)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

VSCodium from flatpak

Version: 1.84.2
Release: 23319
Commit: 1fc52b725b3f76b97eadfd988cea42a739ae923f
Date: 2023-11-15T21:57:44.436Z
Electron: 25.9.2
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.12-300.fc39.x86_64

### PR DESCRIPTION
**Pull request by roife**
I've made substantial enhancements to the "generate delegate trait" code action in rust-analyzer. Here's a summary of the changes:

#### Resolved the "Can’t find CONST_ARG@158..159 in AstIdMap" error

Fix #15804, fix #15968, fix #15108

The issue stemmed from an incorrect application of PathTransform in the original code. Previously, a new 'impl' was generated first and then transformed, causing PathTransform to fail in locating the correct AST node, resulting in an error. I rectified this by performing the transformation before generating the new 'impl' (using make::impl_trait), ensuring a step-by-step transformation of associated items.

#### Rectified generation of `Self` type

`generate_delegate_trait` is unable to properly handle trait with `Self` type.

Let's take the following code as an example:

```rust
trait Trait {
    fn f() -> Self;
}

struct B {}
impl Trait for B {
    fn f() -> B { B{} }
}

struct S {
    b: B,
}
```

Here, if we implement `Trait` for `S`, the type of `f` should be `() -> Self`, i.e. `() -> S`. However we cannot automatically generate a function that constructs `S`.

To ensure that the code action doesn't generate delegate traits for traits with Self types, I add a function named `has_self_type` to handle it.

#### Extended support for generics in structs and fields within this code action

The former version of `generate_delegate_trait` cannot handle structs with generics properly. Here's an example:

```rust
struct B<T> {
    a: T
}

trait Trait<T> {
    fn f(a: T);
}

impl<T1, T2> Trait<T1> for B<T2> {
    fn f(a: T1) -> T2 { self.a }
}

struct A {}
struct S {
    b$0 : B<A>,
}
```

The former version  will generates improper code:

```rust
impl<T1, T2> Trait<T1, T2> for S {
    fn f(&self, a: T1) -> T1 {
        <B as Trait<T1, T2>>::f( &self.b , a)
    }
}
```

The rewritten version can handle generics properly:

```rust
impl<T1> Trait<T1> for S {
    fn f(&self, a: T1) -> T1 {
        <B<A> as Trait<T1>>::f(&self.b, a)
    }
}
```

See more examples in added unit tests.

I enabled support for generic structs in `generate_delegate_trait` through the following steps (using the code example provided):

1. Initially, to prevent conflicts between the generic parameters in struct `S` and the ones in the impl of `B`, I renamed the generic parameters of `S`.
2. Then, since `B`'s parameters are instantiated within `S`, the original generic parameters of `B` needed removal within `S` (to avoid errors from redundant parameters). An important consideration here arises when Trait and B share parameters in `B`'s impl. In such cases, these shared generic parameters cannot be removed.
3. Next, I addressed the matching of types between `B`'s type in `S` and its type in the impl. Given that some generic parameters in the impl are instantiated in `B`, I replaced these parameters with their instantiated results using PathTransform. For instance, in the example provided, matching `B<A>` and `B<T2>`, where `T2` is instantiated as `A`, I replaced all occurrences of `T2` in the impl with `A` (i.e. apply the instantiated generic arguments to the params).
4. Finally, I performed transformations on each assoc item (also to prevent the initial issue) and handled redundant where clauses.

For a more detailed explanation, please refer to the code and comments. I welcome suggestions and any further questions!

### CODE REVIEW

**Comment by roife** [comment]
Here's an simple example for the third step mentioned above. Say we have the following code:

```rust
struct B<T> {
    a: T
}

trait Trait<T> {
    fn f(&self) -> &T;
}

impl<T> Trait<T> for B<T> {
    fn f(&self) -> &T { &self.a }
}

struct S<T> {
    a: B<T>
}
```

To generate a delegate impl for `a` in `S<T>`, the proper implementation is as following:

```rust
// generated after rewritten
impl<T> Trait<T> for S<T> {
    fn f(&self) -> &T {
        <B<T> as Trait<T0>>::f(&self.a)
    }
}
```

However, if we do not match and replace instantiated generic arguments, we will get

```rust
impl<T, T0> Trait<T> for S<T0> {
    fn f(&self) -> &T {
        <B<T0> as Trait<T>>::f(&self.a)
    }
}
```

which is not correct.

File: crates/syntax/src/ast/node_ext.rs [hunk 1]
```diff
@@ -572,6 +572,16 @@ impl ast::Item {
...
 }
 
+impl ast::Type {
+    pub fn generic_arg_list(&self) -> Option<ast::GenericArgList> {
+        if let ast::Type::PathType(path_type) = self {
+            path_type.path()?.segment()?.generic_arg_list()
+        } else {
+            None
+        }
+    }
```
Comment (Veykril) [inline crates/syntax/src/ast/node_ext.rs:582]: There maybe more than one generic arg list in a type, `Qux<(Foo<A, B>, Bar<C, D>>)` for example, also generic args might apear in other spots like `[T]`, `(T, U, V)` etc.

**Review by Veykril — APPROVED** [review]
Small comment, but thats something that could be addressed as a follow up

**Comment by Veykril** [comment]
Thanks!
@bors r+

File: crates/syntax/src/ast/node_ext.rs (hunk 1 above)
Comment (roife) [reply crates/syntax/src/ast/node_ext.rs:582]: Thank you for pointing this out! I hadn't considered this situation before.

These situations might make the analysis a bit more complex; I need to reorganize my current approach and think about how to elegantly address this issue. ❤️
