### PR TITLE
fix: Don't complete `;` when in closure return expression

### LINKED ISSUE #18130: The new complete semicolon feature fails with closures
Filling this mostly for myself so I remember to work on this later: when implementing the complete semicolon for unit returning functions feature, I forgot another incompliance: closure's last statement can be an expression, and commonly people do not wrap the closure's body in a block even when it returns `()`, but now we'll complete `;` which breaks it.

@rustbot claim

### PR DESCRIPTION
**Pull request by ChayimFriedman2**
Completing it will break syntax.

Fixes #18130.

### CODE REVIEW

File: crates/ide-completion/src/render/function.rs [hunk 1]
```diff
@@ -278,31 +278,44 @@ pub(super) fn add_call_parens<'b>(
...
-                ControlFlow::Continue(())
+        let inside_closure_ret = ctx.token.parent_ancestors().try_for_each(|ancestor| {
+            match_ast! {
+                match ancestor {
+                    ast::BlockExpr(_) => ControlFlow::Break(false),
+                    ast::ClosureExpr(_) => ControlFlow::Break(true),
+                    _ => ControlFlow::Continue(())
+                }
             }
         });
```
Comment (Veykril) [inline crates/ide-completion/src/render/function.rs:289]: Kind of missed this last time but we should do this traversal in the completion analysis and store the result where relevant, otherwise we redo this work for every function completion item

File: crates/ide-completion/src/render/function.rs [hunk 2]
```diff
@@ -278,31 +278,44 @@ pub(super) fn add_call_parens<'b>(
...
+            };
+            let complete_token = if in_match_arm { T![,] } else { T![;] };
+            if next_non_trivia_token.map(|it| it.kind()) != Some(complete_token) {
+                cov_mark::hit!(complete_semicolon);
+                let ch = if in_match_arm { ',' } else { ';' };
+                if snippet.ends_with("$0") {
+                    snippet.insert(snippet.len() - "$0".len(), ch);
+                } else {
+                    snippet.push(ch);
+                }
```
Comment (Veykril) [inline crates/ide-completion/src/render/function.rs:318]: Likewise for tihs (apart form what depends on the snippet / function to be rendered)

**Comment by ChayimFriedman2** [comment]
@Veykril, addressed comments.

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
