### PR TITLE
fix: escape keywords used as names in earlier editions

### LINKED ISSUE #13030: More unknown types in `webrender` after #12993
image

I don't know how this happened, but we're reporting more unknown types in the `bitflags!` expansions.

`webrender` is https://github.com/rust-lang/rustc-perf.git at `c52ee623e231e7690a93be88d943016968c1036b`.

EDIT:

Looks like manually expanding that macro makes the errors go away. Repro, note that the second item is needed:

```rust
# bitflags = "1.0"

use bitflags::bitflags;

bitflags! {
    #[repr(C)]
    pub struct FontInstanceFlags: u32 {
        const SYNTHETIC_ITALICS = 1 << 0;
        const SYNTHETIC_BOLD    = 1 << 1;
    }
}
```

Are we choking on `$crate`?

### PR DESCRIPTION
**Pull request by lowr**
Fixes #13030 

There are keywords in Rust 2018+ that you can use as names without escaping when your crate is in Rust 2015 e.g. "try". We need to be consistent on how to keep track of the names regardless of how they are actually written in each crate. This patch attempts at it by taking such names into account and storing them uniformly in their escaped form.

### CODE REVIEW

**Comment by lowr** [comment]
I wanted to add a test, but I couldn't figure out how (I manually tested and confirmed #13030 is resolved with the patch). I even doubt if it's possible for the time being. Ideally we want to test something like this in nameres tests:

```rust
//- /main.rs crate:main deps:liba edition:2015
#[macro_use]
extern crate liba;
use liba::try;

//- /lib.rs crate:liba edition:2018
#[macro_export]
macro_rules! r#try { () => {} }
```

but we cannot, because it seems we unconditionally parse `try` as keywords [**besides `try!` macro in expression position**](https://github.com/rust-lang/rust-analyzer/blob/3903243192d2bd6c38b43d12ffa9d2fa1601c2ec/crates/parser/src/grammar/expressions/atom.rs#L602-L603) and `use liba::try` would be syntax error. I'd appreciate if anyone could come up with a way.

File: crates/hir-expand/src/name.rs [hunk 1]
```diff
@@ -90,10 +90,16 @@ impl Name {
...
-        // keyword, we never need the prefix so we strip it.
         match raw_text.strip_prefix("r#") {
+            // When `raw_text` starts with "r#" but the name does not coincide with any
+            // keyword, we never need the prefix so we strip it.
             Some(text) if !is_raw_identifier(text) => Name::new_text(SmolStr::new(text)),
+            // Keywords (in the current edition) *can* be used as a name in earlier editions of
+            // Rust, e.g. "try" in Rust 2015. Even in such cases, we keep track of them in their
+            // escaped form.
+            None if is_raw_identifier(raw_text) => {
+                Name::new_text(["r#", raw_text].into_iter().collect())
```
Comment (Veykril) [inline crates/hir-expand/src/name.rs:101]:
```suggestion
                Name::new_text(SmolStr::from_iter(["r#", raw_text]))
```
Nit, but I believe this should also work

Comment (lowr) [reply crates/hir-expand/src/name.rs:101]: Yeah, that's definitely more readable, thanks!
