### PR TITLE
fix: Autocomplete for struct fields includes receiver

### LINKED ISSUE #12857: Autocomplete for fields of structs is not working(as expected)
**Text Editor**: VS Code 
If I'm typing I field of struct I need self to be autocompleted for me by rust-analyzer, 
Im getting the suggestion as ```self.field``` but after accepting the suggestion it is being replaced by ```field``` (```self``` is missing).

Before:
lib rs - raytracer  WSL_ Ubuntu  - Visual Studio Code 24-07-2022 00_25_48

Hint is ```self.length``` and that is correct 
After:
lib rs - raytracer  WSL_ Ubuntu  - Visual Studio Code 24-07-2022 00_28_12

It's being replaced by ```length``` not ```self.length```.

**rust-analyzer version**: 0.4.1133-standalone (30c4db10a 2022-07-19)

**rustc version**: rustc 1.64.0-nightly (7665c3543 2022-07-06)

**relevant settings**: everything default

### PR DESCRIPTION
**Pull request by DorianListens**
fixes #12857

### CODE REVIEW

File: crates/ide-completion/src/render.rs [hunk 1]
```diff
@@ -143,6 +143,11 @@ pub(crate) fn render_field(
     item.build()
 }
 
+fn field_with_reciever(receiver: Option<&hir::Name>, field_name: &str) -> SmolStr {
```
Comment (Veykril) [inline crates/ide-completion/src/render.rs:146]:
```suggestion
fn field_with_receiver(receiver: Option<&hir::Name>, field_name: &str) -> SmolStr {
```
