### PR TITLE
fix: Retrigger visibility completion after parentheses

### LINKED ISSUE #12390: `pub(crate)` completion leaves closing `)` behind
```rust
impl () {
    pub(crate) fn f() {}

    pu$0
}
```

Triggering completion here suggests `pub(crate)`. Then, after typing `b(c`, accepting the `pub(crate)` completion produces this:

```rust
impl () {
    pub(crate) fn f() {}

    pub(crate)$0)
}
```

1. That's wrong :)
2. The `pub(crate)` completion does not appear in `pub($0)`, which kinda makes sense (since `crate` by itself appears there), but I also feel like we should be consistent there, since you can "carry over" a completion when you request it after `pu$0`.

### PR DESCRIPTION
**Pull request by yue4u**
close #12390

This PR add `(` to trigger_characters as discussed in original issue.

Some questions:

1. Is lsp's `ctx.trigger_character` from `params.context` is the same as `ctx.original_token` inside actually completions? 
    1. If not what's the difference?
    2. if they are the same, it's unnecessary to pass it down from handler at all.
    3.  if they are the same, maybe we could parse it from fixture directly instead of using the `check_with_trigger_character` I added.
2. Some completion fixtures written as `($0)` ( https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/tests/fn_param.rs#L105 as an example), If I understand correctly they are not invoked outside tests at all?
    1. using `ctx.original_token` directly would break these tests as well as parsing trigger_character from fixture for now.
    2. I think it make sense to allow `(` triggering these cases?
3. I hope this line up with #12144

### CODE REVIEW

File: crates/ide-completion/src/lib.rs [hunk 1]
```diff
@@ -143,36 +143,40 @@ pub fn completions(
...
-        completions::record::complete_record_literal(acc, ctx);
-        completions::record::complete_record(acc, ctx);
-        completions::snippet::complete_expr_snippet(acc, ctx);
-        completions::snippet::complete_item_snippet(acc, ctx);
-        completions::trait_impl::complete_trait_impl(acc, ctx);
-        completions::r#type::complete_type_path(acc, ctx);
-        completions::r#type::complete_inferred_type(acc, ctx);
-        completions::use_::complete_use_tree(acc, ctx);
+        // prevent `(` from triggering unwanted completion noise
+        if trigger_character != Some("(") {
```
Comment (yue4u) [inline crates/ide-completion/src/lib.rs:154]: Could put this down to individual tests but I think it's harder to understand and will just messy the codebase more. Current approach do not scale very well if we want to allow `(` triggering more completions though.

File: crates/rust-analyzer/src/caps.rs [hunk 2]
```diff
@@ -29,7 +29,12 @@ pub fn server_capabilities(config: &Config) -> ServerCapabilities {
         hover_provider: Some(HoverProviderCapability::Simple(true)),
         completion_provider: Some(CompletionOptions {
             resolve_provider: completions_resolve_provider(config.caps()),
-            trigger_characters: Some(vec![":".to_string(), ".".to_string(), "'".to_string()]),
+            trigger_characters: Some(vec![
```
Comment (yue4u) [inline crates/rust-analyzer/src/caps.rs:32]: Are there some reasons for this not being a `Vec<char>`?

File: crates/rust-analyzer/src/handlers.rs [hunk 3]
```diff
@@ -796,27 +796,26 @@ pub(crate) fn handle_completion(
...
-    if completion_triggered_after_single_colon {
-        return Ok(None);
     }
 
     let completion_config = &snap.config.completion();
-    let items = match snap.analysis.completions(completion_config, position)? {
+    let items = match snap.analysis.completions(
+        completion_config,
+        position,
+        completion_trigger_character.as_deref(),
```
Comment (yue4u) [inline crates/rust-analyzer/src/handlers.rs:817]: I think `trigger_character` is a state as the same as `position` and putting it into `config` would be weird.

File: crates/rust-analyzer/src/caps.rs (hunk 2 above)
Comment (Veykril) [reply crates/rust-analyzer/src/caps.rs:32]: jsan has no notion of characters, so strings are used

File: crates/ide-completion/src/lib.rs (hunk 1 above)
Comment (Veykril) [reply crates/ide-completion/src/lib.rs:154]: Ye I think putting it here for now is fine, depending on the final state of the completion architecture we might wanna move this somewhere else.

**Comment by Veykril** [comment]
> Is lsp's ctx.trigger_character from params.context is the same as ctx.original_token inside actually completions? 

`ctx.trigger_character` is the character that triggered the completion, this is only set if the completion was in fact triggered by a character, if it was manually invoked the trigger character is none.

**Comment by Veykril** [comment]
Seems good to me overall, will wait on merging this until tomorrow though.
