### PR TITLE
fix: complete variants of hidden enums through public aliases

### LINKED ISSUE #21891: Cannot complete variant in hidden enum alias
**rust-analyzer version**: rust-analyzer 0.4.2833-standalone

**rustc version**: rustc 1.95.0-nightly (a293cc4af 2026-01-30)

**editor or extension**: Vim

**code snippet to reproduce**:

**src/lib.rs**:
```rust
#[doc(hidden)]
pub enum Foo {
    Variant,
}

pub type Bar = Foo;
```

**src/main.rs**:
```rust
fn main() {
    let x = mycrate::Bar::Var$0; // cannot complete Variant
}
```

### PR DESCRIPTION
**Pull request by Amit5601**
Fixes rust-lang/rust-analyzer#21891.

Previously, the completion engine would aggressively bail out if the parent enum was marked . This pushes the visibility check down to the individual variants so they can be properly completed when accessed via a public type alias.

### CODE REVIEW

File: crates/ide-completion/src/tests/item.rs [hunk 1]
```diff
@@ -380,3 +380,22 @@ foo!(f$0);
...
+fn completes_variant_through_hidden_enum_alias() {
+    check(
+        r#"
+#[doc(hidden)]
+pub enum Foo { Variant }
+
+pub type Bar = Foo;
+
+fn main() {
+    let x = Bar::V$0;
```
Comment (A4-Tacks) [inline crates/ide-completion/src/tests/item.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22003/64ddb549bc9a70d011328746fa46a8883f937b6b..6685b157a35161280864ee695a90bd94bd7ea912)*

This test is invalid, you need to reference it in another crate

**Review by A4-Tacks — CHANGES_REQUESTED** [review]

File: crates/ide-completion/src/completions.rs [hunk 2]
```diff
@@ -276,11 +276,9 @@ impl Completions {
         path_ctx: &PathCompletionCtx<'_>,
         e: hir::Enum,
     ) {
-        if !ctx.check_stability_and_hidden(e) {
-            return;
-        }
         e.variants(ctx.db)
             .into_iter()
+            .filter(|&variant| ctx.check_stability_and_hidden(variant))
```
Comment (A4-Tacks) [inline crates/ide-completion/src/completions.rs]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-analyzer/22003/64ddb549bc9a70d011328746fa46a8883f937b6b..6685b157a35161280864ee695a90bd94bd7ea912)*

This check is redundant, it already exists in add_enum_variant

**Review by A4-Tacks — CHANGES_REQUESTED** [review]

**Review by A4-Tacks — APPROVED** [review]
