### PR TITLE
fix: Prevent public re-export of private item

### LINKED ISSUE #18308: Import suggestions do not take into account visibility
I never had problems with this in the past, but suddenly rust-analyzer's import suggestions no longer take into account `pub` visibility. Unfortunately I don't have a minimal reproduction, but I do have a reproduction.

1. Clone `https://github.com/pola-rs/polars` (suggest `--depth 1`).
2. Edit file `crates/polars-expr/src/lib.rs`, add the following function:
  ```rust
fn foo() -> DataType {
    todo!()
}
```
3. Ask rust-analyzer to import `DataType` for you: Image
4. Suggestion is wrong, it's not visibile to us here, it suggests something else:
  Image
5. Suggestion is *still* wrong, it finally gets a public symbol:
  Image

**rust-analyzer version**: rust-analyzer version: 0.4.2148-standalone (418c1365e 2024-10-15) 

**rustc version**: rustc 1.83.0-nightly (ed04567ba 2024-09-28)

**editor or extension**: VS Code

**repository link (if public, optional)**: https://github.com/polar-rs/polars

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #18308

The original issue is quite complicated.
`polar-rs` monorepo has the following structure;

```rust
// crate polars-core
pub mod prelude {
    pub use crate::datatype::DataType;
}

// crate polars-ops
pub mod frame {
    pub use join::*;

    pub mod join {
        pub use hash_join::*;
        use polars_core::prelude::*;

        mod hash_join {
            pub use super::*;
        }
    }
}
```

1. The glob import `pub use super::*` inside `mod hash_join` reexports the visibility of the glob import `use polars_core::prelude::*` inside the `mod join` as "public", which was previously "module(join)"
2. The glob import `pub use hash_join::*` inside `mod join` overrides visibility of the previous visibility of the glob import `use polars_core::prelude::*` with "public" in 1., which was previously "module(join)"

The problematic step is 1., as rustc doesn't allow such re-export with E0603.
This PR prevent such "more visible" re-export by taking minimum of resolved item visibility and the re-export visibility

### CODE REVIEW

File: crates/hir-def/src/find_path.rs [hunk 1]
```diff
@@ -1047,7 +1047,7 @@ $0
         check_found_path(
             r#"
 mod bar {
-    mod foo { pub(super) struct S; }
+    mod foo { pub(crate) struct S; }
     pub(crate) use foo::S as U;
```
Comment (ShoyuVanilla) [inline crates/hir-def/src/find_path.rs:1051]: These test case is wrong. It emits `E0364` on rustc

```rust
mod bar {
    mod foo { pub(super) struct S; }
    pub(crate) use foo::S as U;
}

fn main() {}
```

```
error[E0364]: `S` is private, and cannot be re-exported
 --> src/main.rs:3:20
  |
3 |     pub(crate) use foo::S as U;
  |                    ^^^^^^^^^^^
  |
note: consider marking `S` as `pub` in the imported module
 --> src/main.rs:3:20
  |
3 |     pub(crate) use foo::S as U;
  |                    ^^^^^^^^^^^
```

**Comment by ShoyuVanilla** [comment]
BTW I spent most time on making a MCVE, as the original issue was quite hard to reproduce outside the `pola-rs` repository😅
Both `pub use super::*` and the importing order mattered

**Review by Veykril — APPROVED** [review]

**Comment by orlp** [comment]
Great work! Sorry for the large reproduction, I tried a bit to make it minimal but wasn't successful 😓.

**Comment by ShoyuVanilla** [comment]
> Great work! Sorry for the large reproduction, I tried a bit to make it minimal but wasn't successful 😓.

No worries 😅 The root causes were quite interwoven with each other and I just managed to made a MVCE with custom r-a build with extra tracings.
Thank you for maintaining `polars`, a great library for data manipulations

**Comment by lnicola** [comment]
This seems to have caused a regression in pattern type inferences:

image

**Comment by ShoyuVanilla** [comment]
> This seems to have caused a regression in pattern type inference:

Oh, I'll check about this

**Comment by ShoyuVanilla** [comment]
I ran `cargo run --release -p rust-analyzer -- unresolved-references .` and it seems that r-a isn't resolving the following layout things since this PR 🤔 
https://github.com/rust-lang/rust-analyzer/blob/f4466718b838de706d74e2c13f20a41c034d87a5/crates/hir/src/lib.rs#L1432

**Comment by ShoyuVanilla** [comment]
MCVE:

```rust
//- /main.rs crate:main deps:test_crate
use test_crate::foo; // not resolving this!

use foo::Foo;

//- /lib.rs crate:test_crate deps:test_crate2
extern crate test_crate2;

pub use test_crate2 as foo;

//- /lib2.rs crate:test_crate2
pub struct Foo;
```

It seems that I should exempt min visibility for `extern crate`, as it seems to be exceptional in rustc 🤔
