### PR TITLE
fix: Extract function from trait impl

### LINKED ISSUE #10036: Extract to function assist implements nonexistent trait methods
Using `extract to function` inside a method in a trait impl block on some code that uses `self` generates a trait method named `fun_name`. It should instead find an inherent impl block with the same bounds or create one, and place the method there.

### PR DESCRIPTION
**Pull request by DorianListens**
This change fixes #10036, "Extract to function assist implements nonexistent
trait methods".

When we detect that the extraction is coming from within a trait impl, and that
a `self` param will be necessary, we adjust which `SyntaxNode` to `insert_after`,
and create a new empty `impl` block for the newly extracted function.

### CODE REVIEW

File: crates/ide-assists/src/handlers/extract_function.rs [hunk 1]
```diff
@@ -485,6 +503,20 @@ impl FunctionBody {
...
 
+    fn node(&self) -> &SyntaxNode {
+        match self {
+            FunctionBody::Expr(e) => e.syntax(),
+            FunctionBody::Span { parent, .. } => parent.syntax(),
+        }
+    }
+
+    fn extracted_from_trait_impl(&self) -> bool {
+        match self.node().ancestors().find_map(ast::Impl::cast) {
```
Comment (jonas-schievink) [inline crates/ide-assists/src/handlers/extract_function.rs:514]: I think this won't work if the function comes from a macro. But that might be okay for now.

**Comment by jonas-schievink** [comment]
@bors r+

(but this might conflict with https://github.com/rust-lang/rust-analyzer/pull/12706)
