### PR TITLE
fix: Fix "needless return" diagnostic for trailing item declarations

### LINKED ISSUE #16566: Incorrect `replace return <expr>; with <expr>` diagnostic
https://github.com/rust-lang/rust-analyzer/blob/1e6cef94dfbc359e7b1e7d392de387c2c539b965/crates/mbe/src/expander/matcher.rs#L184

The transformation here is is not valid so the diagnostic shouldnt' trigger

### PR DESCRIPTION
**Pull request by davidsemakula**
Fixes #16566

### CODE REVIEW

File: crates/hir-def/src/hir.rs [hunk 1]
```diff
@@ -175,6 +175,7 @@ pub enum Expr {
         statements: Box<[Statement]>,
         tail: Option<ExprId>,
         label: Option<LabelId>,
+        has_trailing_item_decl: bool,
```
Comment (Veykril) [inline crates/hir-def/src/hir.rs:178]: Hmm, this feels wrong to me. I think a better approach at fixing this is to not drop item statements on lowering and instead lower them to an empty `Statement::Item` kind for now (we can give it fields once we make actualyl use of that).

Comment (davidsemakula) [reply crates/hir-def/src/hir.rs:178]: Alright, I'll change to the suggested approach ... I initially went with this because I thought it was the least invasive approach 🙂

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+
