### PR TITLE
fix: use `ast::TokenTree` in `make::expr_macro`

### LINKED ISSUE #19584: [syntax] `make::expr_macro_call` should receive a token tree instead of arg list
https://github.com/rust-lang/rust-analyzer/blob/aded72f8e6048b243e20e0b77a3870b1b76ef62d/crates/syntax/src/ast/make.rs#L646

The correct way to build a macro call is with the token tree - it need not be an arg  list.

### PR DESCRIPTION
**Pull request by snprajwal**
Fixes rust-lang/rust-analyzer#19584

### CODE REVIEW

File: crates/syntax/src/ast/make.rs [hunk 1]
```diff
@@ -116,6 +112,10 @@ pub mod ext {
     pub fn ty_result(t: ast::Type, e: ast::Type) -> ast::Type {
         ty_from_text(&format!("Result<{t}, {e}>"))
     }
+
+    pub fn token_tree_from_arg_list(arg_list: ast::ArgList) -> ast::TokenTree {
```
Comment (Veykril) [inline crates/syntax/src/ast/make.rs:116]: We can generalize this I think
```suggestion
    pub fn token_tree_from_node(node: &SyntaxNode) -> ast::TokenTree {
```
we effectively just want to turn any nodes tokens into a `TokenTree` so might as well make this API "untyped" in that regard

Comment (snprajwal) [reply crates/syntax/src/ast/make.rs]: Nice catch, updated!

**Review by Veykril — APPROVED** [review]
thanks!
