### PR TITLE
Fix `tt::Punct`'s spacing calculation

### LINKED ISSUE #13499: Invalid macro expansion when async-trait and duplicate_item macros are used together
I think this is a regression. I don't know when it happened, but judging by the commit date of the code where I see this broken today, it was 5 months ago (May 26th, 2022). I wouldn't leave it like this if it didn't work at that time for sure.

[Reproduction repository](https://github.com/Veetaha/rust-analyzer-async-trait-duplicate-conflict).

<details>
<summary>Screenshot</summary>

image

</details>

Code:

```rust
use async_trait::async_trait;
use duplicate::duplicate_item;

#[async_trait]
pub trait Foo {
    #[duplicate_item(
        var;
        [foo];
    )]
    async fn foo(&self);
}

pub fn foo(val: &dyn Foo) {


    let _ = val.foo();
}
```

Result of "Expand macro recursively":
```rust
// Recursive expansion of async_trait! macro
// ==========================================

pub trait Foo {
    compile_error! {
      "Unexpected token. Expected substitution identifier or ';' instead."
    }
}
```

# Expected

The usage of `duplicate_item` here is actually noop. I.e. it just leaves the decorated trait method as is. Rust-analyzer should see this, and correctly resolve the trait method.

# Actual

Rust-analyzer fails to expand the macro, so the trait method isn't seen in completions and isn't highlighted.

# Meta

**rust-analyzer version**: 0.3.1258-standalone

**rustc version**: 1.64.0 (a55dd71d5 2022-09-19)

**relevant settings**:

This works both with async-trait macro enabled and disabled in the settings via:
```json
"rust-analyzer.procMacro.ignored": {
    "async-trait": ["async_trait"]
}
```
I have it disabled in the settings during regular development

### PR DESCRIPTION
**Pull request by lowr**
Fixes #13499

We currently set a `tt::Punct`'s spacing to `Spacing::Joint` unless its next token is a trivia (i.e. whitespaces or comment). As I understand it, rustc only [sets `Spacing::Joint` if the next token is an operator](https://github.com/rust-lang/rust/blob/5b3e9090757da9a95b22f589fe39b6a4b5455b96/compiler/rustc_parse/src/lexer/tokentrees.rs#L77-L78) and we should follow it to guarantee the consistent behavior of proc macros.

### CODE REVIEW

File: crates/hir-expand/src/fixup.rs [hunk 1]
```diff
@@ -488,6 +484,7 @@ fn foo () {a .__ra_fixup ;}
     }
 
     #[test]
+    #[ignore]
```
Comment (lowr) [inline crates/hir-expand/src/fixup.rs:487]: These two tests fail in [this assertion](https://github.com/rust-lang/rust-analyzer/blob/df3877037e448ca90b17525b00418a2c30da8ddb/crates/hir-expand/src/fixup.rs#L351-L354). This is because dummy ident insertion (to fix up the syntax error) changes the spacing of puncts before it with this patch. Although technically we can record and reverse it to preserve the spacing of the puncts in invalid syntax, it'd be somewhat complex and I'm wondering how essential this invariant to preserve the original tokentree is w.r.t. puncts' spacing.

Comment (Veykril) [reply crates/hir-expand/src/fixup.rs:487]: Hm, it seems odd to me that we check if *spacing* is preserved, macros already don't care about spacing so I don't think the tests should either, not sure how simple it'd would be but can we just check the tokens for equality ignoring any whitespace tokens in between?

Comment (lowr) [reply crates/hir-expand/src/fixup.rs:487]: Yeah that's what I was thinking. I'll see how I can "fix" the tests without complicating much.

cc @flodiebold for you're the original author (#11444), if you have anything to add.

**Comment by Veykril** [comment]
We really ought to look into fixing that damn syntax highlighting test that keeps failing randomly (though maybe we are slightly quadratic and just dancing on a thin line there)

@bors r+
