### PR TITLE
fix: Panic while hovering associated function with type annotation on generic param that not inherited from its container type

### LINKED ISSUE #17871: Chalk panic on displaying type of trait function with type parameter
**rust-analyzer version**: rust-analyzer 0.0.0 (18414cdf64 2024-08-12)

**rustc version**: rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**code snippet to reproduce**: 
```rust
trait T {
    fn f<A>();
}

struct S {}
impl T for S {
    fn f<A>() {}
}

fn main() {
    let x = S::f::<i32>;
}
```
Panic:
```
thread 'main' panicked at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/lib.rs:2238:9:
assertion `left == right` failed
  left: 2
 right: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:363:5
   4: chalk_ir::Binders<T>::substitute
             at /Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.98.0/src/lib.rs:2238:9
   5: hir_ty::display::generic_args_sans_defaults::{{closure}}::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/display.rs:1468:33
   6: <core::option::Option<T> as stdx::IsNoneOr>::is_none_or
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/stdx/src/lib.rs:317:24
   7: hir_ty::display::generic_args_sans_defaults::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/display.rs:1465:21
   8: hir_ty::display::generic_args_sans_defaults
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/display.rs:1473:24
   9: <chalk_ir::Ty<hir_ty::interner::Interner> as hir_ty::display::HirDisplay>::hir_fmt
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/display.rs:1031:29
  10: hir_ty::display::HirDisplayWrapper<T>::write_to
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/hir-ty/src/display.rs:399:9
  11: ide::inlay_hints::label_of_ty::rec
  12: ide::inlay_hints::label_of_ty
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/inlay_hints.rs:430:13
  13: ide::inlay_hints::bind_pat::hints
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/inlay_hints/bind_pat.rs:70:21
  14: ide::inlay_hints::hints
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/inlay_hints.rs:590:25
  15: ide::inlay_hints::inlay_hints::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/inlay_hints.rs:508:28
  16: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/traits/iterator.rs:815:29
  17: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/adapters/map.rs:89:21
  18: core::iter::adapters::filter_map::filter_map_fold::{{closure}}
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/adapters/filter_map.rs:40:20
  19: core::iter::traits::iterator::Iterator::fold
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/traits/iterator.rs:2589:21
  20: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/adapters/filter_map.rs:148:9
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/adapters/map.rs:129:9
  22: core::iter::traits::iterator::Iterator::for_each
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/iter/traits/iterator.rs:818:9
  23: ide::inlay_hints::inlay_hints
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/inlay_hints.rs:517:21
  24: ide::Analysis::inlay_hints::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/lib.rs:434:27
  25: ide::Analysis::with_db::{{closure}}
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/lib.rs:824:29
  26: std::panicking::try::do_call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  27: std::panicking::try
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
  28: std::panic::catch_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  29: salsa::Cancelled::catch
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/salsa/src/lib.rs:633:15
  30: ide::Analysis::with_db
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/lib.rs:824:9
  31: ide::Analysis::inlay_hints
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/lib.rs:434:9
  32: ide::static_index::StaticIndex::add_file
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/static_index.rs:126:27
  33: ide::static_index::StaticIndex::compute
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/ide/src/static_index.rs:257:13
  34: rust_analyzer::cli::scip::<impl rust_analyzer::cli::flags::Scip>::run
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/rust-analyzer/src/cli/scip.rs:66:18
  35: rust_analyzer::actual_main
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:88:46
  36: rust_analyzer::main
             at /Users/davidrichey/Desktop/test/rust-analyzer/crates/rust-analyzer/src/bin/main.rs:39:9
  37: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #17871

We call `generic_args_sans_defaults` here;

https://github.com/rust-lang/rust-analyzer/blob/64a140527b383e3a2fe95908881624fc5374c60c/crates/hir-ty/src/display.rs#L1021-L1034

but the following substitution inside that function panic in #17871;

https://github.com/rust-lang/rust-analyzer/blob/64a140527b383e3a2fe95908881624fc5374c60c/crates/hir-ty/src/display.rs#L1468

it's because the `Binders.binder` inside `default_parameters` has a same length with the generics of the function we are hovering on, but the generics of it is split into two, `fn_params` and `parent_params`.
Because of this, it may panic if the function has one or more default parameters and both `fn_params` and `parent_params` are non-empty, like the case in the title of this PR.

So, we must call `generic_args_sans_default` first and then split it into `fn_params` and `parent_params`

### CODE REVIEW

File: crates/ide/src/hover/tests.rs [hunk 1]
```diff
@@ -8602,3 +8602,31 @@ fn test() {
...
+fn main() {
+    let x$0 = S::f::<i32>;
+}
+"#,
+        expect![[r#"
+            *x*
+
+            ```rust
+            // size = 0, align = 1
+            let x: fn f<S, i32>()
```
Comment (Veykril) [inline crates/ide/src/hover/tests.rs:8628]: Hmm, this does look like the wrong way to render this doesn't it. Ideally we'd render this as `fn <S as T>::f::<i32>()` or so?

Comment (ShoyuVanilla) [reply crates/ide/src/hover/tests.rs:8628]: Yes, I think so, too. Currently we are rendering such container type into `<>` when rendering associated function

rust-analyzer 1.80.0 (05147895 2024-07-21)
image

And we can find such things in many places of our test cases like
https://github.com/rust-lang/rust-analyzer/blob/2b866390189d99191c51e1fe154e94a933c24b0f/crates/hir-ty/src/tests/traits.rs#L1108

I tried to fix them altogather when I was dealing with this issue, but it seems that our generic displaying has many problems that should be dealt with - especially when there are 'parent' generic parameters -, so I just turned to fix this panic with minimal touch and file the issue in proper way 🤔

Comment (Veykril) [reply crates/ide/src/hover/tests.rs:8628]: Yes, there was no need to do all of that in this PR given its separate issues

Comment (ShoyuVanilla) [reply crates/ide/src/hover/tests.rs:8628]: One thing I think that strange is;

We are rendering generics in many cases with `fn hir_fmt_generic_arguments`

https://github.com/rust-lang/rust-analyzer/blob/2b866390189d99191c51e1fe154e94a933c24b0f/crates/hir-ty/src/display.rs#L1484-L1518

and this moves lifetimes before the type and const parameters as it assumes that the input it gets has types and const parameters before the lifetime parameters, as `generics.iter()` gives them in this order;

https://github.com/rust-lang/rust-analyzer/blob/2b866390189d99191c51e1fe154e94a933c24b0f/crates/hir-ty/src/generics.rs#L88-L95

But this function does not do such re-ordering to parent parameters and we only do such re-ordering manually in the block I've modified in this PR.

So, in other types the parent generics can be renderered in the rear position of the generic parameters and I'm not sure whether that's correct.

And If we should do such re-ordering everywhere we have to thinkabout grand-parent generics as well, I think 🤔 

Furthermore, in `fn generic_args_sans_defaults`, we assume that the default parameters are comming in the consecutive last some parameters and this is correct in general in proper rust syntax(L1476)

https://github.com/rust-lang/rust-analyzer/blob/2b866390189d99191c51e1fe154e94a933c24b0f/crates/hir-ty/src/display.rs#L1431-L1482 

But I think that this can be problematic if we have both non-empty self parameters and parent parameters, and they are have some both defaults and non defaults.
In this case, aren't we losing some non-default generic parameter of the parent? 🤔

Comment (ShoyuVanilla) [reply crates/ide/src/hover/tests.rs:8628]: So, I'm just trying to specify the exact problems we have here with some experiments 😅

Comment (Veykril) [reply crates/ide/src/hover/tests.rs:8628]: That might be leftovers, we used to have lifetimes after type/const params, but we've since fixed that order.

> grand-parent generics as well, I think 

I don't think Rust currently has that anywhere?

Comment (Veykril) [reply crates/ide/src/hover/tests.rs:8628]: In general the order ought to be https://github.com/rust-lang/rust-analyzer/blob/bd4785a6f017ec52bc0fb6c061c5f42228946462/crates/hir-ty/src/generics.rs#L1-L9
now
