### PR TITLE
fix: don't include `r#` prefix in filesystem changes

### LINKED ISSUE #14131: Renaming a module to a raw identifier shouldn’t rename the module file to the raw identifier name
For instance, if you were to name a module `r#macro`, the file should be renamed to `macro.rs` or `macro/lib.rs`, not `r#macro.rs`.

**rust-analyzer version**: 2023-01-23

**rustc version**: rustc 1.69.0-nightly (2773383a3 2023-02-10)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
None

### PR DESCRIPTION
**Pull request by lowr**
Fixes #14131 

In addition to fix for #14131, this PR adds raw ident validity checks in rename functionality that we've been missing.

### CODE REVIEW

File: crates/ide-db/src/rename.rs [hunk 1]
```diff
@@ -532,7 +537,14 @@ impl IdentifierKind {
     pub fn classify(new_name: &str) -> Result<IdentifierKind> {
         match parser::LexedStr::single_token(new_name) {
             Some(res) => match res {
-                (SyntaxKind::IDENT, _) => Ok(IdentifierKind::Ident),
+                (SyntaxKind::IDENT, _) => {
+                    if let Some(inner) = new_name.strip_prefix("r#") {
+                        if matches!(inner, "self" | "crate" | "super" | "Self") {
```
Comment (Veykril) [inline crates/ide-db/src/rename.rs:542]: This should fail some tests, we have a bit of logic that allows renaming an assoc function parameter to `self`

**Review by Veykril — APPROVED** [review]
We gotta wait with merging for a bit due to a subtree sync going on right now
