### PR TITLE
fix: Ignore auto-import assist on parameter names

### LINKED ISSUE #13105: Autoimport assist triggers on parameter names
```rust
fn foo(path: &str) {}
```
If I put the cursor on `path`, I get "Import `std::path`" as a suggestion. That probably shouldn't be there.

### PR DESCRIPTION
**Pull request by volsa**
Fixes #13105; before & after

https://user-images.githubusercontent.com/29666622/195999489-0474c93a-b2bf-41c4-b7da-a4242a8082d8.mov

https://user-images.githubusercontent.com/29666622/195999571-605ee09c-bc6f-4ee5-bfe4-73e37254c647.mov

### CODE REVIEW

File: crates/ide-assists/src/handlers/auto_import.rs [hunk 1]
```diff
@@ -156,6 +156,8 @@ pub(super) fn find_importable_node(
     {
         ImportAssets::for_method_call(&method_under_caret, &ctx.sema)
             .zip(Some(method_under_caret.syntax().clone().into()))
+    } else if let Some(_) = ctx.find_node_at_offset_with_descend::<ast::Param>() {
```
Comment (volsa) [inline crates/ide-assists/src/handlers/auto_import.rs:159]: I'm not sure if `if let Some(_) = ...` rather than `.is_some()` is the preferred style here but as every other if statement uses `let Some(...) = ...` I thought I'd do the same

**Review by Veykril — APPROVED** [review]
