### PR TITLE
Clamp Position::character to line length

### LINKED ISSUE #18240: Position.character is not clamped to line length
[LSP says](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position) about `Position::character`

> If the character value is greater than the line length it defaults back
> to the line length.

but `from_proto::offset()` doesnt' implement this 

```
    let text_size = line_index.index.offset(line_col).ok_or_else(|| {
        format_err!("Invalid offset {line_col:?} (line index length: {:?})", line_index.index.len())
    })?;
```

I hit this because rust-analyzer crashes with the kakoune-lsp client because -- if there is no code action in the selection -- this client falls back to requesting code actions for the whole line by simply specifying `Position::character=1e6`.
I worked around the crash by sending the actual line length instead.

I'm not yet sure what we should do, following the protocol can help but the downside is that we're masking potential bugs

I haven't yet found a case where a client inherently needs this behavior, so it doesn't seem important.

### PR DESCRIPTION
**Pull request by krobelus**
LSP says about Position::character

> If the character value is greater than the line length it defaults back to the line length.

but from_proto::offset() doesn't implement this.

A client might for example request code actions for a whole line by sending
Position::character=99999.  I don't think there is ever a reason (besides laziness) why the
client can't specify the line length instead but I guess we should not crash but follow protocol.

Not sure how to update Cargo.lock (lib/README.md doesn't say how).

Fixes #18240

### CODE REVIEW

File: crates/rust-analyzer/src/lsp/from_proto.rs [hunk 1]
```diff
@@ -35,9 +35,20 @@ pub(crate) fn offset(
...
-    })?;
+    let (text_size, clamped_length) =
+        line_index.index.offset_clamped(line_col).ok_or_else(|| {
+            format_err!(
+                "Invalid offset {line_col:?} (line index length: {:?})",
+                line_index.index.len()
+            )
+        })?;
+    if let Some(clamped_length) = clamped_length {
+        tracing::error!(
```
Comment (ChayimFriedman2) [inline crates/rust-analyzer/src/lsp/from_proto.rs:46]: If LSP allows that, should we warn at it?

The answer probably lies in whether there are some client that deliberately sends longer line lengths. But if not, then maybe we don't want to merge this...

**Comment by Veykril** [comment]
> Not sure how to update Cargo.lock (lib/README.md doesn't say how).

We'll need to split the PR, iirc our CI auto publishes the library folder if the versions change so we need the library change first, then a separate PR to bump the dependency.

File: crates/rust-analyzer/src/lsp/from_proto.rs (hunk 1 above)
Comment (krobelus) [reply crates/rust-analyzer/src/lsp/from_proto.rs:46]: > The answer probably lies in whether there are some client that deliberately sends longer line lengths

Indirectly yes. But the more direct answer is in the specification (unless we want to deliberately deviate from that which would be surprising).
Ideally I'd prefer following the spec today but also remove this feature from the spec later (assuming no client needs it).
Since it's allowed by the spec I agree we shouldn't error. But I think a warning would be appropriate; if nothing else it will help us find out which client wants to use this feature.

Assuming we want to warn, we can define our own LSP protocol extension that clients can opt into.
Say we call it `strict-mode`.
Then we can suppress the warning by default and only print it if strict mode is enabled.
LSP is sometimes a bit underspecified, meaning that servers and clients have to implement multiple different ways the protocol could be interpreted. We could use a strict mode as a means to eventually simplify the spec..

I'd also be fine with simply dropping the warning but I guess I have a slight preference for keeping it.

This crash is not necessarily an important issue but I believe I've hit it occasionally over a few years and didn't notice the crash because my client restarts `rust-analyzer` automatically on crash. I got better error propagation set up now.

File: Cargo.toml [hunk 2]
```diff
@@ -40,7 +40,7 @@ debug = 2
 # chalk-ir = { path = "../chalk/chalk-ir" }
 # chalk-recursive = { path = "../chalk/chalk-recursive" }
 # chalk-derive = { path = "../chalk/chalk-derive" }
-# line-index = { path = "lib/line-index" }
+line-index = { path = "lib/line-index" }
```
Comment (Veykril) [inline Cargo.toml:43]: Please split this PR up into two, one changing the lib/line-index crate, that we then merge and have a patch release done by. Then we can rebase this PR on top to use the new release

File: crates/rust-analyzer/src/lsp/from_proto.rs (hunk 1 above)
Comment (Veykril) [reply crates/rust-analyzer/src/lsp/from_proto.rs:46]: I'd say lets keep the log for now, and see if any client is being spammy with this or not

File: lib/line-index/src/lib.rs [hunk 3]
```diff
@@ -136,6 +136,22 @@ impl LineIndex {
         self.start_offset(line_col.line as usize).map(|start| start + TextSize::from(line_col.col))
     }
 
+    /// Transforms the `LineCol` into a `TextSize`. If the column exceeds the line length,
+    /// the line, it is clamped to that.
```
Comment (Veykril) [inline lib/line-index/src/lib.rs:140]: Might be good to describe the return types here then, its not immediately obvious what they mean

File: lib/line-index/src/lib.rs [hunk 4]
```diff
@@ -177,10 +177,18 @@ impl LineIndex {
...
+        let next_newline = self.newlines.get(line as usize).copied().unwrap_or(self.len);
+        let line_length = next_newline - start;
+        Some(TextRange::new(start, start + line_length))
+    }
+
     /// Given a range [start, end), returns a sorted iterator of non-empty ranges [start, x1), [x1,
     /// x2), ..., [xn, end) where all the xi, which are positions of newlines, are inside the range
     /// [start, end).
-    pub fn lines(&self, range: TextRange) -> impl Iterator<Item = TextRange> + '_ {
+    pub fn lines_in_range(&self, range: TextRange) -> impl Iterator<Item = TextRange> + '_ {
```
Comment (Veykril) [inline lib/line-index/src/lib.rs:191]: This is a semver breaking change to the signatures so we'd need to release a `0.2.0` release then if we rename this function, should be fine to keep it as `lines`

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
Thanks!
@bors r+

**Comment by Veykril** [comment]
Ah CI is still borked (not from your PR)
@bors r-
